// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AcompanhamentoGuias
    {
        public int IdAcompanhamentoGuia { get; set; }
        public int IdAtendimento { get; set; }
        public int IdStatus { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtRegistro { get; set; }
        public string NrTelefone { get; set; }
        public string NmAtendente { get; set; }
        public string TxObservacao { get; set; }

        public virtual Atendimento IdAtendimentoNavigation { get; set; }
        public virtual AcompanhamentoGuiasStatus IdStatusNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}