// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AgendaProfissionalSaudeBloqueioOperadoraHorario
    {
        public int IdConfigAgendaBloqueioProfissionalOperadora { get; set; }
        public int IdOperadora { get; set; }
        public int IdProfissionalSaude { get; set; }
        public int? IdDiaSemana { get; set; }
        public DateTime HrInicio { get; set; }
        public DateTime HrFim { get; set; }

        public virtual TipoDiversos IdDiaSemanaNavigation { get; set; }
    }
}