// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AgendaSadtServico
    {
        public int IdAgenda { get; set; }
        public int IdServico { get; set; }
        public int? IdRegiaoAplicacao { get; set; }
        public double? VlServico { get; set; }

        public virtual Servico IdServicoNavigation { get; set; }
    }
}