// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AgendaFarmacia
    {
        public AgendaFarmacia()
        {
            AgendaFarmaciaPeriodoAtendido = new HashSet<AgendaFarmaciaPeriodoAtendido>();
            AgendaFarmaciaUnidadeOrganizacional = new HashSet<AgendaFarmaciaUnidadeOrganizacional>();
        }

        public int IdAgendaFarmacia { get; set; }
        public DateTime HrInicioPeriodo { get; set; }
        public DateTime HrFimPeriodo { get; set; }

        public virtual ICollection<AgendaFarmaciaPeriodoAtendido> AgendaFarmaciaPeriodoAtendido { get; set; }
        public virtual ICollection<AgendaFarmaciaUnidadeOrganizacional> AgendaFarmaciaUnidadeOrganizacional { get; set; }
    }
}