// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AgendaHd
    {
        public AgendaHd()
        {
            AgendaHdCorpoClinico = new HashSet<AgendaHdCorpoClinico>();
            AgendaHdServico = new HashSet<AgendaHdServico>();
        }

        public int IdAgenda { get; set; }
        public DateTime DtAgenda { get; set; }
        public int IdSala { get; set; }
        public int? IdPaciente { get; set; }
        public string TxObservacao { get; set; }
        public string NmPaciente { get; set; }
        public int? NrIdade { get; set; }
        public string NrTelefone { get; set; }
        public int? NrLeito { get; set; }
        public string TxJustificativa { get; set; }
        public int? IdPlano { get; set; }
        public int? IdMedico { get; set; }
        public bool InPacienteInternado { get; set; }
        public int? IdAnestesia { get; set; }
        public int IdHorario { get; set; }
        public int? IdStatusAgenda { get; set; }
        public string TxExameNaoInformado { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual TipoDiversos IdAnestesiaNavigation { get; set; }
        public virtual HorarioHemodinamica IdHorarioNavigation { get; set; }
        public virtual Pessoa IdMedicoNavigation { get; set; }
        public virtual Pessoa IdPacienteNavigation { get; set; }
        public virtual UnidadeOrganizacional IdSalaNavigation { get; set; }
        public virtual ICollection<AgendaHdCorpoClinico> AgendaHdCorpoClinico { get; set; }
        public virtual ICollection<AgendaHdServico> AgendaHdServico { get; set; }
    }
}