// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AgendamentoPagamento
    {
        public int IdAgendamentoPagamento { get; set; }
        public string IdAgenda { get; set; }
        public string IdIntegracao { get; set; }
        public string IdPagamento { get; set; }
        public string Json { get; set; }
        public string DataPagamento { get; set; }
        public decimal Valor { get; set; }
        public string Link { get; set; }
        public string Status { get; set; }
    }
}