// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AgendaHdServico
    {
        public int IdAgenda { get; set; }
        public int IdServico { get; set; }
        public bool InPrincipal { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual AgendaHd IdAgendaNavigation { get; set; }
        public virtual Servico IdServicoNavigation { get; set; }
    }
}