// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AgrupamentoMaterial
    {
        public AgrupamentoMaterial()
        {
            AgrupamentoMaterialProduto = new HashSet<AgrupamentoMaterialProduto>();
            AgrupamentoMaterialUnidadeOrganizacional = new HashSet<AgrupamentoMaterialUnidadeOrganizacional>();
            DispensacaoEnfermagem = new HashSet<DispensacaoEnfermagem>();
        }

        public int IdAgrupamentoMaterial { get; set; }
        public string NmAgrupamentoMaterial { get; set; }
        public int IdUsuarioResponsavel { get; set; }
        public bool InAtivo { get; set; }

        public virtual Usuario IdUsuarioResponsavelNavigation { get; set; }
        public virtual ICollection<AgrupamentoMaterialProduto> AgrupamentoMaterialProduto { get; set; }
        public virtual ICollection<AgrupamentoMaterialUnidadeOrganizacional> AgrupamentoMaterialUnidadeOrganizacional { get; set; }
        public virtual ICollection<DispensacaoEnfermagem> DispensacaoEnfermagem { get; set; }
    }
}