// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AgrupamentoMaterialProduto
    {
        public AgrupamentoMaterialProduto()
        {
            AgrupamentoMaterialProdutoHistorico = new HashSet<AgrupamentoMaterialProdutoHistorico>();
        }

        public int IdAgrupamentoMaterial { get; set; }
        public int IdProdutoDetalhe { get; set; }
        public bool InFracionado { get; set; }
        public int QnMaterial { get; set; }
        public int IdUnidadeConsumo { get; set; }

        public virtual AgrupamentoMaterial IdAgrupamentoMaterialNavigation { get; set; }
        public virtual ProdutoDetalhe IdProdutoDetalheNavigation { get; set; }
        public virtual TipoDiversos IdUnidadeConsumoNavigation { get; set; }
        public virtual ICollection<AgrupamentoMaterialProdutoHistorico> AgrupamentoMaterialProdutoHistorico { get; set; }
    }
}