// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Alimento
    {
        public int IdAlimento { get; set; }
        public string NmAlimento { get; set; }
        public decimal QnCentesimal { get; set; }
        public int IdUnidadeMedida { get; set; }
        public decimal QnKcalorias { get; set; }
        public string TxObservacao { get; set; }
        public int IdUsuarioCadastro { get; set; }
        public int IdUsuarioAlteracao { get; set; }
        public DateTime DtCadastro { get; set; }
        public DateTime DtAlteracao { get; set; }
        public bool InAtivo { get; set; }
    }
}