// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AnaliseUnimed
    {
        public int IdConta { get; set; }
        public int IdFechamentoItem { get; set; }
        public bool? InGlosaDevida { get; set; }
        public string TxObsRecursoUnimed { get; set; }
        public string TxSrpm { get; set; }
        public decimal? QtRevertida { get; set; }
        public int? IdMapaRev { get; set; }
        public decimal? QnCobrado { get; set; }
        public decimal? QnGlosado { get; set; }
        public decimal? VlCobrado { get; set; }
        public decimal? VlGlosado { get; set; }
        public int? IdRespostaAnalise { get; set; }
        public int? IdUsuario { get; set; }
        public DateTime? DtAnalise { get; set; }

        public virtual RespostaAnaliseUnimed IdRespostaAnaliseNavigation { get; set; }
    }
}