// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AnaliseBffg
    {
        public int Id { get; set; }
        public string Tabela { get; set; }
        public int Linhas { get; set; }
    }
}