// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AntecipacaoEntrega
    {
        public AntecipacaoEntrega()
        {
            AntecipacaoEntregaProduto = new HashSet<AntecipacaoEntregaProduto>();
        }

        public int IdAntecipacaoEntrega { get; set; }
        public int NrCupom { get; set; }
        public int IdFornecedor { get; set; }
        public DateTime DtEntrega { get; set; }

        public virtual Pessoa IdFornecedorNavigation { get; set; }
        public virtual ICollection<AntecipacaoEntregaProduto> AntecipacaoEntregaProduto { get; set; }
    }
}