// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AntimicrobianoPedidoMicroorganismoIsolado
    {
        public int IdPedidoAntimicrobiano { get; set; }
        public int IdMicroorganismoIsolado { get; set; }

        public virtual TipoDiversos IdMicroorganismoIsoladoNavigation { get; set; }
        public virtual AntimicrobianoPedido IdPedidoAntimicrobianoNavigation { get; set; }
    }
}