// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ArquivoUnimed
    {
        public ArquivoUnimed()
        {
            CreditoEstorno = new HashSet<CreditoEstorno>();
            LinhaArquivoRetorno = new HashSet<LinhaArquivoRetorno>();
            LinhaRetornoUnimed = new HashSet<LinhaRetornoUnimed>();
        }

        public int IdArquivoUnimed { get; set; }
        public string NmArquivoUnimed { get; set; }
        public DateTime? DtGravacao { get; set; }
        public DateTime? DtLeitura { get; set; }
        public bool? InProcessoRetorno { get; set; }
        public int? IdUsuario { get; set; }
        public bool? InSobreposto { get; set; }
        public DateTime? DtSobreposicao { get; set; }
        public int? IdOperadorarecebimento { get; set; }

        public virtual OperadoraRecebimento IdOperadorarecebimentoNavigation { get; set; }
        public virtual ICollection<CreditoEstorno> CreditoEstorno { get; set; }
        public virtual ICollection<LinhaArquivoRetorno> LinhaArquivoRetorno { get; set; }
        public virtual ICollection<LinhaRetornoUnimed> LinhaRetornoUnimed { get; set; }
    }
}