// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ArquivoContabil
    {
        public ArquivoContabil()
        {
            ArquivoContabilGerado = new HashSet<ArquivoContabilGerado>();
            ArquivoContabilItem = new HashSet<ArquivoContabilItem>();
        }

        public int IdArquivoContabil { get; set; }
        public string NmArquivoContabil { get; set; }
        public string NmProcedureASerExecutada { get; set; }
        public string NmParametrosProcedure { get; set; }
        public bool? InAtivo { get; set; }
        public string TxSqlOrder { get; set; }

        public virtual ICollection<ArquivoContabilGerado> ArquivoContabilGerado { get; set; }
        public virtual ICollection<ArquivoContabilItem> ArquivoContabilItem { get; set; }
    }
}