// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ArquivoRemessaLayoutOperadora
    {
        public int IdArquivoRemessaLayout { get; set; }
        public int IdPessoa { get; set; }
        public bool? InAtivo { get; set; }

        public virtual ArquivoRemessaLayout IdArquivoRemessaLayoutNavigation { get; set; }
        public virtual Pessoa IdPessoaNavigation { get; set; }
    }
}