// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ArquivoContabilHistoricoPadrao
    {
        public ArquivoContabilHistoricoPadrao()
        {
            ArquivoContabilItem = new HashSet<ArquivoContabilItem>();
            ContaPagar = new HashSet<ContaPagar>();
        }

        public int IdArquivoContabilHistoricoPadrao { get; set; }
        public string CdHistorico { get; set; }
        public string TxHistorico { get; set; }
        public DateTime DtCadastro { get; set; }

        public virtual ICollection<ArquivoContabilItem> ArquivoContabilItem { get; set; }
        public virtual ICollection<ContaPagar> ContaPagar { get; set; }
    }
}