// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AtendeSadt
    {
        public int IdAtende { get; set; }
        public int IdUnidadeOrganizacional { get; set; }
        public int? IdRecurso { get; set; }
        public int? IdPessoa { get; set; }
        public int IdTipoDiaSemana { get; set; }
        public int NrDuracao { get; set; }
        public DateTime HrHoraInicio { get; set; }
        public DateTime HrHoraFim { get; set; }
        public DateTime? DtInicioVigencia { get; set; }
        public DateTime? DtFimVigencia { get; set; }
        public int? IdEspecialidade { get; set; }
        public int? IdUnidadeFisica { get; set; }
        public bool? InPresencial { get; set; }
        public bool? InOnline { get; set; }
        public bool? InTelemedicina { get; set; }
        public bool? InPrimeiraConsulta { get; set; }
        public bool? InEhPaciente { get; set; }
        public bool? InRetorno { get; set; }
        public string LocalAtende { get; set; }

        public virtual TipoDiversos IdEspecialidadeNavigation { get; set; }
        public virtual Pessoa IdPessoaNavigation { get; set; }
        public virtual Recurso IdRecursoNavigation { get; set; }
        public virtual TipoDiversos IdTipoDiaSemanaNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeFisicaNavigation { get; set; }
    }
}