// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AtendimentoDrg
    {
        public int IdAtendimento { get; set; }
        public int? CdDrg { get; set; }
        public string TxDescricaoDrg { get; set; }
        public string TxPermanenciaPrevista { get; set; }
        public DateTime? DtAltaPrevista { get; set; }

        public virtual Atendimento IdAtendimentoNavigation { get; set; }
    }
}