// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AtendimentoProcedimento
    {
        public AtendimentoProcedimento()
        {
            MedicoProcedimento = new HashSet<MedicoProcedimento>();
        }

        public int IdAtendimento { get; set; }
        public int IdProcedimento { get; set; }
        public string NrAutorizacao { get; set; }
        public DateTime? DtAutorizacao { get; set; }
        public int? IdCid { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public int? IdSituacaoProcedimento { get; set; }
        public int? QnProcedimentoAutorizado { get; set; }
        public int? QnProcedimentoSolicitado { get; set; }
        public int? InParticular { get; set; }

        public virtual Atendimento IdAtendimentoNavigation { get; set; }
        public virtual Servico IdProcedimentoNavigation { get; set; }
        public virtual TipoDiversos IdSituacaoProcedimentoNavigation { get; set; }
        public virtual ICollection<MedicoProcedimento> MedicoProcedimento { get; set; }
    }
}