// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AtendimentoCancelado
    {
        public int IdAtendimentoCancelado { get; set; }
        public int IdAtendimento { get; set; }
        public int IdJustificativaCancelamentoPadrao { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtCancelamento { get; set; }
        public string TxComplementoJustificativa { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual Atendimento IdAtendimentoNavigation { get; set; }
        public virtual TipoDiversos IdJustificativaCancelamentoPadraoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}