// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AtendimentoComplemento
    {
        public int IdAtendimento { get; set; }
        public int? IdTipoCaraterSolicitacao { get; set; }
        public int? IdTipoAtendimentoSolicitacao { get; set; }
        public int? IdPessoaResponsavel { get; set; }
        public int? IdTipoParentescoResponsavel { get; set; }
        public string TxDescObsResponsavel { get; set; }
        public int? IdPessoaContato1 { get; set; }
        public int? IdTipoParentescoContato1 { get; set; }
        public int? IdPessoaContato2 { get; set; }
        public int? IdTipoParentescoContato2 { get; set; }
        public int? IdPessoaContato3 { get; set; }
        public int? IdTipoParentescoContato3 { get; set; }
        public int? IdTipoDoenca { get; set; }
        public int? IdUnidadeTempoDoenca { get; set; }
        public int? IdIndicacaoDeAciende { get; set; }
        public int? IdEspecialidadeMedicoPrincipal { get; set; }
        public int? QdTempo { get; set; }
        public string NrCodseguranca { get; set; }
        public bool? InRetornoAmbulatorio { get; set; }
        public string NrSenhaCdPainelEletronico { get; set; }
        public int? NrAlmocoJantar { get; set; }
        public int? NrLanche { get; set; }
        public bool? InTv { get; set; }
        public bool? InGeladeira { get; set; }
        public bool? InTelefone { get; set; }
        public bool? InDifAcomodacao { get; set; }
        public bool? InAlmocoJantarCob { get; set; }
        public bool? InLancheCob { get; set; }
        public int? IdAtendimentopa { get; set; }
        public int? IdOperadoraContratada { get; set; }
        public int? IdOperadoraAutorizada { get; set; }
        public string TxObsOcupacao { get; set; }
        public string TxObservacaoAdicional { get; set; }
        public string TxObservacaoContato { get; set; }
        public int? LocNu { get; set; }
        public string TxObsTv { get; set; }
        public string TxObsGeladeira { get; set; }
        public string TxObsTelefone { get; set; }
        public string TxObsDifAcomodacao { get; set; }
        public string TxObsRefeicaoAcomp { get; set; }
        public string TxObsLancheAcomp { get; set; }
        public string NmPessoaContato1 { get; set; }
        public string NmPessoaContato2 { get; set; }
        public string NmPessoaContato3 { get; set; }
        public string TxReligiaoPaciente { get; set; }
        public int? IdUnidadeFisica { get; set; }
        public string TxObsVisitante { get; set; }
        public bool? InEntregaTerceiro { get; set; }
        public string TxPessoaAutorizada { get; set; }
        public string TxDocumentoAutorizada { get; set; }
        public bool? InAcidenteTrabalho { get; set; }
        public DateTime? DtEntregaResultado { get; set; }
        public int? IdClassificacaoSenha { get; set; }
        /// <summary>
        /// tipo tabela 418
        /// </summary>
        public int? IdHospitalOrigem { get; set; }
        public int? IdSetorAtendimento { get; set; }
        public bool? InPosoperatorio { get; set; }
        public string TxIndicacaoClinica { get; set; }
        public bool? InCirurgiaRealizadaHmt { get; set; }

        public virtual Atendimento IdAtendimentoNavigation { get; set; }
        public virtual ClassificacaoSenha IdClassificacaoSenhaNavigation { get; set; }
        public virtual TipoDiversos IdHospitalOrigemNavigation { get; set; }
        public virtual TipoDiversos IdSetorAtendimentoNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeFisicaNavigation { get; set; }
        public virtual LogLocalidade LocNuNavigation { get; set; }
    }
}