// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class AtendimentoMedicoCancelado
    {
        public int IdAtendimentoMedicoCancelado { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtCancelamento { get; set; }
        public int IdJustificativaCancelamentoPadrao { get; set; }
        public string TxComplementoJustificativa { get; set; }
        public int IdMedico { get; set; }
        public int IdAtendimento { get; set; }
        public DateTime DtAtendimento { get; set; }
        public int? IdEspecialidade { get; set; }
        public int? IdMotivoAtendimento { get; set; }
        public int? IdTipoAtendimento { get; set; }
        public int? IdDocumentoLote { get; set; }
        public string NrGuia { get; set; }
        public string NrSenha { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual Atendimento IdAtendimentoNavigation { get; set; }
        public virtual TipoDiversos IdEspecialidadeNavigation { get; set; }
        public virtual Pessoa IdMedicoNavigation { get; set; }
        public virtual TipoDiversos IdMotivoAtendimentoNavigation { get; set; }
        public virtual TipoDiversos IdTipoAtendimentoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}