// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Atributo
    {
        public Atributo()
        {
            AtributoDependenteIdAtributoDependenteNavigation = new HashSet<AtributoDependente>();
            AtributoDependenteIdAtributoNavigation = new HashSet<AtributoDependente>();
            AtributoTipoDiversosTipoTabela = new HashSet<AtributoTipoDiversosTipoTabela>();
            ClassificacaoProdutoAtributo = new HashSet<ClassificacaoProdutoAtributo>();
            CorreioEletronicoAplicativo = new HashSet<CorreioEletronicoAplicativo>();
            OrdemServicoCaracteristica = new HashSet<OrdemServicoCaracteristica>();
            PessoaCaracteristicaHistorico = new HashSet<PessoaCaracteristicaHistorico>();
            PessoaEntidadePessoaAtributo = new HashSet<PessoaEntidadePessoaAtributo>();
            ProdutoDetalheAtributo = new HashSet<ProdutoDetalheAtributo>();
            RegistroEletronicoItemModeloAtributo = new HashSet<RegistroEletronicoItemModeloAtributo>();
            RegistroEletronicoItemModeloAtributoHistorico = new HashSet<RegistroEletronicoItemModeloAtributoHistorico>();
            RegraAtributoAssociacao = new HashSet<RegraAtributoAssociacao>();
            RestricaoKit = new HashSet<RestricaoKit>();
            RestricaoProdutoDetalhe = new HashSet<RestricaoProdutoDetalhe>();
            RestricaoServico = new HashSet<RestricaoServico>();
            ServicoExcecaoPlanoServicoIncidencia = new HashSet<ServicoExcecaoPlanoServicoIncidencia>();
            ServicoExcecaoServicoIncidencia = new HashSet<ServicoExcecaoServicoIncidencia>();
            ServicoIncidenciaCategoria = new HashSet<ServicoIncidenciaCategoria>();
            ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativaHistoricoIdAtributoPrecoBrasindiceNavigation = new HashSet<ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativaHistorico>();
            ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativaHistoricoIdAtributoPrecoBrasindiceRestritoHospNavigation = new HashSet<ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativaHistorico>();
            ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativaIdAtributoPrecoBrasindiceNavigation = new HashSet<ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativa>();
            ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativaIdAtributoPrecoBrasindiceRestritoHospNavigation = new HashSet<ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativa>();
            ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupoHistoricoIdAtributoPrecoBrasindiceNavigation = new HashSet<ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupoHistorico>();
            ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupoHistoricoIdAtributoPrecoBrasindiceRestritoHospNavigation = new HashSet<ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupoHistorico>();
            ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupoIdAtributoPrecoBrasindiceNavigation = new HashSet<ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupo>();
            ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupoIdAtributoPrecoBrasindiceRestritoHospNavigation = new HashSet<ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupo>();
            ServicoProdutoTabelaOperadoraClassificacaoProdutoIdAtributoPrecoBrasindiceNavigation = new HashSet<ServicoProdutoTabelaOperadoraClassificacaoProduto>();
            ServicoProdutoTabelaOperadoraClassificacaoProdutoIdAtributoPrecoBrasindiceRestritoHospNavigation = new HashSet<ServicoProdutoTabelaOperadoraClassificacaoProduto>();
            ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativaHistoricoIdAtributoPrecoBrasindiceNavigation = new HashSet<ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativaHistorico>();
            ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativaHistoricoIdAtributoPrecoBrasindiceRestritoHospNavigation = new HashSet<ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativaHistorico>();
            ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativaIdAtributoPrecoBrasindiceNavigation = new HashSet<ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativa>();
            ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativaIdAtributoPrecoBrasindiceRestritoHospNavigation = new HashSet<ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativa>();
            ServicoProdutoTabelaPlanoClassificacaoProdutoGrupoHistoricoIdAtributoPrecoBrasindiceNavigation = new HashSet<ServicoProdutoTabelaPlanoClassificacaoProdutoGrupoHistorico>();
            ServicoProdutoTabelaPlanoClassificacaoProdutoGrupoHistoricoIdAtributoPrecoBrasindiceRestritoHospNavigation = new HashSet<ServicoProdutoTabelaPlanoClassificacaoProdutoGrupoHistorico>();
            ServicoProdutoTabelaPlanoClassificacaoProdutoGrupoIdAtributoPrecoBrasindiceNavigation = new HashSet<ServicoProdutoTabelaPlanoClassificacaoProdutoGrupo>();
            ServicoProdutoTabelaPlanoClassificacaoProdutoGrupoIdAtributoPrecoBrasindiceRestritoHospNavigation = new HashSet<ServicoProdutoTabelaPlanoClassificacaoProdutoGrupo>();
            ServicoProdutoTabelaPlanoClassificacaoProdutoIdAtributoPrecoBrasindiceNavigation = new HashSet<ServicoProdutoTabelaPlanoClassificacaoProduto>();
            ServicoProdutoTabelaPlanoClassificacaoProdutoIdAtributoPrecoBrasindiceRestritoHospNavigation = new HashSet<ServicoProdutoTabelaPlanoClassificacaoProduto>();
            ServicoServicoProdutoTabelaServicoIncidencia = new HashSet<ServicoServicoProdutoTabelaServicoIncidencia>();
            TipoDiversosCaracteristica = new HashSet<TipoDiversosCaracteristica>();
        }

        public int IdAtributo { get; set; }
        public string NmAtributo { get; set; }
        public int IdAtributoTipo { get; set; }
        public int NrTamanho { get; set; }
        public string TxRotulo { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public int? IdTipoTabela { get; set; }
        public string TxValorMaximo { get; set; }
        public string TxValorMinimo { get; set; }
        public int? IdUnidadeMedida { get; set; }
        public string TxTabela { get; set; }
        public string NmAtributoApresentacao { get; set; }
        public string NmAtributoGravacao { get; set; }
        public string TxCodHl7 { get; set; }

        public virtual TipoDiversos IdAtributoTipoNavigation { get; set; }
        public virtual TipoTabela IdTipoTabelaNavigation { get; set; }
        public virtual TipoDiversos IdUnidadeMedidaNavigation { get; set; }
        public virtual AtributoFaixaValorPessoa AtributoFaixaValorPessoa { get; set; }
        public virtual ICollection<AtributoDependente> AtributoDependenteIdAtributoDependenteNavigation { get; set; }
        public virtual ICollection<AtributoDependente> AtributoDependenteIdAtributoNavigation { get; set; }
        public virtual ICollection<AtributoTipoDiversosTipoTabela> AtributoTipoDiversosTipoTabela { get; set; }
        public virtual ICollection<ClassificacaoProdutoAtributo> ClassificacaoProdutoAtributo { get; set; }
        public virtual ICollection<CorreioEletronicoAplicativo> CorreioEletronicoAplicativo { get; set; }
        public virtual ICollection<OrdemServicoCaracteristica> OrdemServicoCaracteristica { get; set; }
        public virtual ICollection<PessoaCaracteristicaHistorico> PessoaCaracteristicaHistorico { get; set; }
        public virtual ICollection<PessoaEntidadePessoaAtributo> PessoaEntidadePessoaAtributo { get; set; }
        public virtual ICollection<ProdutoDetalheAtributo> ProdutoDetalheAtributo { get; set; }
        public virtual ICollection<RegistroEletronicoItemModeloAtributo> RegistroEletronicoItemModeloAtributo { get; set; }
        public virtual ICollection<RegistroEletronicoItemModeloAtributoHistorico> RegistroEletronicoItemModeloAtributoHistorico { get; set; }
        public virtual ICollection<RegraAtributoAssociacao> RegraAtributoAssociacao { get; set; }
        public virtual ICollection<RestricaoKit> RestricaoKit { get; set; }
        public virtual ICollection<RestricaoProdutoDetalhe> RestricaoProdutoDetalhe { get; set; }
        public virtual ICollection<RestricaoServico> RestricaoServico { get; set; }
        public virtual ICollection<ServicoExcecaoPlanoServicoIncidencia> ServicoExcecaoPlanoServicoIncidencia { get; set; }
        public virtual ICollection<ServicoExcecaoServicoIncidencia> ServicoExcecaoServicoIncidencia { get; set; }
        public virtual ICollection<ServicoIncidenciaCategoria> ServicoIncidenciaCategoria { get; set; }
        public virtual ICollection<ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativaHistorico> ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativaHistoricoIdAtributoPrecoBrasindiceNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativaHistorico> ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativaHistoricoIdAtributoPrecoBrasindiceRestritoHospNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativa> ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativaIdAtributoPrecoBrasindiceNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativa> ServicoProdutoTabelaOperadoraClassificacaoProdutoAlternativaIdAtributoPrecoBrasindiceRestritoHospNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupoHistorico> ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupoHistoricoIdAtributoPrecoBrasindiceNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupoHistorico> ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupoHistoricoIdAtributoPrecoBrasindiceRestritoHospNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupo> ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupoIdAtributoPrecoBrasindiceNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupo> ServicoProdutoTabelaOperadoraClassificacaoProdutoGrupoIdAtributoPrecoBrasindiceRestritoHospNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaOperadoraClassificacaoProduto> ServicoProdutoTabelaOperadoraClassificacaoProdutoIdAtributoPrecoBrasindiceNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaOperadoraClassificacaoProduto> ServicoProdutoTabelaOperadoraClassificacaoProdutoIdAtributoPrecoBrasindiceRestritoHospNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativaHistorico> ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativaHistoricoIdAtributoPrecoBrasindiceNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativaHistorico> ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativaHistoricoIdAtributoPrecoBrasindiceRestritoHospNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativa> ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativaIdAtributoPrecoBrasindiceNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativa> ServicoProdutoTabelaPlanoClassificacaoProdutoAlternativaIdAtributoPrecoBrasindiceRestritoHospNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaPlanoClassificacaoProdutoGrupoHistorico> ServicoProdutoTabelaPlanoClassificacaoProdutoGrupoHistoricoIdAtributoPrecoBrasindiceNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaPlanoClassificacaoProdutoGrupoHistorico> ServicoProdutoTabelaPlanoClassificacaoProdutoGrupoHistoricoIdAtributoPrecoBrasindiceRestritoHospNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaPlanoClassificacaoProdutoGrupo> ServicoProdutoTabelaPlanoClassificacaoProdutoGrupoIdAtributoPrecoBrasindiceNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaPlanoClassificacaoProdutoGrupo> ServicoProdutoTabelaPlanoClassificacaoProdutoGrupoIdAtributoPrecoBrasindiceRestritoHospNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaPlanoClassificacaoProduto> ServicoProdutoTabelaPlanoClassificacaoProdutoIdAtributoPrecoBrasindiceNavigation { get; set; }
        public virtual ICollection<ServicoProdutoTabelaPlanoClassificacaoProduto> ServicoProdutoTabelaPlanoClassificacaoProdutoIdAtributoPrecoBrasindiceRestritoHospNavigation { get; set; }
        public virtual ICollection<ServicoServicoProdutoTabelaServicoIncidencia> ServicoServicoProdutoTabelaServicoIncidencia { get; set; }
        public virtual ICollection<TipoDiversosCaracteristica> TipoDiversosCaracteristica { get; set; }
    }
}