// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class BoletoCobranca
    {
        public int IdBoleto { get; set; }
        public int IdConta { get; set; }
        public int IdBanco { get; set; }
        public string TxSacado { get; set; }
        public string TxCpf { get; set; }
        public double VlBoleto { get; set; }
        public DateTime DtVencimento { get; set; }
        public DateTime DtDocumento { get; set; }
        public string TxNrDocumento { get; set; }
        public string TxCdBarra { get; set; }
        public bool InConciliado { get; set; }
        public double? VlPago { get; set; }
        public double? Juros { get; set; }
        public DateTime? DtConciliacao { get; set; }

        public virtual Pessoa IdBancoNavigation { get; set; }
    }
}