// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class BorderoLog
    {
        public int IdBorderoLog { get; set; }
        public int IdBordero { get; set; }
        public int? IdContaBancaria { get; set; }
        public int? IdFormaPagamento { get; set; }
        public string NrDocumento { get; set; }
        public string TxHistorico { get; set; }
        public DateTime? DtPagamento { get; set; }
        public int? IdFavorecido { get; set; }
        public DateTime DtCadastro { get; set; }
        public decimal? VlBordero { get; set; }
        public int IdUsuarioCadastro { get; set; }
        public DateTime? DtAlteracao { get; set; }
        public int? IdUsuarioAlteracao { get; set; }
        public bool InCompensado { get; set; }
        public bool InCancelado { get; set; }
        public bool InAtivo { get; set; }
        public string TxIdentificacao { get; set; }
        public bool InAguardandoAutorizacao { get; set; }
        public DateTime? DtAutorizacao { get; set; }
        public bool InAvaliacaoIniciada { get; set; }
        public int? IdUsuarioAutorizacao { get; set; }
        public DateTime? DtAtualizacao { get; set; }
        public DateTime? DtExclusao { get; set; }
        public int? IdUsuarioOperacao { get; set; }
        public bool InSubstituirMeioDePagto { get; set; }
        public bool InAutorizadoParaCaixa { get; set; }
        public DateTime? DtPrevisaoPagamento { get; set; }

        public virtual Usuario IdUsuarioOperacaoNavigation { get; set; }
    }
}