// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class BrasMatHmt
    {
        public string CdFabricante { get; set; }
        public string NmFabricante { get; set; }
        public string CdProduto { get; set; }
        public string NmProduto { get; set; }
        public string CdApresentacao { get; set; }
        public string NmApresentacao { get; set; }
        public decimal? VlProduto { get; set; }
        public int? QnFracionamento { get; set; }
        public string CdPrecoTipo { get; set; }
        public double? VlProdutoFracionado { get; set; }
        public string NrEdicaoAlteracao { get; set; }
        public string PrIpi { get; set; }
        public string InProdutoLista { get; set; }
        public int? CdBarras { get; set; }
        public int? CdTiss { get; set; }
        public DateTime DtAtualizacao { get; set; }
        public string CdTuss { get; set; }
    }
}