// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Caixa
    {
        public Caixa()
        {
            CaixaMovimento = new HashSet<CaixaMovimento>();
            CaixaUsuario = new HashSet<CaixaUsuario>();
        }

        public int IdCaixa { get; set; }
        public int IdContaBancaria { get; set; }
        public string NmCaixa { get; set; }
        public string TxDescricao { get; set; }
        public bool? InAtivo { get; set; }
        public bool InAberto { get; set; }
        public int IdUsuarioAlteracao { get; set; }
        public DateTime DtAlteracao { get; set; }

        public virtual ContaBancaria IdContaBancariaNavigation { get; set; }
        public virtual Usuario IdUsuarioAlteracaoNavigation { get; set; }
        public virtual ICollection<CaixaMovimento> CaixaMovimento { get; set; }
        public virtual ICollection<CaixaUsuario> CaixaUsuario { get; set; }
    }
}