// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class CarenciaHistorico
    {
        public int IdCarencia { get; set; }
        public DateTime DtVigencia { get; set; }
        public int NrPeriodo { get; set; }
        public int IdUnidadeTempo { get; set; }
        public bool? InAtual { get; set; }
        public int? IdUsuario { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual Carencia IdCarenciaNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}