// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class CartaRecursoMovimentacaoContaParcela
    {
        public int IdCartarecursoMovimentacaocontaparcela { get; set; }
        public int IdCartarecurso { get; set; }
        public int IdLote { get; set; }
        public int IdMovimentacaocontaparcela { get; set; }
        public decimal VlRecursado { get; set; }
        public DateTime DtInsercao { get; set; }
        public int IdUsuario { get; set; }
    }
}