// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class CartaRecursoParcelaContaReceber
    {
        public int IdCartarecursoParcelacontareceber { get; set; }
        public int IdCartarecurso { get; set; }
        public int IdLote { get; set; }
        public int IdContaReceber { get; set; }
        public int NrParcela { get; set; }
        public decimal VlRecursado { get; set; }
        public DateTime DtInsercao { get; set; }
        public int IdUsuario { get; set; }
        public int IdFaturamentobaixagrupo { get; set; }
        public bool? InAtivo { get; set; }

        public virtual CartaRecurso IdCartarecursoNavigation { get; set; }
        public virtual FaturamentoBaixaGrupo IdFaturamentobaixagrupoNavigation { get; set; }
        public virtual LoteConta IdLoteNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ParcelaContaReceber ParcelaContaReceber { get; set; }
    }
}