// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class CartaRecursoRecursoReenvio
    {
        public int IdFechamentoItem { get; set; }
        public int IdConta { get; set; }
        public int IdCartarecursoReenvio { get; set; }
        public int? IdUsuario { get; set; }
    }
}