// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ChequeCliente
    {
        public ChequeCliente()
        {
            ChequeClienteEvento = new HashSet<ChequeClienteEvento>();
        }

        public int IdChequeCliente { get; set; }
        public bool? InAtivo { get; set; }

        public virtual ICollection<ChequeClienteEvento> ChequeClienteEvento { get; set; }
    }
}