// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ClassificacaoSenhaHistorico
    {
        public int IdClassificacaoSenhaHistorico { get; set; }
        public int IdClassificacaoSenha { get; set; }
        public string TxObservacao { get; set; }
        public int IdStatusSenha { get; set; }
        public int? IdUsuario { get; set; }
        public DateTime DtHistorico { get; set; }

        public virtual ClassificacaoSenha IdClassificacaoSenhaNavigation { get; set; }
        public virtual TipoDiversos IdStatusSenhaNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}