// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ClassificacaoPeso
    {
        public ClassificacaoPeso()
        {
            ClassificacaoFluxo = new HashSet<ClassificacaoFluxo>();
            ClassificacaoSenha = new HashSet<ClassificacaoSenha>();
        }

        public int IdClassificacaoPeso { get; set; }
        public int IdUnidadeOrganizacional { get; set; }
        public string NmClassificacao { get; set; }
        public int NrPeso { get; set; }
        public string TxCor { get; set; }
        public bool? InAtivo { get; set; }
        public string TxSigla { get; set; }
        public int? NrTempoMedioAtendimento { get; set; }

        public virtual UnidadeOrganizacional IdUnidadeOrganizacionalNavigation { get; set; }
        public virtual ICollection<ClassificacaoFluxo> ClassificacaoFluxo { get; set; }
        public virtual ICollection<ClassificacaoSenha> ClassificacaoSenha { get; set; }
    }
}