// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ClassificacaoContabil
    {
        public ClassificacaoContabil()
        {
            ClassificacaoProduto = new HashSet<ClassificacaoProduto>();
            EstoqueFechamentoMensal = new HashSet<EstoqueFechamentoMensal>();
            EstoqueFechamentoMensalConsignado = new HashSet<EstoqueFechamentoMensalConsignado>();
            ProdutoClassificacaoContabilPlanoContaContabil = new HashSet<ProdutoClassificacaoContabilPlanoContaContabil>();
        }

        /// <summary>
        /// PK da Tabela. Identificador único.
        /// </summary>
        public int IdClassificacaoContabil { get; set; }
        /// <summary>
        /// Descrição da Classificação.
        /// 
        /// </summary>
        public string NmClassificacaoContabil { get; set; }
        /// <summary>
        /// Codigo contabil que representa a Classificação.
        /// </summary>
        public int CdClassificacaoContabil { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public int? IdTipoClassificacaoCusto { get; set; }
        public bool InConvenioFaturamento { get; set; }

        public virtual TipoDiversos IdTipoClassificacaoCustoNavigation { get; set; }
        public virtual ICollection<ClassificacaoProduto> ClassificacaoProduto { get; set; }
        public virtual ICollection<EstoqueFechamentoMensal> EstoqueFechamentoMensal { get; set; }
        public virtual ICollection<EstoqueFechamentoMensalConsignado> EstoqueFechamentoMensalConsignado { get; set; }
        public virtual ICollection<ProdutoClassificacaoContabilPlanoContaContabil> ProdutoClassificacaoContabilPlanoContaContabil { get; set; }
    }
}