// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class CobrancaTipoEnfermagem
    {
        public CobrancaTipoEnfermagem()
        {
            DispensacaoEnfermagem = new HashSet<DispensacaoEnfermagem>();
            ServicoCheckinEnfermagem = new HashSet<ServicoCheckinEnfermagem>();
        }

        public int IdCobrancaTipoEnfermagem { get; set; }
        public string TxDescricaoCobranca { get; set; }

        public virtual ICollection<DispensacaoEnfermagem> DispensacaoEnfermagem { get; set; }
        public virtual ICollection<ServicoCheckinEnfermagem> ServicoCheckinEnfermagem { get; set; }
    }
}