// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ComposicaoItem
    {
        public ComposicaoItem()
        {
            ComposicaoItemProduto = new HashSet<ComposicaoItemProduto>();
            ComposicaoItemProdutoExcecao = new HashSet<ComposicaoItemProdutoExcecao>();
            ComposicaoItemServico = new HashSet<ComposicaoItemServico>();
            ComposicaoItemServicoExcecao = new HashSet<ComposicaoItemServicoExcecao>();
        }

        public int IdComposicaoItem { get; set; }
        public int IdOperadora { get; set; }
        public int IdServico { get; set; }
        public int? IdPlano { get; set; }
        public bool InAtivo { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public bool InTodosProcedimentos { get; set; }
        public bool InTodosTaxadiarias { get; set; }
        public bool InTodosMateriais { get; set; }
        public bool InTodosMedicamentos { get; set; }
        public bool InTodosOpme { get; set; }

        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual Plano IdPlanoNavigation { get; set; }
        public virtual Servico IdServicoNavigation { get; set; }
        public virtual ICollection<ComposicaoItemProduto> ComposicaoItemProduto { get; set; }
        public virtual ICollection<ComposicaoItemProdutoExcecao> ComposicaoItemProdutoExcecao { get; set; }
        public virtual ICollection<ComposicaoItemServico> ComposicaoItemServico { get; set; }
        public virtual ICollection<ComposicaoItemServicoExcecao> ComposicaoItemServicoExcecao { get; set; }
    }
}