// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ConfiguracaoMaquina
    {
        public int IdConfiguracaoMaquina { get; set; }
        public string TxNomeMaquina { get; set; }
        public string TxPorta1 { get; set; }
        public string TxPorta2 { get; set; }
        public string TxPorta3 { get; set; }
        public string TxPorta4 { get; set; }
        public string TxPorta5 { get; set; }
        public string TxPorta6 { get; set; }
        public string TxPorta7 { get; set; }
        public string TxPorta8 { get; set; }
        public string TxPorta9 { get; set; }
        public string TxPorta10 { get; set; }
        public string TxIpMaquinaCliente { get; set; }
        public string TxMacAddressMaquina { get; set; }
        public string TxPorta11 { get; set; }
        public string TxPorta12 { get; set; }
        public string TxPorta13 { get; set; }
    }
}