// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ConsignadoPendenteNotaHistorico
    {
        public int IdConsignadoPendenteNota { get; set; }
        public int IdStatusConsignadoPendenteNota { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtAlteracao { get; set; }

        public virtual ConsignadoPendenteNota IdConsignadoPendenteNotaNavigation { get; set; }
        public virtual TipoDiversos IdStatusConsignadoPendenteNotaNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}