// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContaSelNota
    {
        public int IdConta { get; set; }
        public int? IdLote { get; set; }
        public DateTime DtSelecao { get; set; }
        public int IdUsuario { get; set; }
        public int? IdNota2 { get; set; }
        public int? IdNota3 { get; set; }

        public virtual LoteConta IdLoteNavigation { get; set; }
        public virtual NotaEmitida IdNota2Navigation { get; set; }
        public virtual NotaEmitida IdNota3Navigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}