// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContaItemServicoTaxaFolhadeSala
    {
        public int IdContaItemServico { get; set; }
        public int IdTaxaFolhaDeSala { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual ContaItemServico IdContaItemServicoNavigation { get; set; }
        public virtual TaxaFolhaDeSala IdTaxaFolhaDeSalaNavigation { get; set; }
    }
}