// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContaComplemento
    {
        public int IdConta { get; set; }
        public int IdAtendimento { get; set; }
        public int? IdLiberaCriticaSus { get; set; }
        public string NrAutorizacao { get; set; }
        public int? IdMotivoSaida { get; set; }
        public int? IdCidSecundario { get; set; }
        public int? IdCidComplementar { get; set; }
        public int? IdTipoApac { get; set; }
        public int? IdTipoContaSus { get; set; }
        public bool InPendenteConfirmacaoVinculoOpmesSus { get; set; }
        public int? IdUsuarioConfirmacaoVinculoOpmesSus { get; set; }
        public DateTime? DtConfirmacaoVinculoOpmesSus { get; set; }
        public int? IdEspecialidadeLeito { get; set; }
        public DateTime? DtAltaObito { get; set; }
        public string NrAihAnterior { get; set; }
        public string NrAihPosterior { get; set; }
        public double? VlDescontoConta { get; set; }

        public virtual Atendimento IdAtendimentoNavigation { get; set; }
        public virtual Cid IdCidComplementarNavigation { get; set; }
        public virtual Cid IdCidSecundarioNavigation { get; set; }
        public virtual Conta IdContaNavigation { get; set; }
        public virtual TipoDiversos IdEspecialidadeLeitoNavigation { get; set; }
        public virtual TipoDiversos IdLiberaCriticaSusNavigation { get; set; }
        public virtual TipoAltaSus IdMotivoSaidaNavigation { get; set; }
        public virtual TipoDiversos IdTipoContaSusNavigation { get; set; }
        public virtual Usuario IdUsuarioConfirmacaoVinculoOpmesSusNavigation { get; set; }
    }
}