// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContatoDependente
    {
        public int IdDependente { get; set; }
        public string NmDependente { get; set; }
        public int IdParentesco { get; set; }
        public DateTime DtNascimento { get; set; }
        public DateTime? DtCasamento { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public int? IdContato { get; set; }

        public virtual TipoDiversos IdParentescoNavigation { get; set; }
    }
}