// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContaConciliacao
    {
        public int? IdLote { get; set; }
        public int IdConta { get; set; }
        public bool? InRejeitada { get; set; }
        public int IdOperadora { get; set; }
        public string NmOperadora { get; set; }
        public int? NrNotaFiscal { get; set; }
        public int IdAtendimento { get; set; }
        public string NmPaciente { get; set; }
        public DateTime? DtAtendimento { get; set; }
        public string TxDescricaoSituacao { get; set; }
        public int IdSituacao { get; set; }
        public double? VlFaturado { get; set; }
        public int VlPago { get; set; }
        public string NrGuia { get; set; }
        public string NrAutorizacao { get; set; }
        public int IdLoteContaMapa { get; set; }
    }
}