// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContasPendentes
    {
        public string Operadora { get; set; }
        public string DataEnvio { get; set; }
        public string DtVencimento { get; set; }
        public double? Conta { get; set; }
        public string Situação { get; set; }
        public double? Lote { get; set; }
        public string Paciente { get; set; }
        public string Cartão { get; set; }
        public string Matricula { get; set; }
        public string DtAtendimento { get; set; }
        public double? Valor { get; set; }
    }
}