// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContaTotaisReversaoSemRecurso
    {
        public int IdConta { get; set; }
        public double VlRevertidoSemRecurso { get; set; }
    }
}