// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContaReceberLog
    {
        public int IdContaReceberLog { get; set; }
        public int IdContaReceber { get; set; }
        public int IdTipoConta { get; set; }
        public int? IdLote { get; set; }
        public int? IdConta { get; set; }
        public int IdCondicaoPagamento { get; set; }
        public int IdTipoSituacao { get; set; }
        public int IdPessoa { get; set; }
        public int? IdResponsavel { get; set; }
        public int IdTipoDocumento { get; set; }
        public int? NrDocumento { get; set; }
        public string TxSerieDocumento { get; set; }
        public DateTime? DtEmissaoDocumento { get; set; }
        public bool InPrevisao { get; set; }
        public bool InAtivo { get; set; }
        public bool InInconsistente { get; set; }
        public bool InCancelada { get; set; }
        public decimal VlContaReceber { get; set; }
        public decimal? VlDesconto { get; set; }
        public decimal? VlAcrescimos { get; set; }
        public decimal? VlImpostos { get; set; }
        public decimal? VlTotalReceber { get; set; }
        public string TxHistorico { get; set; }
        public string TxObservacoes { get; set; }
        public DateTime DtCadastro { get; set; }
        public int IdUsuario { get; set; }
        public DateTime? DtBaixa { get; set; }
        public string NrContaContabil { get; set; }
        public int? IdContaReceita { get; set; }
        public int? IdContaCorrente { get; set; }
        public int? IdOperadorarecebimentoparcelasemconciliacao { get; set; }
        public DateTime? DtAtualizacao { get; set; }
        public DateTime? DtExclusao { get; set; }
        public int? IdUsuarioOperacao { get; set; }
        public int? IdFaturafinanceira { get; set; }
        public bool? InRecebimentoAutorizado { get; set; }
        public int? IdNotaDevolucao { get; set; }
        public int? IdBaixaAdiantamentoPago { get; set; }

        public virtual Usuario IdUsuarioOperacaoNavigation { get; set; }
    }
}