// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContaItemServicoMedicoExecutante
    {
        public int IdContaItemServico { get; set; }
        public int IdMedico { get; set; }
        public int? IdFuncao { get; set; }
        public int? IdEspecialidadeTipo { get; set; }
        public int? IdCboTipo { get; set; }
        public int? IdApurarValoresSus { get; set; }
        public int IdContaItemServicoMedicoExecutante { get; set; }
        public double? PrRepasse { get; set; }
        public bool InRepasseRealizado { get; set; }

        public virtual TipoDiversos IdApurarValoresSusNavigation { get; set; }
        public virtual TipoDiversos IdCboTipoNavigation { get; set; }
        public virtual ContaItemServico IdContaItemServicoNavigation { get; set; }
        public virtual Pessoa IdMedicoNavigation { get; set; }
    }
}