// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContaBancaria
    {
        public ContaBancaria()
        {
            Bordero = new HashSet<Bordero>();
            Caixa = new HashSet<Caixa>();
            Cheque = new HashSet<Cheque>();
            ChequeEvento = new HashSet<ChequeEvento>();
            ChequeParametrosImpressao = new HashSet<ChequeParametrosImpressao>();
            ContaBancariaPerfil = new HashSet<ContaBancariaPerfil>();
            ContaCorrente = new HashSet<ContaCorrente>();
            DefaultContabil = new HashSet<DefaultContabil>();
            LancamentoBancario = new HashSet<LancamentoBancario>();
            NotaEmitidaFormaPagamento = new HashSet<NotaEmitidaFormaPagamento>();
            TransferenciaFisicaIdContaDestinoNavigation = new HashSet<TransferenciaFisica>();
            TransferenciaFisicaIdContaOrigemNavigation = new HashSet<TransferenciaFisica>();
        }

        public int IdContaBancaria { get; set; }
        public int IdContaTipo { get; set; }
        public int IdAgencia { get; set; }
        public int NrConta { get; set; }
        public string NrDigito { get; set; }
        public DateTime? DtAbertura { get; set; }
        public double VlSaldoAtual { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public bool InEncerrada { get; set; }
        public string TxDescricao { get; set; }
        public int? IdUsuario { get; set; }
        public DateTime? DtMinParaLancamento { get; set; }
        public DateTime? DtSaldoConferido { get; set; }
        public decimal? VlSaldoCompensado { get; set; }
        public decimal? VlDbNaoCompensado { get; set; }
        public decimal? VlCrNaoCompensado { get; set; }

        public virtual Agencia IdAgenciaNavigation { get; set; }
        public virtual TipoDiversos IdContaTipoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<Bordero> Bordero { get; set; }
        public virtual ICollection<Caixa> Caixa { get; set; }
        public virtual ICollection<Cheque> Cheque { get; set; }
        public virtual ICollection<ChequeEvento> ChequeEvento { get; set; }
        public virtual ICollection<ChequeParametrosImpressao> ChequeParametrosImpressao { get; set; }
        public virtual ICollection<ContaBancariaPerfil> ContaBancariaPerfil { get; set; }
        public virtual ICollection<ContaCorrente> ContaCorrente { get; set; }
        public virtual ICollection<DefaultContabil> DefaultContabil { get; set; }
        public virtual ICollection<LancamentoBancario> LancamentoBancario { get; set; }
        public virtual ICollection<NotaEmitidaFormaPagamento> NotaEmitidaFormaPagamento { get; set; }
        public virtual ICollection<TransferenciaFisica> TransferenciaFisicaIdContaDestinoNavigation { get; set; }
        public virtual ICollection<TransferenciaFisica> TransferenciaFisicaIdContaOrigemNavigation { get; set; }
    }
}