// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContaAuditoria
    {
        public int IdConta { get; set; }
        public DateTime? DtEntrada { get; set; }
        public DateTime? DtDevolucao { get; set; }
        public DateTime? DtDevolucaoReal { get; set; }
        public DateTime? DtDevolucaoCorrecao { get; set; }
        public string TxMotivoDevolucao { get; set; }
    }
}