// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContaItemCh
    {
        public int IdContaItem { get; set; }
        public double QnCh { get; set; }
        public double VlCh { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual ContaItem IdContaItemNavigation { get; set; }
    }
}