// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContaItemHistorico
    {
        public int IdContaItem { get; set; }
        public DateTime DtOcorrencia { get; set; }
        public int IdJustificativaPadrao { get; set; }
        public string TxJustificativa { get; set; }
        public bool InCancelamento { get; set; }
        public double VlCobradoItem { get; set; }
        public int IdUsuarioOcorrencia { get; set; }
        public double VlDesconto { get; set; }
        public double VlTotalDesconto { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual ContaItem IdContaItemNavigation { get; set; }
        public virtual TipoDiversos IdJustificativaPadraoNavigation { get; set; }
        public virtual Usuario IdUsuarioOcorrenciaNavigation { get; set; }
    }
}