// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContaConciliacaoLote
    {
        public int IdLote { get; set; }
        public int IdOperadora { get; set; }
        public string NmOperadora { get; set; }
        public decimal VlPago { get; set; }
        public double? VlFaturado { get; set; }
        public int IdLoteContaMapa { get; set; }
    }
}