// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContaItemComposicaoNaoFaturada
    {
        public int IdConta { get; set; }
        public int IdContaItem { get; set; }
        public int IdContaItemPai { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtCadastro { get; set; }
    }
}