// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ContaPagarLog
    {
        public int IdContaPagarLog { get; set; }
        public int IdContaPagar { get; set; }
        public bool InReal { get; set; }
        public int IdTipoDocumento { get; set; }
        public int IdCondicaoPagamento { get; set; }
        public int IdPessoa { get; set; }
        public DateTime DtEntrada { get; set; }
        public DateTime? DtEmissao { get; set; }
        public int? NrDocumento { get; set; }
        public string TxSerieDocumento { get; set; }
        public double VlDocumento { get; set; }
        public double? VlAcrescimos { get; set; }
        public double? VlDescontos { get; set; }
        public double VlPagar { get; set; }
        public string TxHistorico { get; set; }
        public string TxObservacoes { get; set; }
        public int NrStatusConta { get; set; }
        public double? VlImpostos { get; set; }
        public double? VlPago { get; set; }
        public string NrContaContabil { get; set; }
        public int? IdContaDespesa { get; set; }
        public int? IdNotaEntrada { get; set; }
        public DateTime? DtVencimentoOri { get; set; }
        public int? IdUsuario { get; set; }
        public int? IdFaturafinanceira { get; set; }
        public int? IdOrdemCompraAdiantamento { get; set; }
        public int? IdGuiafiscal { get; set; }
        public DateTime? DtAtualizacao { get; set; }
        public DateTime? DtExclusao { get; set; }
        public int? IdUsuarioOperacao { get; set; }
        public int? IdContaCorrente { get; set; }
        public int? IdTipoConta { get; set; }
        public decimal? VlTributosRetidos { get; set; }
        public int? IdRetencaoTecnicaLiberacao { get; set; }
        public int? IdArquivoContabilHistoricoPadrao { get; set; }
        public string NrDocumentoStr { get; set; }

        public virtual Usuario IdUsuarioOperacaoNavigation { get; set; }
    }
}