// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class CorreioEletronicoAplicativo
    {
        public int IdCorreioEletronicoAplicativo { get; set; }
        public string TxCorreioEletronico { get; set; }
        public int? IdAplicativo { get; set; }
        public int? IdTipoUtilizacaoCorreioEletronico { get; set; }
        public int? IdAtributo { get; set; }
        public string VlAtributo { get; set; }
        public bool? InAtivo { get; set; }

        public virtual Aplicativo IdAplicativoNavigation { get; set; }
        public virtual Atributo IdAtributoNavigation { get; set; }
        public virtual TipoDiversos IdTipoUtilizacaoCorreioEletronicoNavigation { get; set; }
    }
}