// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class CotacaoProduto
    {
        /// <summary>
        /// PK da Tabela. FK com Cotacao.
        /// </summary>
        public int IdCotacao { get; set; }
        /// <summary>
        /// PK da Tabela. FK com ProdutoDetalhe_Fabricante. Referencia dos produtos pertencetes a cotação.
        /// 
        /// </summary>
        public int IdProdutoDetalhe { get; set; }
        /// <summary>
        /// Quantidade de produto a ser cotado.
        /// 
        /// </summary>
        public int? QnProduto { get; set; }
        /// <summary>
        /// Unidade de medida do produto. FK com TipoDiversos.
        /// 
        /// </summary>
        public int? IdUnidadeMedida { get; set; }
        /// <summary>
        /// Flag que aponta se o produto já foi cotado.
        /// </summary>
        public bool? InProdutoCotado { get; set; }
        /// <summary>
        /// Ordem de Compra que foi gerado apartir da cotação. FK com OrdemCompra.
        /// 
        /// </summary>
        public int? IdOrdemCompra { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public int? QnProdutoComprado { get; set; }

        public virtual Cotacao IdCotacaoNavigation { get; set; }
        public virtual OrdemCompra IdOrdemCompraNavigation { get; set; }
        public virtual ProdutoDetalhe IdProdutoDetalheNavigation { get; set; }
        public virtual TipoDiversos IdUnidadeMedidaNavigation { get; set; }
    }
}