// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    /// <summary>
    /// Créditos ou estornos ocorridos após o pagamento da conta ter sido feito pelo Convênio
    /// </summary>
    public partial class CreditoEstorno
    {
        /// <summary>
        /// Chave única sequencial
        /// </summary>
        public int IdCreditoestorno { get; set; }
        /// <summary>
        /// Chave Estrangeira (FechamentoItem)
        /// </summary>
        public int IdConta { get; set; }
        /// <summary>
        /// Chave Estrangeira (FechamentoItem)
        /// </summary>
        public int IdFechamentoItem { get; set; }
        /// <summary>
        /// 1=Credito 0=Estorno
        /// </summary>
        public bool InCredito { get; set; }
        /// <summary>
        /// Valor do crédito ou estorno
        /// </summary>
        public decimal VlCreditoestorno { get; set; }
        /// <summary>
        /// Data do cadastro
        /// </summary>
        public DateTime DtCadastro { get; set; }
        /// <summary>
        /// Data do crédito ou estorno
        /// </summary>
        public DateTime DtCreditoestorno { get; set; }
        /// <summary>
        /// Complemento da justificativa
        /// </summary>
        public string TxObservacao { get; set; }
        /// <summary>
        /// Chave Estrangeira (TipoDiversos: TipoTabela 408: Motivo de Credito ou Estorno)
        /// </summary>
        public int IdTipoMotivo { get; set; }
        /// <summary>
        /// Chave Estrangeira (ARQUIVO_UNIMED)
        /// </summary>
        public int? IdArquivoUnimed { get; set; }
        /// <summary>
        /// Usuário que atualizou o registro
        /// </summary>
        public int? IdUsuario { get; set; }
        /// <summary>
        /// 1=Ativo
        /// </summary>
        public bool? InAtivo { get; set; }
        public bool InSeloQualidade { get; set; }

        public virtual ArquivoUnimed IdArquivoUnimedNavigation { get; set; }
        public virtual TipoDiversos IdTipoMotivoNavigation { get; set; }
    }
}