// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class DadosHospital
    {
        public int IdHospital { get; set; }
        public string NmHospital { get; set; }
        public string Endereco1 { get; set; }
        public string Endereco2 { get; set; }
        public string Cnpj { get; set; }
        public string CrmResponsavelLaboratorio { get; set; }
        public string CdCnes { get; set; }
        public string Telefone { get; set; }
    }
}