// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class DevolucaoChecagemSolicitacaoPdEnfermagemHorarioAdministracao
    {
        public int IdDevolucaoChecagem { get; set; }
        public int IdSolicitacaoPdEnfermagemhorarioadministracao { get; set; }

        public virtual DevolucaoChecagem IdDevolucaoChecagemNavigation { get; set; }
        public virtual SolicitacaoPdEnfermagemHorarioAdministracao IdSolicitacaoPdEnfermagemhorarioadministracaoNavigation { get; set; }
    }
}