// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class DiaSolicitacao
    {
        public DiaSolicitacao()
        {
            DiaSolicitacaoUsuario = new HashSet<DiaSolicitacaoUsuario>();
        }

        public int IdDiaSolicitacao { get; set; }
        public int IdUnidadeSolicitante { get; set; }
        public int IdUnidadeExecutante { get; set; }
        public int IdDiaSemana { get; set; }
        public DateTime HrLimiteSolicitacao { get; set; }
        public bool InAtivo { get; set; }
        public int IdUsuarioCadastro { get; set; }
        public DateTime DtCadastro { get; set; }
        public int IdUsuarioAlterou { get; set; }
        public DateTime DtAlteracao { get; set; }

        public virtual TipoDiversos IdDiaSemanaNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeExecutanteNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeSolicitanteNavigation { get; set; }
        public virtual Usuario IdUsuarioAlterouNavigation { get; set; }
        public virtual Usuario IdUsuarioCadastroNavigation { get; set; }
        public virtual ICollection<DiaSolicitacaoUsuario> DiaSolicitacaoUsuario { get; set; }
    }
}