// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class DietaPadronizadaMedicamentoOperadora
    {
        public int IdServico { get; set; }
        public int IdProdutoDetalhe { get; set; }
        public int IdOperadora { get; set; }

        public virtual DietaPadronizadaMedicamento Id { get; set; }
        public virtual Pessoa IdOperadoraNavigation { get; set; }
    }
}