// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class DimTempo
    {
        public int IdTempo { get; set; }
        public string Data { get; set; }
        public string Mes { get; set; }
        public string Semestre { get; set; }
        public int Ano { get; set; }
    }
}