// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class DispensacaoEnfermagemHistorico
    {
        public int IdDispensacaoEnfermagem { get; set; }
        public int IdUsuarioHistorico { get; set; }
        public DateTime DtRegistro { get; set; }
        public int IdCheckinEnfermagem { get; set; }
        public int IdServico { get; set; }
        public int? IdLoteProdutoItem { get; set; }
        public int IdUsuarioDispensou { get; set; }
        public int? IdUsuarioDevolveu { get; set; }
        public bool InDevolvido { get; set; }
        public int IdTipoCobranca { get; set; }
        public int? IdUnidadeEstoque { get; set; }
        public DateTime DtDispensacao { get; set; }
        public DateTime? DtDevolucao { get; set; }
        public bool InCobrado { get; set; }
        public int? IdProdutoDetalhe { get; set; }
        public int? IdFabricante { get; set; }
        public double? QnFracionado { get; set; }
        public DateTime? DtLancamento { get; set; }
        public int? IdComposicaoItemProduto { get; set; }
        public int? IdAgrupamentoMaterial { get; set; }
        public int? IdMdFracionado { get; set; }

        public virtual DispensacaoEnfermagem IdDispensacaoEnfermagemNavigation { get; set; }
        public virtual Usuario IdUsuarioHistoricoNavigation { get; set; }
    }
}