// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Dmed
    {
        public string NrCpfResponsavel { get; set; }
        public string NmResponsavel { get; set; }
        public decimal? VlResponsavel { get; set; }
        public string NrCpfBeneficiario { get; set; }
        public string DtNascBeneficiario { get; set; }
        public string NmBeneficiario { get; set; }
        public decimal? VlBeneficiario { get; set; }
        public int NrAnoReferencia { get; set; }
        public int NrAnoCalendario { get; set; }
        public int IdDmed { get; set; }
        public int IdNotaEmitida { get; set; }

        public virtual NotaEmitida IdNotaEmitidaNavigation { get; set; }
    }
}