// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class DocumentoFluxoEtapa
    {
        public DocumentoFluxoEtapa()
        {
            DocumentoFluxoDocumentoFluxoEtapa = new HashSet<DocumentoFluxoDocumentoFluxoEtapa>();
        }

        public int IdDocumentoFluxoEtapa { get; set; }
        public string NmFluxoDocumentoEtapa { get; set; }
        public int IdUnidadeOrganizacionalInicio { get; set; }
        public int IdUnidadeOrganizacionalFinal { get; set; }
        public bool? InAtivo { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual ICollection<DocumentoFluxoDocumentoFluxoEtapa> DocumentoFluxoDocumentoFluxoEtapa { get; set; }
    }
}