// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class DocumentoLoteAuditoria
    {
        public int IdDocumentoLote { get; set; }
        public DateTime DtExclusao { get; set; }
        public int IdUsuario { get; set; }
        public int IdClienteComputador { get; set; }
        public int IdClientePagina { get; set; }

        public virtual ClienteComputador IdClienteComputadorNavigation { get; set; }
        public virtual ClientePagina IdClientePaginaNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}