// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class DocumentoProtocoloMotivoDevolucao
    {
        public int IdDocumentoProtocoloMotivoDevolucao { get; set; }
        public int IdDocumentoProtocolo { get; set; }
        public int IdMotivoDevolucao { get; set; }

        public virtual DocumentoProtocolo IdDocumentoProtocoloNavigation { get; set; }
        public virtual TipoDiversos IdMotivoDevolucaoNavigation { get; set; }
    }
}