// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class DocumentoExigidoUnidadeOrganizacional
    {
        public int IdDocumentoExigido { get; set; }
        public int IdUnidadeOrganizacional { get; set; }
        public int InAtivo { get; set; }
        public int IdUnidadeTipo { get; set; }

        public virtual DocumentoExigido IdDocumentoExigidoNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeOrganizacionalNavigation { get; set; }
        public virtual TipoDiversos IdUnidadeTipoNavigation { get; set; }
    }
}