// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class DrgInternacao
    {
        public int IdDrgInternacao { get; set; }
        public int IdAtendimento { get; set; }
        public string TxSituacao { get; set; }
        public string TxCarater { get; set; }
        public string NrOperadora { get; set; }
        public string NrRegistro { get; set; }
        public string NrAutorizacao { get; set; }
        public string DtInternacao { get; set; }
        public string DtAlta { get; set; }
        public string TxCondicaoAlta { get; set; }
        public string TxCodCidPrincipal { get; set; }
        public string DtAutorizacao { get; set; }
        public string TxInternadoOutrasVezes { get; set; }
        public string TxReinternacao { get; set; }
        public string TxRecaida { get; set; }
        public string TxCodCidSecundario { get; set; }
        public string TxAltaAdmNrAtend { get; set; }
        public string TxAltaAdmNrAutorizacao { get; set; }

        public virtual Atendimento IdAtendimentoNavigation { get; set; }
    }
}