// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class DrgOperadora
    {
        public int IdDrgOperadora { get; set; }
        public int IdAtendimento { get; set; }
        public string TxCodigo { get; set; }
        public string TxNome { get; set; }
        public string TxSigla { get; set; }
        public string TxPlano { get; set; }
        public string TxNumCarteira { get; set; }
        public string TxDtValidade { get; set; }
        public string TxTipo { get; set; }

        public virtual Atendimento IdAtendimentoNavigation { get; set; }
    }
}