// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Efd
    {
        public int Efdid { get; set; }
        public int? TipoEscrit0000 { get; set; }
        public int? IndSitEsp0000 { get; set; }
        public string Nome0000 { get; set; }
        public string Cnpj0000 { get; set; }
        public string Uf0000 { get; set; }
        public string CodMun0000 { get; set; }
        public string Suframa0000 { get; set; }
        public int? IndNatPj0000 { get; set; }
        public int? IndAtiv0000 { get; set; }
        public string Nome0100 { get; set; }
        public string Cpf0100 { get; set; }
        public int? CodIncTrib0110 { get; set; }
        public int? IndAproCred0110 { get; set; }
        public string Crc0100 { get; set; }
        public string CodMun0140 { get; set; }
        public string Im0140 { get; set; }
        public int? TipoItem0200 { get; set; }
        public int? CodGen0200 { get; set; }
        public int? CodLst200 { get; set; }
    }
}