// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class EmbalagemEmbalagem
    {
        public EmbalagemEmbalagem()
        {
            EmbalagemProdutoDetalhe = new HashSet<EmbalagemProdutoDetalhe>();
        }

        /// <summary>
        /// PK da Tabela. FK com Embalagem. Representa a Embalagem Pai.
        /// </summary>
        public int IdEmbalagemPai { get; set; }
        /// <summary>
        /// PK da Tabela. FK com Embalagem. Representa a Embalagem Filho
        /// 
        /// </summary>
        public int IdEmbalagemFilho { get; set; }
        /// <summary>
        /// Representa o Fator de Conversão entre uma Embalagem Pai e Filho. EX: Caixa com 12 Unidades e Unidade. Fator de conversão é 12.
        /// 
        /// </summary>
        public string NrFatorConversao { get; set; }

        public virtual Embalagem IdEmbalagemFilhoNavigation { get; set; }
        public virtual Embalagem IdEmbalagemPaiNavigation { get; set; }
        public virtual ICollection<EmbalagemProdutoDetalhe> EmbalagemProdutoDetalhe { get; set; }
    }
}