// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Emprestimo
    {
        public Emprestimo()
        {
            EmprestimoLoteProdutoItem = new HashSet<EmprestimoLoteProdutoItem>();
            EmprestimoPagamento = new HashSet<EmprestimoPagamento>();
            EmprestimoProdutoDetalhe = new HashSet<EmprestimoProdutoDetalhe>();
        }

        public int NrEmprestimo { get; set; }
        public int? IdPessoa { get; set; }
        public int? IdTipoEmprestimo { get; set; }
        public DateTime? DtEmprestimo { get; set; }
        public bool? InFechado { get; set; }
        public int? IdUsuario { get; set; }
        public int? IdUsuarioResponsavel { get; set; }
        public string TxUsuarioRepresentante { get; set; }
        public string TxObservacao { get; set; }
        public bool? InConsignado { get; set; }

        public virtual Pessoa IdPessoaNavigation { get; set; }
        public virtual TipoDiversos IdTipoEmprestimoNavigation { get; set; }
        public virtual ICollection<EmprestimoLoteProdutoItem> EmprestimoLoteProdutoItem { get; set; }
        public virtual ICollection<EmprestimoPagamento> EmprestimoPagamento { get; set; }
        public virtual ICollection<EmprestimoProdutoDetalhe> EmprestimoProdutoDetalhe { get; set; }
    }
}