// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class EmprestimoPagamento
    {
        public int IdEmprestimoPagamento { get; set; }
        public int IdEmprestimo { get; set; }
        public int? IdLoteProdutoItem { get; set; }
        public int IdProdutoDetalhe { get; set; }
        public int IdFabricante { get; set; }
        public int IdEmbalagem { get; set; }
        public int QnProduto { get; set; }
        public string NrLoteProduto { get; set; }
        public DateTime? DtValidade { get; set; }
        public int IdResponsavel { get; set; }
        public DateTime? DtPagamento { get; set; }
        public bool? InEtiquetado { get; set; }

        public virtual ProdutoDetalheFabricante Id { get; set; }
        public virtual Embalagem IdEmbalagemNavigation { get; set; }
        public virtual Emprestimo IdEmprestimoNavigation { get; set; }
        public virtual LoteProdutoItem IdLoteProdutoItemNavigation { get; set; }
        public virtual Usuario IdResponsavelNavigation { get; set; }
    }
}