// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Envioagenda
    {
        public int IdEnvioagenda { get; set; }
        public string Dataatendimento { get; set; }
        public string Horaatendimento { get; set; }
        public int? Crm { get; set; }
        public int Codigoespecialidade { get; set; }
        public string Tipoatendimento { get; set; }
        public string Cnpjconvenio { get; set; }
        public string Descricaoconvenio { get; set; }
        public int? Carteiraconvenio { get; set; }
        public string Idclienteintegracao { get; set; }
        public int? Numeroprontuario { get; set; }
        public string Nomecliente { get; set; }
        public string Sexo { get; set; }
        public string Naturalidade { get; set; }
        public string Nacionalidade { get; set; }
        public string Cpf { get; set; }
        public string Datanascimento { get; set; }
        public string Nomemae { get; set; }
        public string Nomepai { get; set; }
        public string Email { get; set; }
        public int? Estadocivil { get; set; }
        public string Tipodocumento { get; set; }
        public string Numerodocumento { get; set; }
        public string Orgaoexpedidor { get; set; }
        public string Responsavellegal { get; set; }
        public string Pessoacontato { get; set; }
        public int? Dddpessoacontato { get; set; }
        public int? Numeropessoacontato { get; set; }
        public int? Dddtelefoneresidencial { get; set; }
        public int? Telefoneresidencial { get; set; }
        public int? Dddcelular { get; set; }
        public int? Celular { get; set; }
        public int? Dddtelefonecomercial { get; set; }
        public int? Telefonecomercial { get; set; }
        public int? Cep { get; set; }
        public string Endereco { get; set; }
        public int? Numero { get; set; }
        public string Complementoendereco { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Uf { get; set; }
        public string Cnpjconvenio1 { get; set; }
        public string Descricaoconvenio1 { get; set; }
        public string Carteiraconvenio1 { get; set; }
        public string Cnpjconvenio2 { get; set; }
        public string Descricaoconvenio2 { get; set; }
        public string Carteiraconvenio2 { get; set; }
        public int? IdAtendimento { get; set; }
        public DateTime? DtCadastro { get; set; }
    }
}