// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class EquipeResponsavel
    {
        public int IdCheckinEnfermagem { get; set; }
        public int IdProcedimentoPrincipal { get; set; }
        public int IdProfissional { get; set; }
        public int IdFuncao { get; set; }
        public bool InRepasse { get; set; }
        /// <summary>
        /// armazena a especialidade do médico para aquele procedimento
        /// </summary>
        public int? IdEspecialidade { get; set; }

        public virtual Folhadesala Id { get; set; }
        public virtual TipoDiversos IdEspecialidadeNavigation { get; set; }
        public virtual CirurgiaFuncaoTipo IdFuncaoNavigation { get; set; }
        public virtual Pessoa IdProfissionalNavigation { get; set; }
    }
}