// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Estatistica
    {
        public string CodServidor { get; set; }
        public int? DatabaseId { get; set; }
        public DateTime? DatExecucao { get; set; }
        public decimal QteMediaDuracao { get; set; }
        public int QteExecucao { get; set; }
    }
}