// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class EtiquetasAtendimento
    {
        public int IdAtendimento { get; set; }
        public string NmPaciente { get; set; }
        public string DtAtendimento { get; set; }
        public string HrAtendimento { get; set; }
        public string DtAlta { get; set; }
        public string HrAlta { get; set; }
        public string TxNaturalidade { get; set; }
        public string TxSexo { get; set; }
        public string TxOperadora { get; set; }
        public string NrMatricula { get; set; }
        public string NmTitular { get; set; }
        public string DtNascimento { get; set; }
        public string NmMae { get; set; }
        public string NmMedico { get; set; }
        public string NmEstadoCivil { get; set; }
        public string CdIdentidade { get; set; }
        public string NrCrm { get; set; }
        public string NrProntuario { get; set; }
        public string TxTelefoneResidencial { get; set; }
        public string TxTelefoneComercial { get; set; }
        public string TxTelefoneCelular { get; set; }
        public string NrGuia { get; set; }
        public string NmResponsavel { get; set; }
        public string TxLeito { get; set; }
        public string DtValidadeCartao { get; set; }
        public string TxEndereco { get; set; }
        public string TxComplemento { get; set; }
        public string TxBairro { get; set; }
        public string TxCep { get; set; }
        public string TxTelefoneResidencialAc { get; set; }
        public string TxTelefoneComercialAc { get; set; }
        public string TxTelefoneCelularAc { get; set; }
        public string TxTelefoneResidencialMe { get; set; }
        public string TxTelefoneComercialMe { get; set; }
        public string TxTelefoneCelularMe { get; set; }
        public int? NrContaParticular { get; set; }
        public int? NrContaConvenio { get; set; }
        public string TxEspecialidade { get; set; }
        public string DtFimAtendimento { get; set; }
        public string HrFimAtendimento { get; set; }
    }
}