// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class EventoIntegracao
    {
        /// <summary>
        /// identificador único do evento
        /// </summary>
        public int IdEventoIntegracao { get; set; }
        /// <summary>
        /// tipo tabela 396
        /// </summary>
        public int IdEvento { get; set; }
        /// <summary>
        /// data que ocorreu o evento
        /// </summary>
        public DateTime DtEvento { get; set; }
        /// <summary>
        /// XML contendo os ID dos itens que foram disparados os eventos
        /// </summary>
        public string TxDados { get; set; }
        public bool InProcessou { get; set; }
        public bool InCancelado { get; set; }
        public int? IdAtendimento { get; set; }
        public DateTime? DtProcessamento { get; set; }

        public virtual TipoDiversos IdEventoNavigation { get; set; }
    }
}