// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ExameServico
    {
        /// <summary>
        /// identificador do serviço que cairá na conta
        /// </summary>
        public int IdServico { get; set; }
        /// <summary>
        /// identificador do exame
        /// </summary>
        public int IdExame { get; set; }
        /// <summary>
        /// exclusão lógica
        /// </summary>
        public bool? InAtivo { get; set; }
        /// <summary>
        /// identificador único do relacionamento entre exames e serviços
        /// </summary>
        public int IdExameServico { get; set; }
        /// <summary>
        /// identificador da operadora
        /// </summary>
        public int? IdOperadora { get; set; }
        public double? VlServico { get; set; }

        public virtual Exame IdExameNavigation { get; set; }
        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual Servico IdServicoNavigation { get; set; }
    }
}