// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ExameItemExame
    {
        public ExameItemExame()
        {
            ExameItemExameTipoTabela = new HashSet<ExameItemExameTipoTabela>();
            ValorReferencia = new HashSet<ValorReferencia>();
        }

        public int IdExameMaterialMeioMetodo { get; set; }
        public int IdItemExame { get; set; }
        public int NrOrdem { get; set; }
        public bool InUsaValorReferencia { get; set; }
        public string TxValorReferencia { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public int? IdUnidadePadraoTipo { get; set; }

        public virtual ExameMaterialColeta IdExameMaterialMeioMetodoNavigation { get; set; }
        public virtual ItemExame IdItemExameNavigation { get; set; }
        public virtual TipoDiversos IdUnidadePadraoTipoNavigation { get; set; }
        public virtual ICollection<ExameItemExameTipoTabela> ExameItemExameTipoTabela { get; set; }
        public virtual ICollection<ValorReferencia> ValorReferencia { get; set; }
    }
}