// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ExameItemColeta
    {
        public ExameItemColeta()
        {
            LaboratorioPedidoColetaItem = new HashSet<LaboratorioPedidoColetaItem>();
            LaboratorioPedidoColetaItemOld = new HashSet<LaboratorioPedidoColetaItemOld>();
        }

        /// <summary>
        /// identificados unico da tabela
        /// </summary>
        public int IdExameItemColeta { get; set; }
        /// <summary>
        /// referencia do identificador do exame
        /// </summary>
        public int IdExame { get; set; }
        /// <summary>
        /// ordem que os campos aparecem na tela e que são impressos
        /// </summary>
        public int NrOrdem { get; set; }
        /// <summary>
        /// label do item que aparece no resultado
        /// </summary>
        public string NmItem { get; set; }
        /// <summary>
        /// se o dado é obrigatório
        /// </summary>
        public bool InObrigatorio { get; set; }
        /// <summary>
        /// tipo do dado que será lançado
        /// </summary>
        public int IdTipoValor { get; set; }
        /// <summary>
        /// tamanho dos campos, caso texto
        /// </summary>
        public int? NrTamanho { get; set; }
        /// <summary>
        /// unidade de medida, tipo tabela 137
        /// </summary>
        public int? IdUnidade { get; set; }
        /// <summary>
        /// range mínimo para alertar o laboratório
        /// </summary>
        public double? NrRangeMin { get; set; }
        /// <summary>
        /// range máximo para alertar o laboratório
        /// </summary>
        public double? NrRangeMax { get; set; }
        /// <summary>
        /// quando o item tem valores predefinidos e utilizam a estrutura do tipodiversos, como cor de urina
        /// </summary>
        public int? IdTabela { get; set; }
        /// <summary>
        /// excelusão lógica
        /// </summary>
        public bool? InAtivo { get; set; }
        /// <summary>
        /// quando o item é calculado
        /// </summary>
        public string TxFormula { get; set; }
        public string TxCampoReferencia { get; set; }
        public int? IdTipoValorAnteriorPor { get; set; }
        public int? IdTipoResponsavelLancamento { get; set; }

        public virtual Exame IdExameNavigation { get; set; }
        public virtual TipoTabela IdTabelaNavigation { get; set; }
        public virtual TipoDiversos IdTipoResponsavelLancamentoNavigation { get; set; }
        public virtual TipoDiversos IdTipoValorAnteriorPorNavigation { get; set; }
        public virtual TipoDiversos IdTipoValorNavigation { get; set; }
        public virtual TipoDiversos IdUnidadeNavigation { get; set; }
        public virtual ICollection<LaboratorioPedidoColetaItem> LaboratorioPedidoColetaItem { get; set; }
        public virtual ICollection<LaboratorioPedidoColetaItemOld> LaboratorioPedidoColetaItemOld { get; set; }
    }
}