// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ExameExame
    {
        /// <summary>
        /// identificador do exame pacote
        /// </summary>
        public int IdExamePai { get; set; }
        /// <summary>
        /// identificador do exame simples
        /// </summary>
        public int IdExameFilho { get; set; }
        /// <summary>
        /// exclusão lógica
        /// </summary>
        public bool? InAtivo { get; set; }
        /// <summary>
        /// data que foi cadastrado este relacionamento
        /// </summary>
        public DateTime DtCadastro { get; set; }
        /// <summary>
        /// número de amostras que será lançada no pedido
        /// </summary>
        public int NrAmostra { get; set; }
        /// <summary>
        /// unidade de medida do tempo do intervalo entre as amostras,tipo tabela 57
        /// </summary>
        public int? IdUnidadeTempo { get; set; }
        /// <summary>
        /// tempo do intervalo de acordo com a unidade, geralmente em minutos
        /// </summary>
        public int? NrIntervalo { get; set; }
        public bool InExcecao { get; set; }

        public virtual Exame IdExameFilhoNavigation { get; set; }
        public virtual Exame IdExamePaiNavigation { get; set; }
        public virtual TipoDiversos IdUnidadeTempoNavigation { get; set; }
    }
}