// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class FaturamentoContaTiss
    {
        public int IdFaturamentoContaTiss { get; set; }
        public int IdOperadora { get; set; }
        public string CdMedicamento { get; set; }
        public string TxMedicamento { get; set; }
        public string CdMaterial { get; set; }
        public string TxMaterial { get; set; }
        public string CdOpm { get; set; }
        public string TxOpm { get; set; }
        public int? IdTipoTabelaTissPacote { get; set; }
        public string TxCaractere { get; set; }
        public int? NrQuantidadeCaractere { get; set; }
        public int? QnCaractereMedicamento { get; set; }
        public int? QnCaractereMaterial { get; set; }
        public int? QnCaractereOpm { get; set; }
        public string CdCodigoMedicamentoGenerico { get; set; }
        public string CdCodigoMaterialGenerico { get; set; }
        public string CdCodigoOpmeGenerico { get; set; }
        public int NrGuiaPrestadorGuiaimpressa { get; set; }
        public int NrGuiaOperadoraXml { get; set; }
        public int NrGuiaPrestadorXml { get; set; }

        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual TipoDiversos IdTipoTabelaTissPacoteNavigation { get; set; }
    }
}