// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class FaturamentoContasHistorico
    {
        public int IdFaturamentoConta { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtOcorrencia { get; set; }
        public bool InInsercao { get; set; }

        public virtual FaturamentoConta IdFaturamentoContaNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}