// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class FaturaFinanceiraLog
    {
        public int IdFaturafinanceiraLog { get; set; }
        public int IdFaturafinanceira { get; set; }
        public string TxIdentificacao { get; set; }
        public int IdTipoFatura { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtReferencia { get; set; }
        public DateTime DtCadastro { get; set; }
        public bool InAtivo { get; set; }
        public bool InPagar { get; set; }
        public decimal? VlTotalBaixa { get; set; }
        public decimal? VlTotalAcrescimos { get; set; }
        public decimal? VlTotalDescontos { get; set; }
        public decimal? VlFaturafinanceira { get; set; }
        public DateTime? DtPreparacaoFinalizada { get; set; }
        public int? IdUsuarioFinalizacao { get; set; }
        public int? IdCondicaoPagamento { get; set; }
        public int? NrDiaFixoVencimentoParcelas { get; set; }
        public int? IdTipoDocumento { get; set; }
        public int? IdPessoa { get; set; }
        public int? NrDocumento { get; set; }
        public string TxObservacoes { get; set; }
        public decimal? VlTotalPendente { get; set; }
        public decimal? VlAcrescimoGeral { get; set; }
        public decimal? VlDescontoGeral { get; set; }
        public DateTime? DtAtualizacao { get; set; }
        public DateTime? DtExclusao { get; set; }
        public int? IdUsuarioOperacao { get; set; }
        public bool InGeraTributo { get; set; }

        public virtual Usuario IdUsuarioOperacaoNavigation { get; set; }
    }
}