// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class FaturaFinanceira
    {
        public FaturaFinanceira()
        {
            ContaPagar = new HashSet<ContaPagar>();
            ContaReceber = new HashSet<ContaReceber>();
            ParcelaContaPagarBaixa = new HashSet<ParcelaContaPagarBaixa>();
            ParcelaContaReceberBaixa = new HashSet<ParcelaContaReceberBaixa>();
        }

        public int IdFaturafinanceira { get; set; }
        public string TxIdentificacao { get; set; }
        public int IdTipoFatura { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtReferencia { get; set; }
        public DateTime DtCadastro { get; set; }
        public bool? InAtivo { get; set; }
        public bool? InPagar { get; set; }
        public decimal? VlTotalBaixa { get; set; }
        public decimal? VlTotalAcrescimos { get; set; }
        public decimal? VlTotalDescontos { get; set; }
        public decimal? VlFaturafinanceira { get; set; }
        public DateTime? DtPreparacaoFinalizada { get; set; }
        public int? IdUsuarioFinalizacao { get; set; }
        public int? IdCondicaoPagamento { get; set; }
        public int? NrDiaFixoVencimentoParcelas { get; set; }
        public int? IdTipoDocumento { get; set; }
        public int? IdPessoa { get; set; }
        public int? NrDocumento { get; set; }
        public string TxObservacoes { get; set; }
        public decimal? VlTotalPendente { get; set; }
        public decimal? VlAcrescimoGeral { get; set; }
        public decimal? VlDescontoGeral { get; set; }
        public bool InGeraTributo { get; set; }

        public virtual CondicaoPagamento IdCondicaoPagamentoNavigation { get; set; }
        public virtual Pessoa IdPessoaNavigation { get; set; }
        public virtual TipoDocumento IdTipoDocumentoNavigation { get; set; }
        public virtual TipoDiversos IdTipoFaturaNavigation { get; set; }
        public virtual Usuario IdUsuarioFinalizacaoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<ContaPagar> ContaPagar { get; set; }
        public virtual ICollection<ContaReceber> ContaReceber { get; set; }
        public virtual ICollection<ParcelaContaPagarBaixa> ParcelaContaPagarBaixa { get; set; }
        public virtual ICollection<ParcelaContaReceberBaixa> ParcelaContaReceberBaixa { get; set; }
    }
}