// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class FechamentoItemValorLiberado
    {
        public FechamentoItemValorLiberado()
        {
            AcrescimosFechamentoItemValorLiberado = new HashSet<AcrescimosFechamentoItemValorLiberado>();
            GlosaFechamentoItemValorLiberado = new HashSet<GlosaFechamentoItemValorLiberado>();
        }

        public int IdFechamentoitemvalorliberado { get; set; }
        public int? IdConta { get; set; }
        public int? IdFechamentoItem { get; set; }
        public decimal VlProcessado { get; set; }
        public decimal VlLiberado { get; set; }
        public DateTime DtCadastro { get; set; }
        public DateTime? DtCredito { get; set; }
        public string TxObservacao { get; set; }
        public int? IdRetornoArquivoProcessamento { get; set; }
        public int? IdUsuario { get; set; }
        public bool? InAtivo { get; set; }
        public int? IdFechamentoitemvalorliberadoSomatorio { get; set; }

        public virtual FechamentoItem Id { get; set; }
        public virtual RetornoArquivoProcessamento IdRetornoArquivoProcessamentoNavigation { get; set; }
        public virtual ICollection<AcrescimosFechamentoItemValorLiberado> AcrescimosFechamentoItemValorLiberado { get; set; }
        public virtual ICollection<GlosaFechamentoItemValorLiberado> GlosaFechamentoItemValorLiberado { get; set; }
    }
}