// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class FechamentoItemHonorarioCooperado
    {
        public int IdConta { get; set; }
        public int IdFechamentoItem { get; set; }
        public double VlUnitario { get; set; }
        public double VlFechamentoItem { get; set; }

        public virtual FechamentoItem Id { get; set; }
    }
}