// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class FeriadoData
    {
        public int IdFeriado { get; set; }
        public DateTime DtFeriado { get; set; }
        public byte[] RvVersaLinha { get; set; }

        public virtual Feriado IdFeriadoNavigation { get; set; }
    }
}