// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class FilaConta
    {
        public FilaConta()
        {
            FilaContaHistorico = new HashSet<FilaContaHistorico>();
        }

        public int IdFilaConta { get; set; }
        public int IdConta { get; set; }
        public int IdFilaContaTipo { get; set; }
        public int IdFilaContaAcaoTipo { get; set; }
        public int IdUsuario { get; set; }
        public int NrItens { get; set; }
        public string TxParametros { get; set; }
        public int NrTentativas { get; set; }
        public bool InPriorizar { get; set; }
        public DateTime DtInclusao { get; set; }
        public bool InProcessada { get; set; }

        public virtual FilaContaAcaoTipo IdFilaContaAcaoTipoNavigation { get; set; }
        public virtual FilaContaTipo IdFilaContaTipoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<FilaContaHistorico> FilaContaHistorico { get; set; }
    }
}