// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class FilaContaAcaoTipo
    {
        public FilaContaAcaoTipo()
        {
            FilaConta = new HashSet<FilaConta>();
        }

        public int IdFilaContaAcaoTipo { get; set; }
        public string TxDescricao { get; set; }

        public virtual ICollection<FilaConta> FilaConta { get; set; }
    }
}