// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Glosa
    {
        public Glosa()
        {
            GlosaAcatada = new HashSet<GlosaAcatada>();
            GlosaJustificativaSecundaria = new HashSet<GlosaJustificativaSecundaria>();
            JustificativaGlosaFiComplementar = new HashSet<JustificativaGlosaFiComplementar>();
            RecursoGlosa = new HashSet<RecursoGlosa>();
        }

        public int IdConta { get; set; }
        public int IdFechamentoItem { get; set; }
        public double? VlGlosado { get; set; }
        public double? QnGlosada { get; set; }
        public string IdJustificativa { get; set; }
        public string TxObservacoes { get; set; }
        public int? IdUnidadeOrganizacional { get; set; }
        public int IdUsuario { get; set; }
        public bool? InAdministrativa { get; set; }
        public int? IdUnidadeOrganizacionalAuditoria { get; set; }
        public DateTime? DtGlosa { get; set; }
        public int? NrOrigemUnimed { get; set; }
        public bool? InAtivo { get; set; }
        public bool InGlosaMista { get; set; }
        public decimal? VlUnitarioPago { get; set; }
        public string IdJustificativaComplementar { get; set; }
        public bool InRecorrer { get; set; }
        public bool InPreparandoContaLimpa { get; set; }

        public virtual FechamentoItem Id { get; set; }
        public virtual JustificativaGlosaFi IdJustificativaNavigation { get; set; }
        public virtual ICollection<GlosaAcatada> GlosaAcatada { get; set; }
        public virtual ICollection<GlosaJustificativaSecundaria> GlosaJustificativaSecundaria { get; set; }
        public virtual ICollection<JustificativaGlosaFiComplementar> JustificativaGlosaFiComplementar { get; set; }
        public virtual ICollection<RecursoGlosa> RecursoGlosa { get; set; }
    }
}