// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class GlosaAcatadaParcialLog
    {
        public int IdGlosaAcatadaParcialLog { get; set; }
        public int IdGlosaAcatadaParcial { get; set; }
        public int IdConta { get; set; }
        public int IdFechamentoItem { get; set; }
        public int? IdUsuario { get; set; }
        public DateTime? DtAcato { get; set; }
        public int? IdJustificativaAcato { get; set; }
        public decimal? VlAcatado { get; set; }
        public string TxObservacao { get; set; }
        public int? IdCartarecurso { get; set; }
        public int? IdFaturamentobaixagrupo { get; set; }
        public bool InBaixouContaReceber { get; set; }
        public DateTime DtCadastro { get; set; }
        public DateTime? DtAtualizacao { get; set; }
        public DateTime? DtExclusao { get; set; }
        public int? IdUsuarioOperacao { get; set; }

        public virtual Usuario IdUsuarioOperacaoNavigation { get; set; }
    }
}