// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class GlosaGenericaAcatada
    {
        public int IdGlosaGenericaAcatada { get; set; }
        public int IdConta { get; set; }
        public decimal VlAcatado { get; set; }
        public DateTime DtAcato { get; set; }
        public int IdJustificativaAcato { get; set; }
        public string TxObservacao { get; set; }
        public int IdUsuario { get; set; }
        public bool? InAtivo { get; set; }
        public int? IdMovimentacaocontaparcelabaixada { get; set; }
        public bool InBaixouContaReceber { get; set; }
        public int? IdCartarecurso { get; set; }
        public int? IdFaturamentobaixagrupo { get; set; }

        public virtual CartaRecurso IdCartarecursoNavigation { get; set; }
        public virtual Conta IdContaNavigation { get; set; }
        public virtual FaturamentoBaixaGrupo IdFaturamentobaixagrupoNavigation { get; set; }
        public virtual JustificativaAcato IdJustificativaAcatoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}