// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class GlosaFechamentoItemValorLiberado
    {
        public int IdGlosaFechamentoItemValorLiberado { get; set; }
        public int IdConta { get; set; }
        public int IdFechamentoItem { get; set; }
        public int? IdFechamentoitemvalorliberado { get; set; }
        public int IdUsuario { get; set; }
        public bool? InAtivo { get; set; }

        public virtual FechamentoItem Id { get; set; }
        public virtual FechamentoItemValorLiberado IdFechamentoitemvalorliberadoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}