// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class GrupoInspecaoRecebimento
    {
        public GrupoInspecaoRecebimento()
        {
            ParametroAvaliacaoRecebimento = new HashSet<ParametroAvaliacaoRecebimento>();
        }

        public int IdGrupoInspecaoRecebimento { get; set; }
        public string NmGrupo { get; set; }
        public int VlPeso { get; set; }
        public DateTime DtCadastro { get; set; }
        public int IdUsuario { get; set; }
        public DateTime? DtExclusao { get; set; }
        public int? IdUsuarioExcluiu { get; set; }
        public bool InAtivo { get; set; }
        public int? IdTipoNota { get; set; }

        public virtual TipoDiversos IdTipoNotaNavigation { get; set; }
        public virtual Usuario IdUsuarioExcluiuNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<ParametroAvaliacaoRecebimento> ParametroAvaliacaoRecebimento { get; set; }
    }
}