// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class GrupoBacteriaBacteria
    {
        public int IdGrupoBacteria { get; set; }
        public int IdBacteria { get; set; }
        public bool InAtivo { get; set; }

        public virtual Bacteria IdBacteriaNavigation { get; set; }
        public virtual GrupoBacteria IdGrupoBacteriaNavigation { get; set; }
    }
}