// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class GuiaFiscalContaPagarTributoAliquota
    {
        public int IdGuiafiscalContaPagarTributoAliquota { get; set; }
        public int IdGuiafiscal { get; set; }
        public int IdContaPagarTributoAliquota { get; set; }
        public bool? InAtivo { get; set; }
        public DateTime DtCadastro { get; set; }
        public int IdUsuario { get; set; }

        public virtual ContaPagarTributoAliquota IdContaPagarTributoAliquotaNavigation { get; set; }
        public virtual GuiaFiscal IdGuiafiscalNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}