// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class HabilitacaoSusCredenciada
    {
        public int IdHabilitacaoSusCredenciada { get; set; }
        public int IdTipoHabilitacao { get; set; }
        public short? InOrigem { get; set; }
        public DateTime? DtCompetenciaIncial { get; set; }
        public DateTime? DtCompetenciaFinal { get; set; }
        public string TxDescPortaria { get; set; }
        public DateTime? DtPortaria { get; set; }
        public int? QnLeitoSus { get; set; }
        public DateTime? DtLancamento { get; set; }
        public DateTime? DtAtualizacao { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtCadastro { get; set; }
        public bool? InAtivo { get; set; }
    }
}