// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class HorarioLaboratorioDiaSemana
    {
        public int IdDiaSemanaTipo { get; set; }
        public DateTime HrInicio { get; set; }
        public DateTime HrFim { get; set; }
        public int IdHorarioLaboratorio { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual TipoDiversos IdDiaSemanaTipoNavigation { get; set; }
        public virtual HorarioLaboratorio IdHorarioLaboratorioNavigation { get; set; }
    }
}