// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class HospitalarAtendimentoTeste
    {
        public int IdOrdemServico { get; set; }
        public DateTime? DtEntrada { get; set; }
        public int? IdAtendimentoTipo { get; set; }
        public int IdCentroCusto { get; set; }
    }
}