// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class HospitaleLogScript
    {
        /// <summary>
        /// nome do sprint do script executado
        /// </summary>
        public string NmSprint { get; set; }
        public int IdWorkItem { get; set; }
        public string NmWorkItem { get; set; }
        /// <summary>
        /// nome do arquivo do script
        /// </summary>
        public string NmArquivo { get; set; }
        /// <summary>
        /// data que foi executado o script
        /// </summary>
        public DateTime DtExecucao { get; set; }
        /// <summary>
        /// legenda do arquivo de script
        /// </summary>
        public string TxObservacao { get; set; }
    }
}