// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class IntervaloAplicacaoMedicamento
    {
        public IntervaloAplicacaoMedicamento()
        {
            ComplementoDietetico = new HashSet<ComplementoDietetico>();
            Posologia = new HashSet<Posologia>();
            ProtocoloAplicacaoAtendimento = new HashSet<ProtocoloAplicacaoAtendimento>();
            ProtocoloItem = new HashSet<ProtocoloItem>();
        }

        public int IdIntervaloAplicacaoMedicamento { get; set; }
        public int VlIntervalo { get; set; }
        public string TxDescricaoIntervalo { get; set; }
        public bool InAtivo { get; set; }
        public int? IdTipoIntervalo { get; set; }
        public DateTime? HrInicioHorarioPadrao { get; set; }
        public string TxAbrevIntervalo { get; set; }
        public int? NrOrdem { get; set; }

        public virtual TipoDiversos IdIntervaloAplicacaoMedicamentoNavigation { get; set; }
        public virtual ICollection<ComplementoDietetico> ComplementoDietetico { get; set; }
        public virtual ICollection<Posologia> Posologia { get; set; }
        public virtual ICollection<ProtocoloAplicacaoAtendimento> ProtocoloAplicacaoAtendimento { get; set; }
        public virtual ICollection<ProtocoloItem> ProtocoloItem { get; set; }
    }
}