// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class IntegracaoAgendaHorariosChatBot
    {
        public int IdAgendaConfig { get; set; }
        public int IdUnidadeOrganizacional { get; set; }
        public int? IdRecurso { get; set; }
        public int? IdMedico { get; set; }
        public int NrDuracao { get; set; }
        public DateTime? Horario { get; set; }
        public bool? InOnline { get; set; }
        public bool? InRetorno { get; set; }
        public bool? InPrimeiraConsulta { get; set; }
        public bool? InTelemedicina { get; set; }
    }
}