// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class InteracaoMedicamentosaPrincipioAtivo
    {
        public int IdInteracaoMedicamentosa { get; set; }
        public int IdPrincipioAtivo { get; set; }

        public virtual InteracaoMedicamentosa IdInteracaoMedicamentosaNavigation { get; set; }
        public virtual TipoDiversos IdPrincipioAtivoNavigation { get; set; }
    }
}