// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class InventarioProdutoDetalheLoteProdutoItem
    {
        public int IdLoteProdutoItem { get; set; }
        public int IdInventario { get; set; }
        public int IdFabricante { get; set; }
        public int IdProdutoDetalhe { get; set; }
        public bool? InPrimeiraContagem { get; set; }
        public bool? InSegundaContagem { get; set; }
        public bool? InTerceiraContagem { get; set; }

        public virtual InventarioProdutoDetalhe Id { get; set; }
        public virtual LoteProdutoItem IdLoteProdutoItemNavigation { get; set; }
    }
}