// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ItemClassificacao
    {
        public int IdItemClassificacao { get; set; }
        public int IdTabelaClassificacao { get; set; }
        public int IdClassificacao { get; set; }
        public int? IdGrupoFaixaEtaria { get; set; }
        public int? IdSexo { get; set; }
        public string TxFormulaCondicao { get; set; }

        public virtual TipoDiversos IdClassificacaoNavigation { get; set; }
        public virtual GrupoFaixaEtaria IdGrupoFaixaEtariaNavigation { get; set; }
        public virtual TipoDiversos IdSexoNavigation { get; set; }
        public virtual TabelaClassificacao IdTabelaClassificacaoNavigation { get; set; }
    }
}