// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class JanusInternacao
    {
        public int IdAtendimento { get; set; }
        public DateTime? Dataadmissao { get; set; }
        public string Nomepaciente { get; set; }
        public string Prontuario { get; set; }
        public string Datanascimento { get; set; }
        public string Rua { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Sexo { get; set; }
        public string Cep { get; set; }
        public string Telefone { get; set; }
        public string Nomeconvenio { get; set; }
        public int? Codconvenio { get; set; }
        public string Codunidadeinternacao { get; set; }
        public int? IdUnidadeInternacao { get; set; }
        public int? Codespecialidade { get; set; }
        public string Nomeespecialidade { get; set; }
        public string Nomeunidade { get; set; }
        public int? Codunidade { get; set; }
        public string Email { get; set; }
    }
}