// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class JustificativaAcato
    {
        public JustificativaAcato()
        {
            GlosaAcatada = new HashSet<GlosaAcatada>();
            GlosaAcatadaParcial = new HashSet<GlosaAcatadaParcial>();
            GlosaGenericaAcatada = new HashSet<GlosaGenericaAcatada>();
        }

        public int IdJustificativaAcato { get; set; }
        public string TxJustificativaAcato { get; set; }
        public bool? InAtivo { get; set; }

        public virtual ICollection<GlosaAcatada> GlosaAcatada { get; set; }
        public virtual ICollection<GlosaAcatadaParcial> GlosaAcatadaParcial { get; set; }
        public virtual ICollection<GlosaGenericaAcatada> GlosaGenericaAcatada { get; set; }
    }
}