// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class JustificativaGlosaFiComplementar
    {
        public int IdJustificativaComplementar { get; set; }
        public int? IdConta { get; set; }
        public int? IdFechamentoItem { get; set; }
        public int? IdUsuario { get; set; }
        public DateTime? DtLancamento { get; set; }
        public string IdJustificativaGlosa { get; set; }

        public virtual Glosa Id { get; set; }
        public virtual JustificativaGlosaFi IdJustificativaGlosaNavigation { get; set; }
    }
}