// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class KitLoteProdutoItem
    {
        public int IdKitLoteProdutoItem { get; set; }
        public int IdLoteProdutoItem { get; set; }
        public int? IdLoteProdutoItemCompoe { get; set; }
        public int? IdProdutoDetalhe { get; set; }
        public int? IdFabricante { get; set; }

        public virtual ProdutoDetalheFabricante Id { get; set; }
        public virtual LoteProdutoItem IdLoteProdutoItemCompoeNavigation { get; set; }
        public virtual LoteProdutoItem IdLoteProdutoItemNavigation { get; set; }
    }
}