// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class KitProduto
    {
        public int IdViaAdministracao { get; set; }
        public int IdKit { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public int IdProdutoDetalhe { get; set; }

        public virtual ProdutoDetalheViaAdministracao Id { get; set; }
        public virtual Kit IdKitNavigation { get; set; }
    }
}