// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Laboratoriopedidoresultadohistorico
    {
        public int IdLaboratorioPedidoResultadoHistorico { get; set; }
        public DateTime DtLaboratorioPedidoResultadoHistorico { get; set; }
        public int IdLaboratorioPedidoResultado { get; set; }
        public int IdLaboratorioPedidoItem { get; set; }
        public int? IdUsuarioDigitou { get; set; }
        public int? IdUsuarioLiberou { get; set; }
        public int? IdUsuarioRetificou { get; set; }
        public bool InResultadoCritico { get; set; }
        public bool InSucessoComunicacao { get; set; }
        public bool InResultadoRetificado { get; set; }
        public string TxObservacao { get; set; }
        public int IdMetodo { get; set; }
        public int? IdEquipamento { get; set; }
        public DateTime DtDigitacao { get; set; }
        public DateTime? DtLiberacao { get; set; }
        public bool InAtivo { get; set; }
        public int? IdExameMaterial { get; set; }
        public bool InResultadoAutomatico { get; set; }
        public string TxMetodo { get; set; }
        public string TxHash { get; set; }
    }
}