// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LaboratorioPedidoColetaRestricaoAmostra
    {
        public int IdLaboratorioPedidoColeta { get; set; }
        public int IdRestricaoAmostra { get; set; }

        public virtual LaboratorioPedidoColeta IdLaboratorioPedidoColetaNavigation { get; set; }
        public virtual TipoDiversos IdRestricaoAmostraNavigation { get; set; }
    }
}