// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LaboratorioPedidoResultadoAntibiotico
    {
        /// <summary>
        /// identificador do resultado do exame
        /// </summary>
        public int IdLaboratorioPedidoResultado { get; set; }
        /// <summary>
        /// identificador do germe do resultado, tipo tabela 232
        /// </summary>
        public int IdGerme { get; set; }
        /// <summary>
        /// identificador do antibiotico, tipo tabela 233
        /// </summary>
        public int IdAntibiotico { get; set; }
        /// <summary>
        /// valor do resultado, s - sensível, i - intermediario, r- resistente, - - não testado
        /// </summary>
        public string TxResistente { get; set; }

        public virtual TipoDiversos IdAntibioticoNavigation { get; set; }
        public virtual TipoDiversos IdGermeNavigation { get; set; }
        public virtual LaboratorioPedidoResultado IdLaboratorioPedidoResultadoNavigation { get; set; }
    }
}