// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LaboratorioPedidoItem
    {
        public LaboratorioPedidoItem()
        {
            LaboratorioPedidoColeta = new HashSet<LaboratorioPedidoColeta>();
            LaboratorioPedidoColetaEnfermagem = new HashSet<LaboratorioPedidoColetaEnfermagem>();
            LaboratorioPedidoColetaItem = new HashSet<LaboratorioPedidoColetaItem>();
            LaboratorioPedidoItemHistorico = new HashSet<LaboratorioPedidoItemHistorico>();
            LaboratorioPedidoItemInterfaceamentoHistorico = new HashSet<LaboratorioPedidoItemInterfaceamentoHistorico>();
            LaboratorioPedidoItemObservacao = new HashSet<LaboratorioPedidoItemObservacao>();
            LaboratorioPedidoLaudo = new HashSet<LaboratorioPedidoLaudo>();
            LaboratorioPedidoResultado = new HashSet<LaboratorioPedidoResultado>();
            Laboratoriopedidoitemhistoricoamostra = new HashSet<Laboratoriopedidoitemhistoricoamostra>();
            LaudoLaboratorioIntegracaoConnect = new HashSet<LaudoLaboratorioIntegracaoConnect>();
        }

        /// <summary>
        /// identificador único para o exame no pedido
        /// </summary>
        public int IdLaboratorioPedidoItem { get; set; }
        /// <summary>
        /// identificador do pedido
        /// </summary>
        public int IdLaboratorioPedido { get; set; }
        /// <summary>
        /// identificador do exame
        /// </summary>
        public int IdExame { get; set; }
        /// <summary>
        /// identificador do material que será utilizado, tipo tabela 123
        /// </summary>
        public int IdMaterial { get; set; }
        /// <summary>
        /// quando o material é diversos, o médico escreve o material que será coletado
        /// </summary>
        public string TxMaterial { get; set; }
        /// <summary>
        /// número da amostra
        /// </summary>
        public int NrAmostra { get; set; }
        /// <summary>
        /// intervalo de tempo entre amostras
        /// </summary>
        public int? NrIntervalo { get; set; }
        /// <summary>
        /// unidade de tempo entre amostras
        /// </summary>
        public int? IdUnidadeTempo { get; set; }
        /// <summary>
        /// status do exame no pedido
        /// </summary>
        public int IdStatusItem { get; set; }
        /// <summary>
        /// exclusão lógica
        /// </summary>
        public bool? InAtivo { get; set; }
        public bool InGerouArquivo { get; set; }
        public string TxCodigoAmostra { get; set; }
        /// <summary>
        /// se o item foi enviado em lote para laboratório de apoio
        /// </summary>
        public int? IdLaboratorioLote { get; set; }
        public bool InGerouAutomate { get; set; }
        public DateTime? DtPrazoLiberacao { get; set; }
        public bool? InAmostraApoio { get; set; }

        public virtual Exame IdExameNavigation { get; set; }
        public virtual LaboratorioPedido IdLaboratorioPedidoNavigation { get; set; }
        public virtual TipoDiversos IdMaterialNavigation { get; set; }
        public virtual TipoDiversos IdStatusItemNavigation { get; set; }
        public virtual TipoDiversos IdUnidadeTempoNavigation { get; set; }
        public virtual ICollection<LaboratorioPedidoColeta> LaboratorioPedidoColeta { get; set; }
        public virtual ICollection<LaboratorioPedidoColetaEnfermagem> LaboratorioPedidoColetaEnfermagem { get; set; }
        public virtual ICollection<LaboratorioPedidoColetaItem> LaboratorioPedidoColetaItem { get; set; }
        public virtual ICollection<LaboratorioPedidoItemHistorico> LaboratorioPedidoItemHistorico { get; set; }
        public virtual ICollection<LaboratorioPedidoItemInterfaceamentoHistorico> LaboratorioPedidoItemInterfaceamentoHistorico { get; set; }
        public virtual ICollection<LaboratorioPedidoItemObservacao> LaboratorioPedidoItemObservacao { get; set; }
        public virtual ICollection<LaboratorioPedidoLaudo> LaboratorioPedidoLaudo { get; set; }
        public virtual ICollection<LaboratorioPedidoResultado> LaboratorioPedidoResultado { get; set; }
        public virtual ICollection<Laboratoriopedidoitemhistoricoamostra> Laboratoriopedidoitemhistoricoamostra { get; set; }
        public virtual ICollection<LaudoLaboratorioIntegracaoConnect> LaudoLaboratorioIntegracaoConnect { get; set; }
    }
}