// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LaboratorioPedidoResultadoItem
    {
        /// <summary>
        /// identificador único de cada ítem do resultado
        /// </summary>
        public int IdLaboratorioPedidoResultadoItem { get; set; }
        /// <summary>
        /// identificador do resultado
        /// </summary>
        public int IdLaboratorioPedidoResultado { get; set; }
        /// <summary>
        /// identificador do item do exame
        /// </summary>
        public int IdExameItemMaterial { get; set; }
        /// <summary>
        /// armazena o valor de referência no momento que foi lançado o resultado
        /// </summary>
        public string TxValorReferencia { get; set; }
        /// <summary>
        /// valor do resultado
        /// </summary>
        public string TxValor { get; set; }
        /// <summary>
        /// exclusão lógica
        /// </summary>
        public bool? InAtivo { get; set; }
        public bool InForaRange { get; set; }
        public bool InForaRangeVermelho { get; set; }
        public bool? InRetificado { get; set; }
        public byte[] AdImagem { get; set; }

        public virtual ExameItemMaterial IdExameItemMaterialNavigation { get; set; }
        public virtual LaboratorioPedidoResultado IdLaboratorioPedidoResultadoNavigation { get; set; }
    }
}