// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LaboratorioPedidoResultadoGermes
    {
        /// <summary>
        /// identificador do resultado
        /// </summary>
        public int IdLaboratorioPedidoResultado { get; set; }
        /// <summary>
        /// identificador do germe lançado no resultado, tipo tabela 232
        /// </summary>
        public int IdGerme { get; set; }
        /// <summary>
        /// ordem que foi lançado o germe, 1,2,3 e 4
        /// </summary>
        public int NrOrdem { get; set; }
        /// <summary>
        /// texto quantitativo de cada germe
        /// </summary>
        public string TxQuantitativo { get; set; }

        public virtual TipoDiversos IdGermeNavigation { get; set; }
        public virtual LaboratorioPedidoResultado IdLaboratorioPedidoResultadoNavigation { get; set; }
    }
}