// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LaboratorioPedidoResultadoRepeticao
    {
        /// <summary>
        /// identificador do resultado
        /// </summary>
        public int IdLaboratorioPedidoResultado { get; set; }
        /// <summary>
        /// motivo da repetição, tipo tabela 222
        /// </summary>
        public int IdMotivoRepeticao { get; set; }
        /// <summary>
        /// quantidade de repetições
        /// </summary>
        public int NrRepeticao { get; set; }

        public virtual LaboratorioPedidoResultado IdLaboratorioPedidoResultadoNavigation { get; set; }
        public virtual TipoDiversos IdMotivoRepeticaoNavigation { get; set; }
    }
}