// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LaboratorioPedidoItemHistorico
    {
        public int IdLaboratorioPedidoItemHistorico { get; set; }
        public int IdLaboratorioPedidoItem { get; set; }
        public int IdStatusPedido { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtExecucao { get; set; }
        public string TxObservacao { get; set; }
        public bool? InAtivo { get; set; }

        public virtual LaboratorioPedidoItem IdLaboratorioPedidoItemNavigation { get; set; }
    }
}