// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LaboratorioUnidadeSolicitante
    {
        /// <summary>
        /// unidade organizacional que pode qualquer exame
        /// </summary>
        public int IdUnidadeOrganizacional { get; set; }
        /// <summary>
        /// ao solicitar o pedido para esta unidade será lançada a prioridade, TIPO TABELA 104
        /// </summary>
        public int IdPrioridadeTipo { get; set; }
        /// <summary>
        /// exclusão lógica
        /// </summary>
        public bool? InAtivo { get; set; }

        public virtual TipoDiversos IdPrioridadeTipoNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeOrganizacionalNavigation { get; set; }
    }
}