// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LaboratorioPedidoItemContaItem
    {
        /// <summary>
        /// identificador do item do pedido
        /// </summary>
        public int IdLaboratorioPedidoItem { get; set; }
        /// <summary>
        /// identificador do item na conta
        /// </summary>
        public int IdContaItem { get; set; }
    }
}