// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LancamentoBancarioComplemento
    {
        public int IdLancamentoBancarioComplemento { get; set; }
        public int IdLancamentoBancario { get; set; }
        public int? IdBanco { get; set; }
        public string NrAgencia { get; set; }
        public string NrConta { get; set; }
        public string NmResponsavel { get; set; }
        public string NrCpfCnpj { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtCadastro { get; set; }
        public bool? InAtivo { get; set; }

        public virtual Pessoa IdBancoNavigation { get; set; }
        public virtual LancamentoBancario IdLancamentoBancarioNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}