// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LeitoEventoLeito
    {
        public LeitoEventoLeito()
        {
            EventoLeitoAssociacaoIdEventoLeitoFilhoNavigation = new HashSet<EventoLeitoAssociacao>();
            EventoLeitoAssociacaoIdEventoLeitoPaiNavigation = new HashSet<EventoLeitoAssociacao>();
        }

        public int IdLeito { get; set; }
        public int IdEvento { get; set; }
        public int IdResponsavel { get; set; }
        public DateTime? DtPrevisaoInicio { get; set; }
        public DateTime? DtPrevisaoLiberacao { get; set; }
        public string TxObservacao { get; set; }
        public bool InInicioLeitoDesocupado { get; set; }
        public DateTime? DtEncerramento { get; set; }
        public DateTime DtRegistro { get; set; }
        public int IdEventoLeito { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public int IdJustPadraoEventoleito { get; set; }
        public int? IdSituacaoLeitoTipo { get; set; }
        public int IdUsuarioAcesso { get; set; }

        public virtual EventoLeito IdEventoNavigation { get; set; }
        public virtual TipoDiversos IdJustPadraoEventoleitoNavigation { get; set; }
        public virtual Leito IdLeitoNavigation { get; set; }
        public virtual Pessoa IdResponsavelNavigation { get; set; }
        public virtual TipoDiversos IdSituacaoLeitoTipoNavigation { get; set; }
        public virtual Usuario IdUsuarioAcessoNavigation { get; set; }
        public virtual ICollection<EventoLeitoAssociacao> EventoLeitoAssociacaoIdEventoLeitoFilhoNavigation { get; set; }
        public virtual ICollection<EventoLeitoAssociacao> EventoLeitoAssociacaoIdEventoLeitoPaiNavigation { get; set; }
    }
}