// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Leito
    {
        public Leito()
        {
            AtendimentoLeito = new HashSet<AtendimentoLeito>();
            AtendimentoServico = new HashSet<AtendimentoServico>();
            CheckinEnfermagem = new HashSet<CheckinEnfermagem>();
            ControleVisitantes = new HashSet<ControleVisitantes>();
            LaboratorioPedido = new HashSet<LaboratorioPedido>();
            LeitoCaracteristica = new HashSet<LeitoCaracteristica>();
            LeitoEventoLeito = new HashSet<LeitoEventoLeito>();
            LeitoReserva = new HashSet<LeitoReserva>();
            LeitoSolicitacaoIdLeitoAtualNavigation = new HashSet<LeitoSolicitacao>();
            LeitoSolicitacaoIdLeitoPropostoNavigation = new HashSet<LeitoSolicitacao>();
            PedidoDeSangueHemoplus = new HashSet<PedidoDeSangueHemoplus>();
            ProcedimentoPedido = new HashSet<ProcedimentoPedido>();
            ReservaLeito = new HashSet<ReservaLeito>();
        }

        public int IdLeito { get; set; }
        public int IdLeitoTipo { get; set; }
        public string NrLeito { get; set; }
        public int IdUnidadeOrganizacional { get; set; }
        public int IdStatusLeito { get; set; }
        public DateTime? DtPrevisaoLiberacao { get; set; }
        public int IdBloco { get; set; }
        public int IdAndar { get; set; }
        public bool? InAtivo { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public int IdUnidadeResponsavelTipo { get; set; }
        public int? IdSexo { get; set; }
        public string NrRamal { get; set; }
        public bool? InVisivel { get; set; }

        public virtual TipoDiversos IdLeitoTipoNavigation { get; set; }
        public virtual TipoDiversos IdSexoNavigation { get; set; }
        public virtual TipoDiversos IdStatusLeitoNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeOrganizacionalNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeResponsavelTipoNavigation { get; set; }
        public virtual ICollection<AtendimentoLeito> AtendimentoLeito { get; set; }
        public virtual ICollection<AtendimentoServico> AtendimentoServico { get; set; }
        public virtual ICollection<CheckinEnfermagem> CheckinEnfermagem { get; set; }
        public virtual ICollection<ControleVisitantes> ControleVisitantes { get; set; }
        public virtual ICollection<LaboratorioPedido> LaboratorioPedido { get; set; }
        public virtual ICollection<LeitoCaracteristica> LeitoCaracteristica { get; set; }
        public virtual ICollection<LeitoEventoLeito> LeitoEventoLeito { get; set; }
        public virtual ICollection<LeitoReserva> LeitoReserva { get; set; }
        public virtual ICollection<LeitoSolicitacao> LeitoSolicitacaoIdLeitoAtualNavigation { get; set; }
        public virtual ICollection<LeitoSolicitacao> LeitoSolicitacaoIdLeitoPropostoNavigation { get; set; }
        public virtual ICollection<PedidoDeSangueHemoplus> PedidoDeSangueHemoplus { get; set; }
        public virtual ICollection<ProcedimentoPedido> ProcedimentoPedido { get; set; }
        public virtual ICollection<ReservaLeito> ReservaLeito { get; set; }
    }
}