// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LeitoCnesAcomodacao
    {
        public int IdLeitoCnesAcomodacao { get; set; }
        public int IdLeitoCnes { get; set; }
        public int IdAcomodacao { get; set; }
        public int? IdUnidadeOrganizacional { get; set; }
        public bool? InAtivo { get; set; }
        public int IdUsuarioCadastro { get; set; }
        public DateTime DtCadastro { get; set; }
        public int? IdUsuarioExclusao { get; set; }
        public DateTime? DtExclusao { get; set; }

        public virtual TipoDiversos IdAcomodacaoNavigation { get; set; }
        public virtual LeitoSusCnes IdLeitoCnesNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeOrganizacionalNavigation { get; set; }
    }
}