// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LgpdLog
    {
        public int IdLgpdLog { get; set; }
        public int IdSessao { get; set; }
        public int IdPagina { get; set; }
        public int IdTipoChave { get; set; }
        public string TxValorLog { get; set; }
        public string NmArquivoXml { get; set; }
        public DateTime DtLog { get; set; }
        public DateTime DtRegistro { get; set; }
        public int? IdAtendimento { get; set; }

        public virtual Atendimento IdAtendimentoNavigation { get; set; }
        public virtual Pagina IdPaginaNavigation { get; set; }
        public virtual Sessao IdSessaoNavigation { get; set; }
        public virtual TipoDiversos IdTipoChaveNavigation { get; set; }
    }
}