// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LinhaRetornoUnimedItemAdequacao
    {
        public int IdArquivoUnimed { get; set; }
        public int NrOrdemLinha { get; set; }
        public int NrOrdemLinhaPai { get; set; }
        public int? IdConta { get; set; }
        public int? IdFechamentoItem { get; set; }
        public int? IdTipoItem { get; set; }
        public string CdItem { get; set; }
        public decimal? QdPaga { get; set; }
        public decimal? VlPago { get; set; }
        public decimal? VlUt { get; set; }
        public string TxMesanoCompetencia { get; set; }
        public decimal? VlPagoAnterior { get; set; }
        public string TxMesanoPgAnterior { get; set; }
        public byte? PrPagamento { get; set; }
        public decimal? VlSeriaPago { get; set; }
        public decimal? QdUt { get; set; }

        public virtual LinhaRetornoUnimed LinhaRetornoUnimed { get; set; }
        public virtual LinhaRetornoUnimedItem LinhaRetornoUnimedItem { get; set; }
    }
}