// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LogErroLoteConta
    {
        public long IdLogErroLoteConta { get; set; }
        public int? IdLote { get; set; }
        public int? IdConta { get; set; }
        public bool? InErroTratado { get; set; }
        public string CdServico { get; set; }
        public string TxDescricaoServico { get; set; }
        public string TxDescricaoErro { get; set; }
    }
}