// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LogFaixaLocalidade
    {
        public int LocNu { get; set; }
        public string LocCepIni { get; set; }
        public string LocCepFim { get; set; }
        public int LocNuEct { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual LogLocalidade LocNuNavigation { get; set; }
    }
}