// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LogLogradouro
    {
        public LogLogradouro()
        {
            ContaPagarDes = new HashSet<ContaPagarDes>();
            Endereco = new HashSet<Endereco>();
            LogGrandeUsuario = new HashSet<LogGrandeUsuario>();
            LogVarLog = new HashSet<LogVarLog>();
        }

        public int LogNu { get; set; }
        public int LocNu { get; set; }
        public int IdOrigemCadastroTipo { get; set; }
        public int IdLogradouroTipo { get; set; }
        public string LogNo { get; set; }
        public string Cep { get; set; }
        public int BaiNuIni { get; set; }
        public int? BaiNuFim { get; set; }
        public string LogComplemento { get; set; }
        public string LogStaTlo { get; set; }
        public int? LogNuEct { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public bool? InAtivo { get; set; }

        public virtual TipoDiversos IdLogradouroTipoNavigation { get; set; }
        public virtual TipoDiversos IdOrigemCadastroTipoNavigation { get; set; }
        public virtual LogLocalidade LocNuNavigation { get; set; }
        public virtual LogNumSec LogNumSec { get; set; }
        public virtual ICollection<ContaPagarDes> ContaPagarDes { get; set; }
        public virtual ICollection<Endereco> Endereco { get; set; }
        public virtual ICollection<LogGrandeUsuario> LogGrandeUsuario { get; set; }
        public virtual ICollection<LogVarLog> LogVarLog { get; set; }
    }
}