// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LogLocalidade
    {
        public LogLocalidade()
        {
            AtendimentoComplemento = new HashSet<AtendimentoComplemento>();
            ContaPagarDes = new HashSet<ContaPagarDes>();
            Feriado = new HashSet<Feriado>();
            LogBairro = new HashSet<LogBairro>();
            LogCpc = new HashSet<LogCpc>();
            LogFaixaLocalidade = new HashSet<LogFaixaLocalidade>();
            LogGrandeUsuario = new HashSet<LogGrandeUsuario>();
            LogLogradouro = new HashSet<LogLogradouro>();
            LogVarLoc = new HashSet<LogVarLoc>();
            PessoaEndereco = new HashSet<PessoaEndereco>();
            UnidadeOrganizacionalEndereco = new HashSet<UnidadeOrganizacionalEndereco>();
        }

        public int LocNu { get; set; }
        public string LocNo { get; set; }
        public string Cep { get; set; }
        public string LocInSit { get; set; }
        public string LocInTipoLoc { get; set; }
        public int? LocNuSub { get; set; }
        public int? LocNuEct { get; set; }
        public int IdUf { get; set; }
        public int IdOrigemCadastroTipo { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public bool? InAtivo { get; set; }
        public string CdIbge { get; set; }
        public int? NrPopulacao { get; set; }
        public int? IdMicrorregiao { get; set; }
        public int? IdRegional { get; set; }

        public virtual TipoDiversos IdMicrorregiaoNavigation { get; set; }
        public virtual TipoDiversos IdRegionalNavigation { get; set; }
        public virtual Uf IdUfNavigation { get; set; }
        public virtual ICollection<AtendimentoComplemento> AtendimentoComplemento { get; set; }
        public virtual ICollection<ContaPagarDes> ContaPagarDes { get; set; }
        public virtual ICollection<Feriado> Feriado { get; set; }
        public virtual ICollection<LogBairro> LogBairro { get; set; }
        public virtual ICollection<LogCpc> LogCpc { get; set; }
        public virtual ICollection<LogFaixaLocalidade> LogFaixaLocalidade { get; set; }
        public virtual ICollection<LogGrandeUsuario> LogGrandeUsuario { get; set; }
        public virtual ICollection<LogLogradouro> LogLogradouro { get; set; }
        public virtual ICollection<LogVarLoc> LogVarLoc { get; set; }
        public virtual ICollection<PessoaEndereco> PessoaEndereco { get; set; }
        public virtual ICollection<UnidadeOrganizacionalEndereco> UnidadeOrganizacionalEndereco { get; set; }
    }
}