// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LogNumSec
    {
        public int LogNu { get; set; }
        public string SecNuIni { get; set; }
        public string SecNuFim { get; set; }
        public string SecInLado { get; set; }
        public int LogNuEct { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual LogLogradouro LogNuNavigation { get; set; }
    }
}