// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LogradourosTipo
    {
        public int Tlg { get; set; }
        /// <summary>
        /// SQL_Latin1_General_CP1_CI_AS
        /// </summary>
        public string Descricao { get; set; }
        /// <summary>
        /// SQL_Latin1_General_CP1_CI_AS
        /// </summary>
        public string Abr { get; set; }
    }
}