// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LogSmsenviadoPaciente
    {
        public int IdLogSmsEnviado { get; set; }
        public DateTime DtLogSmsEnviado { get; set; }
        public string DesDestinatario { get; set; }
        public string DesTelefone { get; set; }
        public string DesSms { get; set; }
        public string DesRetornoWs { get; set; }
        public int IdAgenda { get; set; }
    }
}