// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LogVarBai
    {
        public int BaiNu { get; set; }
        public int VdbNu { get; set; }
        public string VdbTx { get; set; }
        public int BaiNuEct { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual LogBairro BaiNuNavigation { get; set; }
    }
}