// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LoteProdutoItemImpressao
    {
        public int IdLoteProdutoItemImpressao { get; set; }
        public int? IdLoteProdutoItem { get; set; }
        public DateTime? DtImpressao { get; set; }
        public int? IdUsuario { get; set; }
        public string TxJustificativa { get; set; }
    }
}