// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LoteConta
    {
        public LoteConta()
        {
            CartaRecursoParcelaContaReceber = new HashSet<CartaRecursoParcelaContaReceber>();
            Conta = new HashSet<Conta>();
            ContaDtLiberacaoTab = new HashSet<ContaDtLiberacaoTab>();
            ContaReceber = new HashSet<ContaReceber>();
            ContaSelNota = new HashSet<ContaSelNota>();
        }

        public int IdLote { get; set; }
        public int IdOperadora { get; set; }
        public DateTime DtGeracaoLote { get; set; }
        public DateTime? DtEnvioLote { get; set; }
        public DateTime? DtVencimentoLote { get; set; }
        public bool InExterno { get; set; }
        public int? NrCartaRemessa { get; set; }
        public int? NrProtocolo { get; set; }
        public DateTime? DtEmissaoProtocolo { get; set; }
        public double? VlTotalLote { get; set; }
        public string TxObservacao { get; set; }
        public int? IdLoteContaMapa { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public int IdLoteContaStatusTipo { get; set; }
        public int? IdLoteContaSusTipo { get; set; }
        public string TxNomeArquivoSus { get; set; }
        public int? NrTotalRegistrosSus { get; set; }
        public int? NrTotalProducao { get; set; }
        public int? NrCampoControle { get; set; }
        public int? NrInicioFolhaBpac { get; set; }
        public int? NrInicioFolhaBpai { get; set; }
        public DateTime? DtInicial { get; set; }
        public DateTime? DtFinal { get; set; }
        public bool? InRejeitada { get; set; }
        public int? IdLoteContaConvenioTipo { get; set; }
        public int QnContasProcessadas { get; set; }
        public string CdConvenio { get; set; }
        public string CdCnpjOrigem { get; set; }

        public virtual TipoDiversos IdLoteContaConvenioTipoNavigation { get; set; }
        public virtual LoteContaMapa IdLoteContaMapaNavigation { get; set; }
        public virtual TipoDiversos IdLoteContaStatusTipoNavigation { get; set; }
        public virtual TipoDiversos IdLoteContaSusTipoNavigation { get; set; }
        public virtual LoteCobranca LoteCobranca { get; set; }
        public virtual LoteContaComplemento LoteContaComplemento { get; set; }
        public virtual ICollection<CartaRecursoParcelaContaReceber> CartaRecursoParcelaContaReceber { get; set; }
        public virtual ICollection<Conta> Conta { get; set; }
        public virtual ICollection<ContaDtLiberacaoTab> ContaDtLiberacaoTab { get; set; }
        public virtual ICollection<ContaReceber> ContaReceber { get; set; }
        public virtual ICollection<ContaSelNota> ContaSelNota { get; set; }
    }
}