// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LoteContaMapa
    {
        public LoteContaMapa()
        {
            AnaliseCritica = new HashSet<AnaliseCritica>();
            ContaDtLiberacaoTab = new HashSet<ContaDtLiberacaoTab>();
            LoteConta = new HashSet<LoteConta>();
            OperadoraRecebimento = new HashSet<OperadoraRecebimento>();
            RepasseMedicoPrevia = new HashSet<RepasseMedicoPrevia>();
        }

        public int IdLoteContaMapa { get; set; }
        public int MesMapa { get; set; }
        public int AnoMapa { get; set; }
        public DateTime? DtEmissao { get; set; }
        public int IdUsuarioResponsavel { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public bool? InAberto { get; set; }
        public DateTime? DtFechamento { get; set; }

        public virtual ICollection<AnaliseCritica> AnaliseCritica { get; set; }
        public virtual ICollection<ContaDtLiberacaoTab> ContaDtLiberacaoTab { get; set; }
        public virtual ICollection<LoteConta> LoteConta { get; set; }
        public virtual ICollection<OperadoraRecebimento> OperadoraRecebimento { get; set; }
        public virtual ICollection<RepasseMedicoPrevia> RepasseMedicoPrevia { get; set; }
    }
}