// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LotePrescricaoRegistroInteracao
    {
        public int IdLoteprescricaoregistrointeracao { get; set; }
        public int IdLotePrescricaoItem { get; set; }
        public int IdInteracaoMedicamentosa { get; set; }
        public int? IdUsuarioConcordante { get; set; }
        public int? NrLotePrescricaoConcordancia { get; set; }

        public virtual InteracaoMedicamentosa IdInteracaoMedicamentosaNavigation { get; set; }
        public virtual LotePrescricao IdLotePrescricaoItemNavigation { get; set; }
        public virtual Usuario IdUsuarioConcordanteNavigation { get; set; }
    }
}