// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LotePrescricaoRegistroAlergiaPrincipioAtivo
    {
        public int IdLoteprescricaoregistroalergiaprincipioativo { get; set; }
        public int IdLotePrescricaoItem { get; set; }
        public int IdPrincipioAtivo { get; set; }
        public int? IdUsuarioConcordante { get; set; }
        public int? NrLotePrescricaoConcordancia { get; set; }

        public virtual LotePrescricao IdLotePrescricaoItemNavigation { get; set; }
        public virtual TipoDiversos IdPrincipioAtivoNavigation { get; set; }
        public virtual Usuario IdUsuarioConcordanteNavigation { get; set; }
    }
}