// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class LoteCobranca
    {
        public int IdLote { get; set; }
        public double? VlGlosa { get; set; }
        public double? VlAcrescimo { get; set; }
        public double? VlFi { get; set; }
        public double? VlRecursado { get; set; }
        public double? VlRevertido { get; set; }
        public double? VlCobrado { get; set; }
        public double? VlRecebido { get; set; }
        public double? VlPendente { get; set; }
        public double? VlGlosaGenerica { get; set; }
        public DateTime? DtCobrancaPreventiva { get; set; }
        public DateTime? DtPrometida { get; set; }
        public double? VlPrometido { get; set; }
        public string TxObsCp { get; set; }
        public DateTime? DtCredito { get; set; }
        public double? VlCredito { get; set; }
        public int? IdSituacaoLote { get; set; }
        public int? IdUsuario { get; set; }
        public double? VlAcrescimoGenerico { get; set; }
        public string TxAnaliseCritica { get; set; }
        public int? IdUsuarioAnaliseCritica { get; set; }
        public DateTime? DtLiberacao { get; set; }
        public decimal VlTotalFiContaLimpa { get; set; }
        public decimal VlTotalGlosasContaLimpa { get; set; }

        public virtual LoteConta IdLoteNavigation { get; set; }
        public virtual SituacaoLote IdSituacaoLoteNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}