// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class MconnectOcorrencias
    {
        public string Instrumento { get; set; }
        public int Sequencia { get; set; }
        public string TipoLog { get; set; }
        public string Descricao { get; set; }
        public string DataOcorrencia { get; set; }
        public string HoraOcorrencia { get; set; }
        public string Amostra { get; set; }
        public string Usuario { get; set; }
        public string Porta { get; set; }
        public string Detalhes { get; set; }
        public string DataExportacao { get; set; }
        public string HoraExportacao { get; set; }

        public virtual MconnectAmostra AmostraNavigation { get; set; }
    }
}