// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class MconnectExame
    {
        public MconnectExame()
        {
            MconnectFlag = new HashSet<MconnectFlag>();
            MconnectResultado = new HashSet<MconnectResultado>();
        }

        public string Amostra { get; set; }
        public string Exame { get; set; }
        public int SequenciaRepeticao { get; set; }
        public string DataResultado { get; set; }
        public string HoraResultado { get; set; }
        public string DataLiberacao { get; set; }
        public string HoraLiberacao { get; set; }
        public string Operador { get; set; }

        public virtual MconnectAmostra AmostraNavigation { get; set; }
        public virtual ICollection<MconnectFlag> MconnectFlag { get; set; }
        public virtual ICollection<MconnectResultado> MconnectResultado { get; set; }
    }
}