// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class MensagemUsuario
    {
        public int IdMensagem { get; set; }
        public int IdUsuarioLeitor { get; set; }
        public DateTime? DtLeitura { get; set; }
        public int? IdTipoResposta { get; set; }
        public bool InLida { get; set; }

        public virtual Mensagem IdMensagemNavigation { get; set; }
        public virtual TipoDiversos IdTipoRespostaNavigation { get; set; }
        public virtual Usuario IdUsuarioLeitorNavigation { get; set; }
    }
}