// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class MensagemTipoPerfil
    {
        public int IdTipoMensagem { get; set; }
        public int IdPerfil { get; set; }

        public virtual Perfil IdPerfilNavigation { get; set; }
        public virtual MensagemTipo IdTipoMensagemNavigation { get; set; }
    }
}