// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class MensagemPerfilBackup
    {
        public int IdMensagem { get; set; }
        public int IdPerfil { get; set; }
    }
}