// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class MlisAmostra
    {
        public MlisAmostra()
        {
            MlisAtributo = new HashSet<MlisAtributo>();
            MlisExame = new HashSet<MlisExame>();
        }

        public string Amostra { get; set; }
        public string Diluicao { get; set; }
        public string Agrupamento { get; set; }
        public string Prioridade { get; set; }
        public string Material { get; set; }
        public string Instrumento { get; set; }
        public string Registro { get; set; }
        public string Origem { get; set; }
        public string DataColeta { get; set; }
        public string HoraColeta { get; set; }

        public virtual MlisPaciente RegistroNavigation { get; set; }
        public virtual ICollection<MlisAtributo> MlisAtributo { get; set; }
        public virtual ICollection<MlisExame> MlisExame { get; set; }
    }
}