// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Modulo
    {
        public Modulo()
        {
            Aplicativo = new HashSet<Aplicativo>();
        }

        /// <summary>
        /// Identificador unico do modulo
        /// </summary>
        public int IdModulo { get; set; }
        /// <summary>
        /// Nome do modulo
        /// </summary>
        public string NmModulo { get; set; }

        public virtual ICollection<Aplicativo> Aplicativo { get; set; }
    }
}