// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class NotaFiscalEletronicaRetorno
    {
        public int IdNotaFiscalEletronicaRetorno { get; set; }
        public int IdNotaFiscalEletronica { get; set; }
        public string TxDados { get; set; }
        public DateTime DtRetorno { get; set; }
        public string CdMensagemAlerta { get; set; }
        public string TxDescricaoMensagemAlerta { get; set; }
        public string CdCancelamentoNota { get; set; }
    }
}