// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class NotaEmitidaImposto
    {
        public int IdNotaEmitidaImposto { get; set; }
        public int? IdNotaEmitida { get; set; }
        public int? IdImpostoIss { get; set; }
        public int? IdImpostoIr { get; set; }
        public float? VlIss { get; set; }
        public float? VlPis { get; set; }
        public float? VlCofins { get; set; }
        public float? VlCsll { get; set; }
        public float? VlIr { get; set; }
        public string TxDiscriminacao { get; set; }
        public float? VlTotalRetido { get; set; }
    }
}