// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class NotaExcluidaProdutoDetalhe
    {
        public int? IdNotaEntradaProdutoDetalhe { get; set; }
        public int IdNotaEntrada { get; set; }
        public int IdProdutoDetalhe { get; set; }
        public int IdFabricante { get; set; }
        public int QnProduto { get; set; }
        public int IdEmbalagem { get; set; }
        public decimal VlUnitario { get; set; }
        public decimal? VlDesconto { get; set; }
        public decimal? VlFrete { get; set; }
        public decimal VlTotal { get; set; }
        public decimal? VlIcms { get; set; }
        public decimal? VlIpi { get; set; }
        public bool InItemAntecipado { get; set; }
        public string NrLote { get; set; }
        public DateTime? DtValidade { get; set; }
        public bool? InProdutoEtiquetado { get; set; }
        public decimal? PrIcms { get; set; }
        public decimal? PrIpi { get; set; }
        public decimal? PrDesconto { get; set; }
        public decimal? VlIcmsSubstituicaoTributaria { get; set; }
        public decimal? PrIcmsSubstituicaoTributaria { get; set; }
        public bool? InLoteDesmembrado { get; set; }
    }
}