// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class NotaEmitidaTemporaria
    {
        public int IdNotaEmitida { get; set; }
        public int NrNotaFiscal { get; set; }
        public string TxSerie { get; set; }
        public int? IdCliente { get; set; }
        public DateTime? DtEmissao { get; set; }
        public int? IdSituacao { get; set; }
        public decimal? VlNotaEmitida { get; set; }
        public decimal? VlIss { get; set; }
        public int? IdUsuarioEmitiu { get; set; }
        public int? IdUsuarioCancelou { get; set; }
        public string TxJustificativaCancelamento { get; set; }
        public DateTime? DtCancelamento { get; set; }
        public decimal? VlDesconto { get; set; }
        public decimal? PrDesconto { get; set; }
        public string TxPessoaAutorizouDesconto { get; set; }
        public string NmResponsavel { get; set; }
        public string NrCnpjResponsavel { get; set; }
        public decimal? PrAliquota { get; set; }
    }
}