// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class NotificacaoPendencia
    {
        public int IdNotificacaoPendencia { get; set; }
        public int IdPendencia { get; set; }
        public string XmlNotificacao { get; set; }

        public virtual Pendencia IdPendenciaNavigation { get; set; }
    }
}