// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class OcupacaoAgrupamento
    {
        public int IdOcupacao { get; set; }
        public int IdOcupacaoAgrupado { get; set; }
        public bool InAtivo { get; set; }
    }
}