// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class OperadoraEmpresaPagante
    {
        public OperadoraEmpresaPagante()
        {
            NotaEmitidaComplemento = new HashSet<NotaEmitidaComplemento>();
        }

        public int IdEmpresaPagante { get; set; }
        public int IdOperadora { get; set; }
        public string TxRazaoSocial { get; set; }
        public string TxEndereco { get; set; }
        public string TxCnpj { get; set; }
        public string TxTelefone { get; set; }
        public string TxContato { get; set; }
        public string TxObservacoes { get; set; }

        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual ICollection<NotaEmitidaComplemento> NotaEmitidaComplemento { get; set; }
    }
}