// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class OperadoraHistorico
    {
        public int IdOperadora { get; set; }
        public int IdOperadoraOcorrenciaTipo { get; set; }
        public DateTime DtOcorrencia { get; set; }
        public int IdOperadoraJustificativaTipo { get; set; }
        public string TxObservacao { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public bool InAtual { get; set; }

        public virtual TipoDiversos IdOperadoraJustificativaTipoNavigation { get; set; }
        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual TipoDiversos IdOperadoraOcorrenciaTipoNavigation { get; set; }
    }
}