// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Operador
    {
        public Operador()
        {
            OperadorAtributoTipo = new HashSet<OperadorAtributoTipo>();
            RestricaoKit = new HashSet<RestricaoKit>();
            RestricaoProdutoDetalhe = new HashSet<RestricaoProdutoDetalhe>();
            RestricaoServico = new HashSet<RestricaoServico>();
        }

        public int IdOperador { get; set; }
        public string NmOperador { get; set; }
        public string TxSimbolo { get; set; }
        public int? QtValores { get; set; }
        public bool InAtivo { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual ICollection<OperadorAtributoTipo> OperadorAtributoTipo { get; set; }
        public virtual ICollection<RestricaoKit> RestricaoKit { get; set; }
        public virtual ICollection<RestricaoProdutoDetalhe> RestricaoProdutoDetalhe { get; set; }
        public virtual ICollection<RestricaoServico> RestricaoServico { get; set; }
    }
}