// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class OperadoraUnidadeOrganizacionalCredenciada
    {
        public OperadoraUnidadeOrganizacionalCredenciada()
        {
            OperadoraUnidadeOrganizacionalChHistorico = new HashSet<OperadoraUnidadeOrganizacionalChHistorico>();
            OperadoraUnidadeOrganizacionalHistorico = new HashSet<OperadoraUnidadeOrganizacionalHistorico>();
            TaxaAcrescimoHistorico = new HashSet<TaxaAcrescimoHistorico>();
        }

        public int IdOperadora { get; set; }
        public int IdUnidadeOrganizacional { get; set; }
        public int IdStatus { get; set; }
        public double? VlTaxaAcrescimoServico { get; set; }
        public double? VlTaxaAcrescimoHonorario { get; set; }
        public double? VlCh { get; set; }
        public double? VlChExterno { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public string TxInstrucaoAtendimento { get; set; }
        public bool InEnvioAutomaticoContaLote { get; set; }
        public int? IdTipoRepasse { get; set; }

        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual TipoDiversos IdTipoRepasseNavigation { get; set; }
        public virtual ICollection<OperadoraUnidadeOrganizacionalChHistorico> OperadoraUnidadeOrganizacionalChHistorico { get; set; }
        public virtual ICollection<OperadoraUnidadeOrganizacionalHistorico> OperadoraUnidadeOrganizacionalHistorico { get; set; }
        public virtual ICollection<TaxaAcrescimoHistorico> TaxaAcrescimoHistorico { get; set; }
    }
}