// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class OperadoraEspecialidadeHistorico
    {
        public int IdOperadora { get; set; }
        public int IdEspecialidade { get; set; }
        public DateTime DtHistorico { get; set; }
        public int IdHistorico { get; set; }

        public virtual OperadoraEspecialidade Id { get; set; }
    }
}