// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Operadora
    {
        public int IdOperadora { get; set; }
        public string NmOperadora { get; set; }
        public bool InAtivo { get; set; }
        public string CdRegistroAns { get; set; }
        public string IdOperadoraTipo { get; set; }
        public string IdOperadoraGrupoTipo { get; set; }
        public string TxSite { get; set; }
        public string TxRazaoSocial { get; set; }
        public string CdCnpj { get; set; }
        public string CdInscricaoEstadual { get; set; }
        public string CdInscricaoMunicipal { get; set; }
        public string DtInicioAtividade { get; set; }
        public string IdEmpresaTipo { get; set; }
        public string IdFonteRemuneracao { get; set; }
        public string InAtivada { get; set; }
        public string InPadrao { get; set; }
        public string QnBeneficiario { get; set; }
        public string CdConvenioHmt { get; set; }
        public string InPessoaTipo { get; set; }
    }
}