// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class OperadoraRecebimentoRetornoArquivo
    {
        public int IdOperadorarecebimentoretornoarquivo { get; set; }
        public int IdOperadorarecebimento { get; set; }
        public int IdRetornoArquivo { get; set; }

        public virtual OperadoraRecebimento IdOperadorarecebimentoNavigation { get; set; }
        public virtual RetornoArquivo IdRetornoArquivoNavigation { get; set; }
    }
}