// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class OperadoraCodigoHospital
    {
        public int IdOperadoraCodigohospital { get; set; }
        public int IdOperadora { get; set; }
        public string TxDescricao { get; set; }
        public string CdHospitalOperadora { get; set; }
        public bool InPrincipal { get; set; }

        public virtual Pessoa IdOperadoraNavigation { get; set; }
    }
}