// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class OrdemServicoCaracteristica
    {
        public int IdAtributo { get; set; }
        public int IdOrdemServico { get; set; }
        public string VlAtibuto { get; set; }

        public virtual Atributo IdAtributoNavigation { get; set; }
        public virtual OrdemServico IdOrdemServicoNavigation { get; set; }
    }
}