// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PacientePlanoConta
    {
        public string NmPaciente { get; set; }
        public int IdConta { get; set; }
        public bool InExterno { get; set; }
        public DateTime? DtFechamento { get; set; }
        public bool InParticular { get; set; }
        public int? IdLote { get; set; }
        public int? IdPlano { get; set; }
        public int IdAtendimento { get; set; }
        public DateTime? DtAtendimento { get; set; }
        public int IdPaciente { get; set; }
    }
}