// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PacoteFaturamento
    {
        public int IdServico { get; set; }
        public int IdOperadora { get; set; }
        public double VlPacote { get; set; }

        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual Servico IdServicoNavigation { get; set; }
    }
}