// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ParametrizacaoSistema
    {
        public int IdParametro { get; set; }
        public int? IdAplicativo { get; set; }
        public int IdTipoParametro { get; set; }
        public string NmParametro { get; set; }
        public string VlParametro { get; set; }
        public string TxExibicao { get; set; }
        public string TxDescricao { get; set; }
        public int? IdTipoTabela { get; set; }
        public string TxTabela { get; set; }
        public string NmAtributoApresentacao { get; set; }
        public string NmAtributoGravacao { get; set; }
        public bool InObrigatorio { get; set; }
        public string VlParametroDescricao { get; set; }
        /// <summary>
        /// para identificar se na tela de parametrização de sistema irá ficar com o botão ...
        /// </summary>
        public bool InPesquisaEmTela { get; set; }
        public string NmPagina { get; set; }

        public virtual Aplicativo IdAplicativoNavigation { get; set; }
        public virtual TipoParametro IdTipoParametroNavigation { get; set; }
        public virtual TipoTabela IdTipoTabelaNavigation { get; set; }
    }
}