// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ParcelaContaReceberHistorico
    {
        public int IdContaReceber { get; set; }
        public int NrParcela { get; set; }
        public DateTime DtHistorico { get; set; }
        public int IdHistorico { get; set; }
        public int? IdUsuario { get; set; }

        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ParcelaContaReceber ParcelaContaReceber { get; set; }
    }
}