// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ParcelaContaReceberBaixaDesconto
    {
        public int IdParcelacontareceberBaixaDesconto { get; set; }
        public int IdParcelacontareceberBaixa { get; set; }
        public int IdTipoDesconto { get; set; }
        public decimal VlDesconto { get; set; }
        public decimal? PrDesconto { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtCadastro { get; set; }
        public bool? InAtivo { get; set; }

        public virtual ParcelaContaReceberBaixa IdParcelacontareceberBaixaNavigation { get; set; }
        public virtual TipoDiversos IdTipoDescontoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}