// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Pendencia
    {
        public Pendencia()
        {
            NotificacaoPendencia = new HashSet<NotificacaoPendencia>();
        }

        public int IdPendencia { get; set; }
        public string TxPendencia { get; set; }
        public DateTime DtCriacao { get; set; }
        public DateTime DtLimite { get; set; }
        public DateTime? DtEncerramento { get; set; }
        public int CdModulo { get; set; }
        public int CdOrigem { get; set; }
        public int? QnMensagensEnviadas { get; set; }
        public int IdTipoPendencia { get; set; }

        public virtual TipoPendencia IdTipoPendenciaNavigation { get; set; }
        public virtual ICollection<NotificacaoPendencia> NotificacaoPendencia { get; set; }
    }
}