// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PerfilClassificacaoProduto
    {
        public int IdPerfil { get; set; }
        public int IdClassificacao { get; set; }

        public virtual ClassificacaoProduto IdClassificacaoNavigation { get; set; }
        public virtual Perfil IdPerfilNavigation { get; set; }
    }
}