// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PessoaEndereco
    {
        public PessoaEndereco()
        {
            PessoaEnderecoFinalidade = new HashSet<PessoaEnderecoFinalidade>();
        }

        public int IdEndereco { get; set; }
        public int IdPessoa { get; set; }
        public int? IdJustEndeDesaTipo { get; set; }
        public bool? InEnderecoAtivo { get; set; }
        public string TxObservacao { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public int? LocNu { get; set; }
        public string CdCep { get; set; }
        public int? BaiNu { get; set; }
        public string TxLogradouro { get; set; }
        public string NrNumero { get; set; }
        public string TxComplemento { get; set; }
        public int? IdEnderecoTipo { get; set; }
        public int? IdImovelTipo { get; set; }
        public int? IdEnderecoCategoriaTipo { get; set; }

        public virtual LogBairro BaiNuNavigation { get; set; }
        public virtual TipoDiversos IdEnderecoCategoriaTipoNavigation { get; set; }
        public virtual Endereco IdEnderecoNavigation { get; set; }
        public virtual TipoDiversos IdEnderecoTipoNavigation { get; set; }
        public virtual TipoDiversos IdImovelTipoNavigation { get; set; }
        public virtual TipoDiversos IdJustEndeDesaTipoNavigation { get; set; }
        public virtual Pessoa IdPessoaNavigation { get; set; }
        public virtual LogLocalidade LocNuNavigation { get; set; }
        public virtual ICollection<PessoaEnderecoFinalidade> PessoaEnderecoFinalidade { get; set; }
    }
}