// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PessoaRelacionamento
    {
        public int IdPessoa { get; set; }
        public int IdPessoaEntidade { get; set; }
        public int IdPessoaDependente { get; set; }
        public bool? InAtivo { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual Relacionamento IdPessoa1 { get; set; }
        public virtual Pessoa IdPessoaNavigation { get; set; }
    }
}