// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PessoaHistorico
    {
        public int IdPessoaHistorico { get; set; }
        public int IdPessoa { get; set; }
        public string NmPessoa { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtInclusao { get; set; }
        public bool? InInclusao { get; set; }

        public virtual Pessoa IdPessoaNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}