// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PlanoDeContasFinanceiro
    {
        public int PlanoContasId { get; set; }
        public int Codigo { get; set; }
        public int Natureza { get; set; }
        public int Contabil { get; set; }
        public int Titulo { get; set; }
        public int Descricao { get; set; }
        public int PlanoContasPaiId { get; set; }
    }
}