// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PlanoTratamentoOncologia
    {
        public PlanoTratamentoOncologia()
        {
            PlanoTratamentoOncologiaProtocolo = new HashSet<PlanoTratamentoOncologiaProtocolo>();
        }

        public int IdPlanoTratamentoOncologia { get; set; }
        public int IdPaciente { get; set; }
        public decimal QnPeso { get; set; }
        public decimal QnAltura { get; set; }
        public decimal QnSc { get; set; }
        public DateTime DtCadastro { get; set; }
        public int IdUsuario { get; set; }

        public virtual Pessoa IdPacienteNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<PlanoTratamentoOncologiaProtocolo> PlanoTratamentoOncologiaProtocolo { get; set; }
    }
}