// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PlanoOperadoraCategoria
    {
        public int IdPlanoCategoria { get; set; }
        public int IdOperadora { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public bool InAtivo { get; set; }
        public double? VlCh { get; set; }

        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual TipoDiversos IdPlanoCategoriaNavigation { get; set; }
    }
}