// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PontoAtendimento
    {
        public int IdPontoAtendimento { get; set; }
        public string TxDescricaoPontoAtendimento { get; set; }
        public int NrRamal { get; set; }
    }
}