// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PorteTabela
    {
        public PorteTabela()
        {
            Porte = new HashSet<Porte>();
            ServicoProdutoTabelaPorteTabela = new HashSet<ServicoProdutoTabelaPorteTabela>();
        }

        public int IdPorteTabela { get; set; }
        public string NmPorteTabela { get; set; }
        public int IdPorteTabelaTipo { get; set; }
        public decimal? PrViaUnica { get; set; }
        public decimal? PrViaVarias { get; set; }
        public decimal? PrBilateralUnica { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public decimal? PrBilateralVarias { get; set; }
        public bool InReal { get; set; }

        public virtual TipoDiversos IdPorteTabelaTipoNavigation { get; set; }
        public virtual ICollection<Porte> Porte { get; set; }
        public virtual ICollection<ServicoProdutoTabelaPorteTabela> ServicoProdutoTabelaPorteTabela { get; set; }
    }
}