// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PrecoProdutoTabelaSus
    {
        public int IdServicoProdutoTabela { get; set; }
        public string NmServicoProdutoTabela { get; set; }
        public int IdServico { get; set; }
        public string CdServico { get; set; }
        public string TxDescricao { get; set; }
        public DateTime? DtVigencia { get; set; }
        public string IdFabricante { get; set; }
        public string NmFabricante { get; set; }
        public int? NrNivel { get; set; }
        public string NmServicoCategoria { get; set; }
        public bool InAtivo { get; set; }
        public int? IdProdutoDetalhe { get; set; }
        public bool InDesconto { get; set; }
        public string VlPrecoFabricanteAtualizado { get; set; }
        public string VlPrecoConsumidorAtualizado { get; set; }
        public bool InAtual { get; set; }
        public int InAtualizacaoPreco { get; set; }
        public string VlPrecoFabricante { get; set; }
        public string VlPrecoConsumidor { get; set; }
        public int InAssociado { get; set; }
    }
}