// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PrecoProduto
    {
        public int IdFabricante { get; set; }
        public int IdProdutoDetalhe { get; set; }
        public int IdServicoProdutoTabela { get; set; }
        public int IdServico { get; set; }
        public DateTime DtVigencia { get; set; }
        public double VlPrecoFabricante { get; set; }
        public double VlPrecoConsumidor { get; set; }
        public bool? InDesconto { get; set; }
        public bool? InAtual { get; set; }
        public int? IdUsuario { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public string NrEdicao { get; set; }
        public DateTime? DtCadastro { get; set; }
        public bool? InAtivo { get; set; }

        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}