// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PrecoProdutoCargaLog
    {
        public int IdPrecoProdutoCargaLog { get; set; }
        public int IdPrecoProdutoCargaHistorico { get; set; }
        public string NrEdicao { get; set; }
        public int IdServicoProdutoTabela { get; set; }
        public int IdServico { get; set; }
        public string CdServico { get; set; }
        public string TxDescricaoServico { get; set; }
        public int IdServicoCategoria { get; set; }
        public string TxPrecoTipo { get; set; }
        public double VlProduto { get; set; }
        public DateTime DtCarga { get; set; }
        public bool InInsercao { get; set; }
        public bool InExclusao { get; set; }
        public bool InAtualizacao { get; set; }
        public string TxDescricaoAtualizacao { get; set; }
        public int IdUsuario { get; set; }
        public byte[] RvVersaoLinha { get; set; }
    }
}