// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class PrecoProdutoTrabalho
    {
        public long CdServico { get; set; }
        public int IdServico { get; set; }
        public int IdServicoProdutoTabela { get; set; }
        public int IdServicoCategoria { get; set; }
        public string TxDescricaoServico { get; set; }
        public int? IdFabricante { get; set; }
        public double VlPrecoProdutoFabricante { get; set; }
        public double VlPrecoProdutoConsumidor { get; set; }
        public bool InCadastroManual { get; set; }
        public bool InAtivo { get; set; }
    }
}