// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Procedimentos
    {
        public Procedimentos()
        {
            ProcedimentoPedido = new HashSet<ProcedimentoPedido>();
            ProcedimentoPedidoProcedimentos = new HashSet<ProcedimentoPedidoProcedimentos>();
            ProcedimentosRecurso = new HashSet<ProcedimentosRecurso>();
            ProcedimentosRegiaoAplicacao = new HashSet<ProcedimentosRegiaoAplicacao>();
            ProcedimentosServico = new HashSet<ProcedimentosServico>();
        }

        /// <summary>
        /// chave identity do procedimento de imagem
        /// </summary>
        public int IdProcedimento { get; set; }
        /// <summary>
        /// nome do procedimento
        /// </summary>
        public string NmProcedimento { get; set; }
        /// <summary>
        /// preparo do paciente
        /// </summary>
        public string TxPreparoPaciente { get; set; }
        /// <summary>
        /// tipo do procedimento, tabela 431
        /// </summary>
        public int? IdTipoProcedimento { get; set; }
        /// <summary>
        /// exclusão lógica
        /// </summary>
        public bool? InAtivo { get; set; }

        public virtual TipoDiversos IdTipoProcedimentoNavigation { get; set; }
        public virtual ICollection<ProcedimentoPedido> ProcedimentoPedido { get; set; }
        public virtual ICollection<ProcedimentoPedidoProcedimentos> ProcedimentoPedidoProcedimentos { get; set; }
        public virtual ICollection<ProcedimentosRecurso> ProcedimentosRecurso { get; set; }
        public virtual ICollection<ProcedimentosRegiaoAplicacao> ProcedimentosRegiaoAplicacao { get; set; }
        public virtual ICollection<ProcedimentosServico> ProcedimentosServico { get; set; }
    }
}