// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProcedimentosServico
    {
        public int IdProcedimento { get; set; }
        public int IdOperadora { get; set; }
        public int IdServico { get; set; }
        public bool? InAtivo { get; set; }
        public int IdProcedimentoServico { get; set; }

        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual Procedimentos IdProcedimentoNavigation { get; set; }
        public virtual Servico IdServicoNavigation { get; set; }
    }
}