// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProdutoDetalheFabricanteServicoProdutoTabela
    {
        public ProdutoDetalheFabricanteServicoProdutoTabela()
        {
            ProdutoDetalheFabricanteServicoProdutoTabelaOperadora = new HashSet<ProdutoDetalheFabricanteServicoProdutoTabelaOperadora>();
            ProdutoDetalheFabricanteServicoProdutoTabelaPlano = new HashSet<ProdutoDetalheFabricanteServicoProdutoTabelaPlano>();
        }

        public int IdProdutoDetalhe { get; set; }
        public int IdFabricante { get; set; }
        public int IdServicoProdutoTabela { get; set; }
        public int IdServico { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual ProdutoDetalheFabricante Id { get; set; }
        public virtual ICollection<ProdutoDetalheFabricanteServicoProdutoTabelaOperadora> ProdutoDetalheFabricanteServicoProdutoTabelaOperadora { get; set; }
        public virtual ICollection<ProdutoDetalheFabricanteServicoProdutoTabelaPlano> ProdutoDetalheFabricanteServicoProdutoTabelaPlano { get; set; }
    }
}