// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProdutoDetalheViaAdministracao
    {
        public ProdutoDetalheViaAdministracao()
        {
            KitProduto = new HashSet<KitProduto>();
        }

        public int IdProdutoDetalhe { get; set; }
        public int IdViaAdministracao { get; set; }
        public int? IdKit { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual Kit IdKitNavigation { get; set; }
        public virtual ProdutoDetalhe IdProdutoDetalheNavigation { get; set; }
        public virtual TipoDiversos IdViaAdministracaoNavigation { get; set; }
        public virtual ICollection<KitProduto> KitProduto { get; set; }
    }
}