// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProdutoPreco
    {
        public int IdServicoProdutoTabela { get; set; }
        public int IdServico { get; set; }
        public int? CdServico { get; set; }
        public string TxDescricaoServico { get; set; }
        public string IdFabricante { get; set; }
        public string VlPrecoProdutoFabricante { get; set; }
        public string VlPrecoProdutoConsumidor { get; set; }
        public string InCadastroManual { get; set; }
        public bool InAtivo { get; set; }
    }
}