// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProdutoLocalizacao
    {
        public int IdProdutoLocalizacao { get; set; }
        public int IdProdutoDetalhe { get; set; }
        public int IdUnidadeOrganizacional { get; set; }
        public string TxLocalizacao { get; set; }
        public int IdUsuarioCadastro { get; set; }
        public DateTime DtCadastro { get; set; }

        public virtual ProdutoDetalhe IdProdutoDetalheNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeOrganizacionalNavigation { get; set; }
        public virtual Usuario IdUsuarioCadastroNavigation { get; set; }
    }
}