// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProdutoGeral
    {
        /// <summary>
        /// PK Identificador da tabela. FK com ProdutoDetalhe
        /// </summary>
        public int IdProdutoDetalhe { get; set; }
        /// <summary>
        /// FK com Produto.
        /// 
        /// </summary>
        public int IdProduto { get; set; }
        /// <summary>
        /// FK com Pessoa. Traz o ID do Fabricante.
        /// 
        /// </summary>
        public int IdFabricante { get; set; }
        /// <summary>
        /// Nome do Produto.
        /// </summary>
        public string NmProduto { get; set; }
        /// <summary>
        /// Nome comercial do Produto.
        /// </summary>
        public string NmComercial { get; set; }
        /// <summary>
        /// Variação do nome de acordo com o Produto Detalhe. Mesmo produtos podem ter &quot;N&quot; Apresentações. 
        /// </summary>
        public string TxApresentacao { get; set; }
        public int InAtivo { get; set; }
        /// <summary>
        /// Classificação do Produto. FK com ClassificacaoProduto
        /// </summary>
        public int IdClassificacaoGeral { get; set; }
        /// <summary>
        /// Classificação do Produto. FK com ClassificacaoProduto
        /// 
        /// </summary>
        public string NrCodigoBarras { get; set; }
        /// <summary>
        /// Nome completo do produto, concatenando o Nome, Nome Comercial e Apresentação.
        /// </summary>
        public string NmProdutoCompleto { get; set; }
    }
}