// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProdutoClassificacaoContabilPlanoContaContabil
    {
        public int IdProduto { get; set; }
        public int? IdClassificacaoContabil { get; set; }
        public int? IdPlanoContaFinanceiro { get; set; }
        public int? IdPlanoContaContabil { get; set; }
        public DateTime DtCadastro { get; set; }
        public int IdUsuarioCadastro { get; set; }
        public DateTime? DtAtualizacao { get; set; }
        public int? IdUsuarioAtualizacao { get; set; }
        public bool? InAtivo { get; set; }

        public virtual ClassificacaoContabil IdClassificacaoContabilNavigation { get; set; }
        public virtual Produto IdProdutoNavigation { get; set; }
        public virtual Usuario IdUsuarioAtualizacaoNavigation { get; set; }
        public virtual Usuario IdUsuarioCadastroNavigation { get; set; }
    }
}