// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProdutoQuimioterapicoItem
    {
        public int IdProdutoQuimioterapicoItem { get; set; }
        public int IdProdutoQuimioterapico { get; set; }
        public int IdSolicitacaoPdEnfermagemhorarioadministracaoLoteprodutoitem { get; set; }
        public bool InPrincipal { get; set; }

        public virtual ProdutoQuimioterapico IdProdutoQuimioterapicoNavigation { get; set; }
        public virtual SolicitacaoPdEnfermagemHorarioAdministracaoLoteProdutoItem IdSolicitacaoPdEnfermagemhorarioadministracaoLoteprodutoitemNavigation { get; set; }
    }
}