// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProdutoFornecedor
    {
        /// <summary>
        /// PK da Tabela. FK com Produto.
        /// </summary>
        public int IdProduto { get; set; }
        /// <summary>
        /// PK da Tabela. FK com Pessoa. (Fornecedor)
        /// </summary>
        public int IdFornecedor { get; set; }

        public virtual Pessoa IdFornecedorNavigation { get; set; }
        public virtual Produto IdProdutoNavigation { get; set; }
    }
}