// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProtocoloAplicacaoAtendimentoDispensacaoEnfermagem
    {
        public int IdProtocoloAplicacaoAtendimentoDispensacaoEnfermagem { get; set; }
        public int IdProtocoloAplicacaoAtendimento { get; set; }
        public int IdDispensacaoEnfermagem { get; set; }
        public int IdUsuario { get; set; }

        public virtual DispensacaoEnfermagem IdDispensacaoEnfermagemNavigation { get; set; }
        public virtual ProtocoloAplicacaoAtendimento IdProtocoloAplicacaoAtendimentoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}