// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProtocoloSame
    {
        public int IdProtocoloSame { get; set; }
        public int IdDocumentoLote { get; set; }
        public DateTime? DtArquivamento { get; set; }

        public virtual DocumentoLote IdDocumentoLoteNavigation { get; set; }
    }
}