// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProtocoloAplicacaoHistorico
    {
        public int IdProtocoloAplicacaoHistorico { get; set; }
        public DateTime DtProtocoloAplicacaoHistoricoUtc { get; set; }
        public int IdProtocoloAplicacao { get; set; }
        public int IdProtocoloItem { get; set; }
        public decimal QnDose { get; set; }
        public int QnHoraAplicacao { get; set; }
        public int IdUsuario { get; set; }
        public bool InAtivo { get; set; }
    }
}