// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProtocoloHistorico
    {
        public int IdProtocoloHistorico { get; set; }
        public int IdProtocolo { get; set; }
        public string NmProtocolo { get; set; }
        public string TxReferenciaBibliografica { get; set; }
        public bool InAtivo { get; set; }
        public int IdUsuario { get; set; }
        public bool? InAjusteHorarioPrimeiraImportacao { get; set; }
        public DateTime DtProtocoloHistoricoUtc { get; set; }
    }
}