// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProtocoloAplicacaoAtendimentoPrescricaoHorario
    {
        public int IdProtocoloAplicacaoAtendimentoPrescricaoHorario { get; set; }
        public int IdProtocoloAplicacaoAtendimento { get; set; }
        public int IdSolicitacaoPdEnfermagemhorarioadministracao { get; set; }
        public int IdUsuario { get; set; }

        public virtual ProtocoloAplicacaoAtendimento IdProtocoloAplicacaoAtendimentoNavigation { get; set; }
        public virtual SolicitacaoPdEnfermagemHorarioAdministracao IdSolicitacaoPdEnfermagemhorarioadministracaoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}