// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProtocoloBloqueioAgendaSadt
    {
        public int IdProtocoloBloqueioAgenda { get; set; }
        public int IdMedico { get; set; }
        public DateTime DtInicioBloqueio { get; set; }
        public DateTime DtFimBloqueio { get; set; }
        public DateTime? HrInicioBloqueio { get; set; }
        public DateTime? HrFimBloqueio { get; set; }
        public string TxJustificativa { get; set; }
        public bool InForaPrazo { get; set; }
        public bool? InAgendaExtra { get; set; }
        public DateTime? DtInicioAgendaExtra { get; set; }
        public DateTime? DtFimAgendaExtra { get; set; }
        public DateTime? HrInicioAgendaExtra { get; set; }
        public DateTime? HrFimAgendaExtra { get; set; }
        public DateTime DtCadastro { get; set; }
        public int IdUsuario { get; set; }
        public bool InAtivo { get; set; }
    }
}