// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ProtocoloClassificacao
    {
        public int IdProtocoloClassificacao { get; set; }
        public string NmProtocoloClassificacao { get; set; }
        public string NmTipoLayout { get; set; }
        public string NmMetodoDeCalculo { get; set; }
        public string TxMetodologia { get; set; }
        public int? IdExtratoResultado { get; set; }
    }
}