// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Rastreamento
    {
        public int IdLoteProdutoItem { get; set; }
        public DateTime DtDispensacao { get; set; }
        public int? IdSolicitacao { get; set; }
        public DateTime? DtRecebimento { get; set; }
        public bool InLocalProduto { get; set; }
        public int? IdUnidadeLocalProduto { get; set; }
        public int? IdUsuarioDispensou { get; set; }
        public int? IdUsuarioRecebeu { get; set; }

        public virtual LoteProdutoItem IdLoteProdutoItemNavigation { get; set; }
        public virtual Solicitacao IdSolicitacaoNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeLocalProdutoNavigation { get; set; }
    }
}