// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RecursoGlosa
    {
        public RecursoGlosa()
        {
            CartaRecursoRecurso = new HashSet<CartaRecursoRecurso>();
        }

        public int IdFechamentoItem { get; set; }
        public int IdConta { get; set; }
        public double? VlRecursado { get; set; }
        public int? QnRecursada { get; set; }
        public double? VlRecursadoTotal { get; set; }
        public string TxObservacoes { get; set; }
        public int IdJustificativaRecurso { get; set; }
        public DateTime? DtRecurso { get; set; }
        public int IdUsuario { get; set; }

        public virtual Glosa Id { get; set; }
        public virtual JustificativaRecurso IdJustificativaRecursoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<CartaRecursoRecurso> CartaRecursoRecurso { get; set; }
    }
}