// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RefeicaoUnidadeOrganizacionalTipoRefeicao
    {
        public int IdUnidadeOrganizacional { get; set; }
        public int IdTipoRefeicao { get; set; }
        public int IdRefeicao { get; set; }
        public int IdUsuarioCadastro { get; set; }
        public DateTime DtCadastro { get; set; }
        public int IdUsuarioAlteracao { get; set; }
        public DateTime DtAlteracao { get; set; }
        public bool? InAtivo { get; set; }

        public virtual Refeicao IdRefeicaoNavigation { get; set; }
        public virtual TipoDiversos IdTipoRefeicaoNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeOrganizacionalNavigation { get; set; }
        public virtual Usuario IdUsuarioAlteracaoNavigation { get; set; }
        public virtual Usuario IdUsuarioCadastroNavigation { get; set; }
    }
}