// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Refeicao
    {
        public Refeicao()
        {
            AlimentoRefeicao = new HashSet<AlimentoRefeicao>();
            RefeicaoUnidadeOrganizacional = new HashSet<RefeicaoUnidadeOrganizacional>();
            RefeicaoUnidadeOrganizacionalTipoRefeicao = new HashSet<RefeicaoUnidadeOrganizacionalTipoRefeicao>();
        }

        public int IdRefeicao { get; set; }
        public string NmRefeicao { get; set; }
        public DateTime DtCadastro { get; set; }
        public int IdUsuario { get; set; }
        public bool InAtivo { get; set; }
        public int? IdServico { get; set; }
        public int? IdUnidadeMedida { get; set; }

        public virtual Servico IdServicoNavigation { get; set; }
        public virtual TipoDiversos IdUnidadeMedidaNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<AlimentoRefeicao> AlimentoRefeicao { get; set; }
        public virtual ICollection<RefeicaoUnidadeOrganizacional> RefeicaoUnidadeOrganizacional { get; set; }
        public virtual ICollection<RefeicaoUnidadeOrganizacionalTipoRefeicao> RefeicaoUnidadeOrganizacionalTipoRefeicao { get; set; }
    }
}