// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RefeicaoUnidadeOrganizacional
    {
        public int IdUnidadeOrganizacional { get; set; }
        public int IdRefeicao { get; set; }
        public decimal QnRefeicao { get; set; }
        public DateTime DtLancamento { get; set; }
        public DateTime DtCadastro { get; set; }
        public int IdUsuario { get; set; }

        public virtual Refeicao IdRefeicaoNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeOrganizacionalNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}