// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RegistroEletronicoItemHistorico
    {
        public int IdRegistroEletronicoItem { get; set; }
        public int IdRegistroEletronicoItemHistorico { get; set; }
        public string TxHtmlConteudo { get; set; }
        public DateTime DtRegistro { get; set; }
        public bool InAtivo { get; set; }
        public DateTime DtOcorrencia { get; set; }

        public virtual RegistroEletronicoItem IdRegistroEletronicoItemNavigation { get; set; }
    }
}