// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RegistroEletronicoModelo
    {
        public RegistroEletronicoModelo()
        {
            ClassificacaoFluxo = new HashSet<ClassificacaoFluxo>();
            RegistroEletronico = new HashSet<RegistroEletronico>();
            RegistroEletronicoItemModelo = new HashSet<RegistroEletronicoItemModelo>();
            RegistroEletronicoItemTipoServico = new HashSet<RegistroEletronicoItemTipoServico>();
            RegistroEletronicoModeloExigidoIdRegistroEletronicoModeloExigidoNavigation = new HashSet<RegistroEletronicoModeloExigido>();
            RegistroEletronicoModeloExigidoIdRegistroEletronicoModeloNavigation = new HashSet<RegistroEletronicoModeloExigido>();
            RegistroEletronicoModeloHistorico = new HashSet<RegistroEletronicoModeloHistorico>();
            RegistroEletronicoModeloPessoaEntidade = new HashSet<RegistroEletronicoModeloPessoaEntidade>();
            RegistroEletronicoModeloServico = new HashSet<RegistroEletronicoModeloServico>();
            RegistroEletronicoModeloUnidadeOrganizacional = new HashSet<RegistroEletronicoModeloUnidadeOrganizacional>();
        }

        public int IdRegistroEletronicoModelo { get; set; }
        public int IdTipoRegistroEletronico { get; set; }
        public int? IdTipoOcorrencia { get; set; }
        public int IdUsuario { get; set; }
        public string NmRegistroEletronicoModelo { get; set; }
        public string NrVersao { get; set; }
        public bool InAtivo { get; set; }
        public bool InCustomizavel { get; set; }
        /// <summary>
        /// nome do arquivo do arquétipo
        /// </summary>
        public string NmArquivo { get; set; }
        public bool InNecessitaFinalizacao { get; set; }
        public bool InImprimeFinalizado { get; set; }
        public bool InPadrao { get; set; }
        public int? NrPrazoPreenchimento { get; set; }
        public bool InMostrarAba { get; set; }
        public int? NrHorasAposObito { get; set; }
        public bool InSomenteCriadorEdita { get; set; }
        public bool? InPermiteCopia { get; set; }
        public bool InEditarOutrosProfissionais { get; set; }
        public bool InFinalizaAutomatico { get; set; }
        public string NmAba { get; set; }
        public bool? InMostrarRegistroClinicos { get; set; }

        public virtual TipoDiversos IdTipoOcorrenciaNavigation { get; set; }
        public virtual TipoDiversos IdTipoRegistroEletronicoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<ClassificacaoFluxo> ClassificacaoFluxo { get; set; }
        public virtual ICollection<RegistroEletronico> RegistroEletronico { get; set; }
        public virtual ICollection<RegistroEletronicoItemModelo> RegistroEletronicoItemModelo { get; set; }
        public virtual ICollection<RegistroEletronicoItemTipoServico> RegistroEletronicoItemTipoServico { get; set; }
        public virtual ICollection<RegistroEletronicoModeloExigido> RegistroEletronicoModeloExigidoIdRegistroEletronicoModeloExigidoNavigation { get; set; }
        public virtual ICollection<RegistroEletronicoModeloExigido> RegistroEletronicoModeloExigidoIdRegistroEletronicoModeloNavigation { get; set; }
        public virtual ICollection<RegistroEletronicoModeloHistorico> RegistroEletronicoModeloHistorico { get; set; }
        public virtual ICollection<RegistroEletronicoModeloPessoaEntidade> RegistroEletronicoModeloPessoaEntidade { get; set; }
        public virtual ICollection<RegistroEletronicoModeloServico> RegistroEletronicoModeloServico { get; set; }
        public virtual ICollection<RegistroEletronicoModeloUnidadeOrganizacional> RegistroEletronicoModeloUnidadeOrganizacional { get; set; }
    }
}