// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RegistroEletronicoItemAtributoHistorico
    {
        public int IdRegistroEletronicoItemAtributo { get; set; }
        public int IdRegistroEletronicoItemAtributoHistorico { get; set; }
        public DateTime DtRegistro { get; set; }
        public string TxValorAtributo { get; set; }
        public string TxDescricao { get; set; }
        public string TxObservacao { get; set; }
        public DateTime? DtAfericao { get; set; }
        public bool InAtivo { get; set; }
        public DateTime DtOcorrencia { get; set; }
        public int? IdUsuario { get; set; }
    }
}