// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RegistroEletronicoItemModeloAtributoEspecialidade
    {
        public int IdRegistroEletronicoItemModeloAtributo { get; set; }
        public int IdEspecialidade { get; set; }
        public bool? InAtivo { get; set; }

        public virtual TipoDiversos IdEspecialidadeNavigation { get; set; }
        public virtual RegistroEletronicoItemModeloAtributo IdRegistroEletronicoItemModeloAtributoNavigation { get; set; }
    }
}