// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RegistroEletronico
    {
        public RegistroEletronico()
        {
            RegistroEletronicoHistorico = new HashSet<RegistroEletronicoHistorico>();
            RegistroEletronicoImpressao = new HashSet<RegistroEletronicoImpressao>();
            RegistroEletronicoItem = new HashSet<RegistroEletronicoItem>();
        }

        public int IdRegistroEletronico { get; set; }
        public int IdRegistroEletronicoModelo { get; set; }
        public int IdStatusRegistroEletronico { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtRegistro { get; set; }
        public string NrVersaoModelo { get; set; }
        public bool InAtivo { get; set; }
        public int? IdAtendimento { get; set; }
        public int? IdServicoGuia { get; set; }
        public int? IdSolicitacaoPdEnfermagemhorarioadministracao { get; set; }
        public int? IdPessoa { get; set; }
        public int? IdCheckinEnfermagem { get; set; }
        public int? IdProcedimentoPrincipal { get; set; }
        public int? IdClassificacaoSenha { get; set; }
        public string TxRegistroDuplicadoSalvo { get; set; }
        public byte[] AdArquivoAssinado { get; set; }
        public string TxAssinaturaDigital { get; set; }
        public bool? InIntegracaoHl7 { get; set; }

        public virtual Folhadesala Id { get; set; }
        public virtual Atendimento IdAtendimentoNavigation { get; set; }
        public virtual ClassificacaoSenha IdClassificacaoSenhaNavigation { get; set; }
        public virtual Pessoa IdPessoaNavigation { get; set; }
        public virtual RegistroEletronicoModelo IdRegistroEletronicoModeloNavigation { get; set; }
        public virtual ServicoGuia IdServicoGuiaNavigation { get; set; }
        public virtual SolicitacaoPdEnfermagemHorarioAdministracao IdSolicitacaoPdEnfermagemhorarioadministracaoNavigation { get; set; }
        public virtual TipoDiversos IdStatusRegistroEletronicoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<RegistroEletronicoHistorico> RegistroEletronicoHistorico { get; set; }
        public virtual ICollection<RegistroEletronicoImpressao> RegistroEletronicoImpressao { get; set; }
        public virtual ICollection<RegistroEletronicoItem> RegistroEletronicoItem { get; set; }
    }
}