// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RegraAtributo
    {
        public RegraAtributo()
        {
            RegraAtributoAssociacao = new HashSet<RegraAtributoAssociacao>();
        }

        public int IdRegra { get; set; }
        public string TxDescricao { get; set; }
        public DateTime? DtRegra { get; set; }

        public virtual ICollection<RegraAtributoAssociacao> RegraAtributoAssociacao { get; set; }
    }
}