// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Relacionamento
    {
        public Relacionamento()
        {
            HorarioPlantao = new HashSet<HorarioPlantao>();
            PessoaRelacionamento = new HashSet<PessoaRelacionamento>();
            Recomendacao = new HashSet<Recomendacao>();
            RelacionamentoOcorrenciaTipo = new HashSet<RelacionamentoOcorrenciaTipo>();
            RelacionamentoTipoOcorrencia = new HashSet<RelacionamentoTipoOcorrencia>();
        }

        public int IdPessoaEntidade { get; set; }
        public int IdPessoa { get; set; }
        public bool? InAtivo { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual PessoaEntidade IdPessoaEntidadeNavigation { get; set; }
        public virtual Pessoa IdPessoaNavigation { get; set; }
        public virtual ICollection<HorarioPlantao> HorarioPlantao { get; set; }
        public virtual ICollection<PessoaRelacionamento> PessoaRelacionamento { get; set; }
        public virtual ICollection<Recomendacao> Recomendacao { get; set; }
        public virtual ICollection<RelacionamentoOcorrenciaTipo> RelacionamentoOcorrenciaTipo { get; set; }
        public virtual ICollection<RelacionamentoTipoOcorrencia> RelacionamentoTipoOcorrencia { get; set; }
    }
}