// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RelatorioProfilatico
    {
        public int Atendimento { get; set; }
        public string Internação { get; set; }
        public string Paciente { get; set; }
        public string ProcedimentoS { get; set; }
        public string InícioProcedimento { get; set; }
        public string Protocolo { get; set; }
        public string DataHoraAssociação { get; set; }
        public string TipoDose { get; set; }
        public string Medicamento { get; set; }
        public double? Dose { get; set; }
        public string PrevisãoAplicação { get; set; }
        public string Intervalo { get; set; }
        public string Associada { get; set; }
        public string Checkin { get; set; }
        public string Prescrição { get; set; }
        public string EtiquetasUtilizadas { get; set; }
        public string Checagem { get; set; }
    }
}