// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RelacionamentoOcorrenciaTipo
    {
        public DateTime DtOcorrencia { get; set; }
        public string TxMotivo { get; set; }
        public int IdPessoaEntidade { get; set; }
        public int IdPessoa { get; set; }
        public int IdOcorrencia { get; set; }
        public bool InAtivo { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual TipoDiversos IdOcorrenciaNavigation { get; set; }
        public virtual Relacionamento IdPessoaNavigation { get; set; }
    }
}