// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RemuneracaoServicoHistorico
    {
        public int IdRemuneracaoservicohistorico { get; set; }
        public int IdOperadora { get; set; }
        public DateTime DtModificacao { get; set; }
        public int IdUsuario { get; set; }
        public bool InInsercao { get; set; }
        public double? VlChGeral { get; set; }
        public double? VlTaxaServico { get; set; }
        public double? VlTaxaAcrescimoServico { get; set; }
        public double? VlFilme { get; set; }
        public int? IdGrupoHorario { get; set; }
        public double? VlLimite { get; set; }
        public double? VlLimiteGrupo { get; set; }
        public string HrVencimentoDiaria { get; set; }
        public int? QnToleranciaEntrada { get; set; }
        public int? QnToleranciaSaida { get; set; }
        public double? VlUnidadeCustoOperacional { get; set; }
        public double? VlRedutorHonorario { get; set; }
        public double? VlRedutorCustoOperacional { get; set; }
        public double? VlDescontoOperadora { get; set; }
        public double? VlTaxaAcomodacaoSuperior { get; set; }
        public double? PrTaxaSalaInstrumental { get; set; }
        public double? PrPrimeiroAuxiliar { get; set; }
        public double? PrDemaisAuxiliares { get; set; }
        public double? PrTaxaDemaisProcedimentos { get; set; }
        public double? PrPrimeiroAuxiliarAnestesista { get; set; }
        public double? PrDemaisAuxiliaresAnestesistas { get; set; }
        public bool? InTipoContaTaxaServico { get; set; }
        public int? IdClassficacaoTaxaServico { get; set; }
        public bool? InDiariaAutomatica { get; set; }
        public bool? InCalculaDiferencaDiaria { get; set; }
        public DateTime? DtInicioVigencia { get; set; }
        public DateTime? DtFimVigencia { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public bool InDiariaAlta { get; set; }
        public bool InDiariaHospitalDia { get; set; }

        public virtual TipoDiversos IdGrupoHorarioNavigation { get; set; }
        public virtual RemuneracaoServico IdOperadoraNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}