// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RepassePorMedicoClinicaUnidade
    {
        public int? IdLote { get; set; }
        public int? IdClinica { get; set; }
        public int? IdMedico { get; set; }
        public string NmUnidade { get; set; }
        public double? VlServicoConvenio { get; set; }
        public double? VlDespesaConvenio { get; set; }
        public double? VlLiquidoConvenio { get; set; }
        public double? VlRepasseConvenio { get; set; }
        public double? NrPercentualConvenio { get; set; }
        public double? VlServicoParticular { get; set; }
        public double? VlDespesaParticular { get; set; }
        public double? VlLiquidoParticular { get; set; }
        public double? VlRepasseParticular { get; set; }
        public double? NrPercentualParticular { get; set; }
        public int IdUnidadeOrganizacional { get; set; }
        public DateTime DtInicioProcessamento { get; set; }
        public DateTime DtFimProcessamento { get; set; }
    }
}