// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RepasseCustoOperacionalPacote
    {
        public int IdRepasseCustoOperacionalPacote { get; set; }
        public int IdOperadora { get; set; }
        public int? IdPlano { get; set; }
        public int IdServico { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtVigencia { get; set; }
        public DateTime DtCadastro { get; set; }
        public double? PrCirurgiaoClinico { get; set; }
        public double? VlCirurgiaoClinico { get; set; }
        public double? PrPrimeiroAuxiliar { get; set; }
        public double? VlPrimeiroAuxiliar { get; set; }
        public double? PrSegundoAuxiliar { get; set; }
        public double? VlSegundoAuxiliar { get; set; }
        public double? PrTerceiroAuxiliar { get; set; }
        public double? VlTerceiroAuxiliar { get; set; }
        public double? PrAnestesista { get; set; }
        public double? VlAnestesista { get; set; }
        public bool? InAtivo { get; set; }
        public int? IdUsuarioDesativacao { get; set; }
        public DateTime? DtDesativacao { get; set; }

        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual Plano IdPlanoNavigation { get; set; }
        public virtual Servico IdServicoNavigation { get; set; }
        public virtual Usuario IdUsuarioDesativacaoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}