// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RepasseMedicoLote
    {
        public RepasseMedicoLote()
        {
            RepasseMedico = new HashSet<RepasseMedico>();
            RepasseMedicoHistorico = new HashSet<RepasseMedicoHistorico>();
        }

        public int IdRepasseMedicoLote { get; set; }
        public DateTime DtInicioProcessamento { get; set; }
        public DateTime DtFimProcessamento { get; set; }
        public int IdUsuario { get; set; }
        public int? IdClinica { get; set; }
        public string NrNotaFiscal { get; set; }
        public DateTime? DtEmissao { get; set; }
        public double? VlPago { get; set; }
        public DateTime? DtInicioProcessamentoConc { get; set; }
        public DateTime? DtFimProcessamentoConc { get; set; }

        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<RepasseMedico> RepasseMedico { get; set; }
        public virtual ICollection<RepasseMedicoHistorico> RepasseMedicoHistorico { get; set; }
    }
}