// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RepasseOperadoraUnidadeOrganizacionalServico
    {
        public int IdOperadoraUnidadeorganizacionalServico { get; set; }
        public int IdOperadora { get; set; }
        public int IdUnidadeOrganizacional { get; set; }
        public int IdServico { get; set; }
        public double? NrPercentual { get; set; }
        public DateTime DtLancamento { get; set; }
        public DateTime DtInicioVigencia { get; set; }
        public bool InAtual { get; set; }
        public DateTime? DtAtualizacao { get; set; }
        public bool InAtivo { get; set; }
        public DateTime? DtDesativacao { get; set; }
        public int IdUsuario { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public double? VlRepasseFixo { get; set; }

        public virtual UnidadeOrganizacionalServico Id { get; set; }
        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}