// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RepasseAuxilio
    {
        public string CdProcedimento { get; set; }
        public double VlHospital { get; set; }
        public double VlProfissional { get; set; }
        public double VlAnestesista { get; set; }
        public int IdUnidadeOrganizacional { get; set; }
        public int IdRepasseAuxilio { get; set; }
    }
}