// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RepasseDuplicadoteste
    {
        public int? IdConta { get; set; }
        public int? IdFechamentoItem { get; set; }
    }
}