// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RepassePorClinicaUnidade
    {
        public int? IdLote { get; set; }
        public int? IdClinica { get; set; }
        public string NmUnidade { get; set; }
        public decimal? VlServico { get; set; }
        public decimal? VlDespesa { get; set; }
        public decimal? VlLiquido { get; set; }
        public decimal? VlRepasse { get; set; }
    }
}