// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RestricaoPdvalor
    {
        public int IdRestricaoValor { get; set; }
        public int IdProdutoDetalhe { get; set; }
        public int IdAtributo { get; set; }
        public string TxValorRestricao { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual RestricaoProdutoDetalhe Id { get; set; }
    }
}