// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ResultadoCotacao
    {
        /// <summary>
        /// PK da Tabela. FK com Cotacao_Fornecedor_ProdutoDetalhe.
        /// </summary>
        public int IdCotacaoFornecedorProdutodetalhe { get; set; }
        /// <summary>
        /// Flag que informa quem foi o fornecedor ganhador da cotação.
        /// </summary>
        public bool? InVencedor { get; set; }
        /// <summary>
        /// Foi criado para mostrar em qual classificação ficou a cotação do fornecedor.
        /// 
        /// </summary>
        public byte? NrClassifcacao { get; set; }
        /// <summary>
        /// No caso de alteração do vencedor, tem que informar uma justificativa de alteração. FK com TipoDiversos.
        /// 
        /// </summary>
        public int? IdJustificativa { get; set; }
        /// <summary>
        /// Texto livre para informar o motivo que o o vencedor da cotação foi modificado.
        /// </summary>
        public string TxJustificativa { get; set; }
        /// <summary>
        /// Flag que informa se ja teve ordem de compra gerada.
        /// 
        /// </summary>
        public bool? InOrdemCompraGerada { get; set; }

        public virtual CotacaoFornecedorProdutoDetalhe IdCotacaoFornecedorProdutodetalheNavigation { get; set; }
    }
}