// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ResumoLogWebServices
    {
        public string NmWebService { get; set; }
        public int Quantidade { get; set; }
        public string DtExecucao { get; set; }
    }
}