// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class RetencaoTecnica
    {
        public RetencaoTecnica()
        {
            RetencaoTecnicaLiberacao = new HashSet<RetencaoTecnicaLiberacao>();
        }

        public int IdRetencaoTecnica { get; set; }
        public int IdContaPagar { get; set; }
        public int? IdTipoRetencao { get; set; }
        public decimal VlRetencao { get; set; }
        public DateTime DtCadastro { get; set; }
        public int IdUsuario { get; set; }
        public bool? InAtivo { get; set; }

        public virtual ContaPagar IdContaPagarNavigation { get; set; }
        public virtual TipoDiversos IdTipoRetencaoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<RetencaoTecnicaLiberacao> RetencaoTecnicaLiberacao { get; set; }
    }
}