// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ReversaoGlosaGenerica
    {
        public int IdConta { get; set; }
        public double VlRevertido { get; set; }
        public DateTime DtReversao { get; set; }
        public int IdUsuario { get; set; }
        public int? IdNotaEmitida { get; set; }
        public bool InPaga { get; set; }

        public virtual ContaCobranca IdContaNavigation { get; set; }
        public virtual NotaEmitida IdNotaEmitidaNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}