// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class SacTipoOcorrencia
    {
        public SacTipoOcorrencia()
        {
            SacOcorrencia = new HashSet<SacOcorrencia>();
        }

        public int IdTipoOcorrencia { get; set; }
        public string TxDescricao { get; set; }
        public bool? InVisualizaAgendasadt { get; set; }
        public bool? InVisualizaAtendimento { get; set; }

        public virtual ICollection<SacOcorrencia> SacOcorrencia { get; set; }
    }
}