// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ServicoCompativel
    {
        public int IdServicoPrincipal { get; set; }
        public int IdInstrRegistroPrinc { get; set; }
        public int IdServicoCompativelTipo { get; set; }
        public int IdInstrRegistroComp { get; set; }
        public int? IdCompatibilidadeTipo { get; set; }
        public int? QnPermitida { get; set; }
        public bool? InAtivo { get; set; }

        public virtual TipoDiversos IdCompatibilidadeTipoNavigation { get; set; }
        public virtual TipoDiversos IdInstrRegistroCompNavigation { get; set; }
        public virtual TipoDiversos IdInstrRegistroPrincNavigation { get; set; }
        public virtual Servico IdServicoCompativelTipoNavigation { get; set; }
        public virtual Servico IdServicoPrincipalNavigation { get; set; }
    }
}