// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ServicoCheckinEnfermagem
    {
        public ServicoCheckinEnfermagem()
        {
            ContaItemServicoServicoCheckinEnfermagem = new HashSet<ContaItemServicoServicoCheckinEnfermagem>();
            DispensacaoEnfermagem = new HashSet<DispensacaoEnfermagem>();
            FolhadesalaPedidoSangue = new HashSet<FolhadesalaPedidoSangue>();
        }

        public int IdCheckinEnfermagem { get; set; }
        public int IdServico { get; set; }
        public bool InDispensacaoConcluida { get; set; }
        public int? IdUsuarioConcluiuDispensacao { get; set; }
        public int IdTipoCobranca { get; set; }
        public bool InCancelado { get; set; }
        public int QnRealizado { get; set; }
        public int? IdSolicitacao { get; set; }
        public int? IdServicoGuia { get; set; }
        public int? IdServicoRegiaoAplicacao { get; set; }
        public int? IdProcedimentoPedido { get; set; }
        public int? IdProcedimentoPedidoProcedimento { get; set; }

        public virtual CheckinEnfermagem IdCheckinEnfermagemNavigation { get; set; }
        public virtual ProcedimentoPedido IdProcedimentoPedidoNavigation { get; set; }
        public virtual ServicoGuia IdServicoGuiaNavigation { get; set; }
        public virtual Servico IdServicoNavigation { get; set; }
        public virtual TipoDiversos IdServicoRegiaoAplicacaoNavigation { get; set; }
        public virtual Solicitacao IdSolicitacaoNavigation { get; set; }
        public virtual CobrancaTipoEnfermagem IdTipoCobrancaNavigation { get; set; }
        public virtual Usuario IdUsuarioConcluiuDispensacaoNavigation { get; set; }
        public virtual ServicoFilmeIncidenciaAdicional ServicoFilmeIncidenciaAdicional { get; set; }
        public virtual ICollection<ContaItemServicoServicoCheckinEnfermagem> ContaItemServicoServicoCheckinEnfermagem { get; set; }
        public virtual ICollection<DispensacaoEnfermagem> DispensacaoEnfermagem { get; set; }
        public virtual ICollection<FolhadesalaPedidoSangue> FolhadesalaPedidoSangue { get; set; }
    }
}