// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ServicoServicoProdutoTabela
    {
        public ServicoServicoProdutoTabela()
        {
            ServicoOperadoraServicoProdutoTabelaPlano = new HashSet<ServicoOperadoraServicoProdutoTabelaPlano>();
            ServicoServicoProdutoTabelaServicoIncidencia = new HashSet<ServicoServicoProdutoTabelaServicoIncidencia>();
        }

        public int IdServico { get; set; }
        public int IdServicoProdutoTabela { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual Servico IdServicoNavigation { get; set; }
        public virtual ServicoProdutoTabela IdServicoProdutoTabelaNavigation { get; set; }
        public virtual ICollection<ServicoOperadoraServicoProdutoTabelaPlano> ServicoOperadoraServicoProdutoTabelaPlano { get; set; }
        public virtual ICollection<ServicoServicoProdutoTabelaServicoIncidencia> ServicoServicoProdutoTabelaServicoIncidencia { get; set; }
    }
}