// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ServicoPlano
    {
        public ServicoPlano()
        {
            ServicoPlanoHistorico = new HashSet<ServicoPlanoHistorico>();
        }

        public int IdServicoPlano { get; set; }
        public int IdPlano { get; set; }
        public int IdServico { get; set; }
        public int IdServicoProdutoTabela { get; set; }
        public int IdOperadora { get; set; }
        public double VlServico { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual Plano IdPlanoNavigation { get; set; }
        public virtual ICollection<ServicoPlanoHistorico> ServicoPlanoHistorico { get; set; }
    }
}