// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ServicoModalidadeTipo
    {
        public int IdServico { get; set; }
        public int IdModalidadeTipo { get; set; }
        public bool? InAtivo { get; set; }

        public virtual TipoDiversos IdModalidadeTipoNavigation { get; set; }
        public virtual Servico IdServicoNavigation { get; set; }
    }
}