// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ServicoPrestado
    {
        public ServicoPrestado()
        {
            ContaPagar = new HashSet<ContaPagar>();
        }

        public int IdServicoPrestado { get; set; }
        public string TxServicoPrestado { get; set; }
        public string NmServicoPrestado { get; set; }
        public int InAtivo { get; set; }

        public virtual ICollection<ContaPagar> ContaPagar { get; set; }
    }
}