// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ServicoPlanoHistorico
    {
        public int IdServicoPlano { get; set; }
        public DateTime DtVigencia { get; set; }
        public double VlServico { get; set; }
        public bool InAtual { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public int? IdUsuario { get; set; }

        public virtual ServicoPlano IdServicoPlanoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}