// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ServicoOperadoraServicoProdutoTabela
    {
        public int IdServicoOperadoraServicoprodutotabela { get; set; }
        public int IdOperadora { get; set; }
        public int IdServicoProdutoTabela { get; set; }
        public int IdServico { get; set; }
        public string CdServico { get; set; }
        public string TxDescricaoServico { get; set; }
        public double? VlCh { get; set; }
        public double? VlChExterno { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public bool? InAtivo { get; set; }
        public DateTime DtCadastro { get; set; }
        public DateTime? DtDesativacao { get; set; }
        public int? IdUsuarioCadastro { get; set; }
        public int? IdUsuarioDesativacao { get; set; }
        public int? IdPlano { get; set; }

        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual Plano IdPlanoNavigation { get; set; }
    }
}