// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ServicoPrecoSus
    {
        public int IdServicoPrecoSus { get; set; }
        public int IdServico { get; set; }
        public int IdOperadora { get; set; }
        public DateTime DtCadastro { get; set; }
        public decimal? VlDiferencaCirurgiaoClinico { get; set; }
        public decimal? VlDiferencaAuxiliar1 { get; set; }
        public decimal? VlDiferencaAuxiliar2 { get; set; }
        public decimal? VlDiferencaAuxiliar3 { get; set; }
        public decimal? VlDiferencaAnestesista { get; set; }
        public decimal? VlDiferencaPerfusionista { get; set; }
        public decimal? VlProfissionalSus { get; set; }
        public decimal? VlTotalDiferenca { get; set; }
        public decimal? VlTotalProcedimento { get; set; }
        public decimal? VlSubstituidoProfissionalSus { get; set; }
        public bool? InAtivo { get; set; }
        public int IdUsuario { get; set; }
        public DateTime DtInicioVigencia { get; set; }
        public DateTime? DtFimVigencia { get; set; }

        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual Servico IdServicoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}