// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ServicoAgenda
    {
        public int IdServicoAgenda { get; set; }
        public int IdServicoAgendaEtapa { get; set; }
        public string TxParametro { get; set; }
        public DateTime? DtExecucaoEtapa { get; set; }
        public DateTime? DtCadastramento { get; set; }
        public DateTime? DtCancelamento { get; set; }
        public int? IdUsuarioCancelamento { get; set; }
        public DateTime? DtAgendamento { get; set; }
        public int? IdUsuario { get; set; }

        public virtual ServicoAgendaEtapa IdServicoAgendaEtapaNavigation { get; set; }
        public virtual Usuario IdUsuarioCancelamentoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}