// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class ServicoPreparo
    {
        public int IdServicoPreparo { get; set; }
        public int IdServico { get; set; }
        public string TxDescricaoPreparo { get; set; }
        public int? NrHoraAntecipacao { get; set; }
        public int? NrHoraDuracao { get; set; }
        public string TxObservacoesMarcacao { get; set; }
        public int? QdDiasprazoentrega { get; set; }

        public virtual Servico IdServicoNavigation { get; set; }
    }
}