// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class SessaoOncologia
    {
        public SessaoOncologia()
        {
            SessaoOncologiaHistorico = new HashSet<SessaoOncologiaHistorico>();
            SessaoOncologiaItem = new HashSet<SessaoOncologiaItem>();
        }

        public int IdSessaoOncologia { get; set; }
        public int IdPlanoTratamentoOncologiaProtocolo { get; set; }
        public int? IdSolicitacao { get; set; }
        public int NrCiclo { get; set; }
        public string TxDiaAplicacao { get; set; }
        public DateTime DtPlanejada { get; set; }
        public DateTime? DtRealizada { get; set; }
        public DateTime DtCadastro { get; set; }
        public int IdUsuario { get; set; }
        public int IdStatus { get; set; }
        public string TxObservacaoMedica { get; set; }
        public string TxObservacaoEnfermagem { get; set; }
        public int? NrSessao { get; set; }

        public virtual PlanoTratamentoOncologiaProtocolo IdPlanoTratamentoOncologiaProtocoloNavigation { get; set; }
        public virtual Solicitacao IdSolicitacaoNavigation { get; set; }
        public virtual TipoDiversos IdStatusNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<SessaoOncologiaHistorico> SessaoOncologiaHistorico { get; set; }
        public virtual ICollection<SessaoOncologiaItem> SessaoOncologiaItem { get; set; }
    }
}