// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class SessaoOncologiaItem
    {
        public int IdSessaoOncologiaItem { get; set; }
        public int IdSessaoOncologia { get; set; }
        public int? IdSolicitacaoPdEnfermagem { get; set; }
        public int IdProduto { get; set; }
        public int? IdFaseInfusao { get; set; }
        public decimal QnDosePadrao { get; set; }
        public int IdUnidadeMedidaPadrao { get; set; }
        public decimal QnDoseCalculada { get; set; }
        public decimal? QnDoseAjustada { get; set; }
        public int? IdUnidadeMedida { get; set; }
        public int? IdViaAdministracao { get; set; }
        public decimal? QnTempoInfusao { get; set; }
        public int? IdInstrucaoEspecial { get; set; }
        public DateTime DtCadastro { get; set; }
        public int IdUsuario { get; set; }
        public int? IdOrdemInfusao { get; set; }
        public int? NrAssociacao { get; set; }
        public int? IdSessaoOncologiaItemPai { get; set; }
        public int? IdTipoItem { get; set; }
        public double? VlConcentracao { get; set; }
        public int? IdProdutoDetalhe { get; set; }
        public string TxJustificativa { get; set; }

        public virtual TipoDiversos IdFaseInfusaoNavigation { get; set; }
        public virtual TipoDiversos IdInstrucaoEspecialNavigation { get; set; }
        public virtual TipoDiversos IdOrdemInfusaoNavigation { get; set; }
        public virtual ProdutoDetalhe IdProdutoDetalheNavigation { get; set; }
        public virtual Produto IdProdutoNavigation { get; set; }
        public virtual SessaoOncologia IdSessaoOncologiaNavigation { get; set; }
        public virtual SolicitacaoPdEnfermagem IdSolicitacaoPdEnfermagemNavigation { get; set; }
        public virtual TipoDiversos IdTipoItemNavigation { get; set; }
        public virtual TipoDiversos IdUnidadeMedidaNavigation { get; set; }
        public virtual TipoDiversos IdUnidadeMedidaPadraoNavigation { get; set; }
        public virtual TipoDiversos IdViaAdministracaoNavigation { get; set; }
    }
}