// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class SituacaoConta
    {
        public SituacaoConta()
        {
            SituacaoDaConta = new HashSet<SituacaoDaConta>();
            SituacaoDaContaHistorico = new HashSet<SituacaoDaContaHistorico>();
        }

        public int IdSituacaoConta { get; set; }
        public string TxDescricao { get; set; }
        public bool InCobranca { get; set; }
        public bool InLiberacontapararepasse { get; set; }

        public virtual ICollection<SituacaoDaConta> SituacaoDaConta { get; set; }
        public virtual ICollection<SituacaoDaContaHistorico> SituacaoDaContaHistorico { get; set; }
    }
}