// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class SituacaoLote
    {
        public SituacaoLote()
        {
            LoteCobranca = new HashSet<LoteCobranca>();
        }

        public int IdSituacaoLote { get; set; }
        public string TxDescricao { get; set; }

        public virtual ICollection<LoteCobranca> LoteCobranca { get; set; }
    }
}