// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class SituacaoDaConta
    {
        public int? IdUsuario { get; set; }
        public int IdConta { get; set; }
        public int IdSituacaoConta { get; set; }
        public int IdUnidadeOrganizacional { get; set; }
        public DateTime DtLancamento { get; set; }

        public virtual SituacaoConta IdSituacaoContaNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeOrganizacionalNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}