// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Solicitacao
    {
        public Solicitacao()
        {
            DevolucaoChecagem = new HashSet<DevolucaoChecagem>();
            MensagemSolicitacao = new HashSet<MensagemSolicitacao>();
            PrescricaoImportacaoUsuarioIdPrescricaoImportacaoNavigation = new HashSet<PrescricaoImportacaoUsuario>();
            PrescricaoImportacaoUsuarioIdPrescricaoVisualizacaoNavigation = new HashSet<PrescricaoImportacaoUsuario>();
            Rastreamento = new HashSet<Rastreamento>();
            ServicoCheckinEnfermagem = new HashSet<ServicoCheckinEnfermagem>();
            SessaoOncologia = new HashSet<SessaoOncologia>();
            SolicitacaoHistorico = new HashSet<SolicitacaoHistorico>();
            SolicitacaoImpressao = new HashSet<SolicitacaoImpressao>();
            SolicitacaoIntegracaoSistemaLegado = new HashSet<SolicitacaoIntegracaoSistemaLegado>();
            SolicitacaoPdEnfermagem = new HashSet<SolicitacaoPdEnfermagem>();
            SolicitacaoProdutoDetalhe = new HashSet<SolicitacaoProdutoDetalhe>();
        }

        /// <summary>
        /// PK da Tabela. Identificador unico.
        /// </summary>
        public int IdSolicitacao { get; set; }
        /// <summary>
        /// Tipo de Solicitação. EX: Compras, Transferencia, Prescrição etc. FK com TipoDiversos.
        /// </summary>
        public int IdTipoSolicitacao { get; set; }
        /// <summary>
        /// Data de criação da solicitação.
        /// </summary>
        public DateTime DtSolicitacao { get; set; }
        /// <summary>
        /// Unidade que irá atenteder a solicitação. FK com UnidadeOrganizacional.
        /// </summary>
        public int IdUnidadeExecutora { get; set; }
        /// <summary>
        /// Unidade que está solicitando. FK com UnidadeOrganizacional.
        /// </summary>
        public int IdUnidadeSolicitante { get; set; }
        /// <summary>
        /// Data em que a solicitação foi atendida.
        /// </summary>
        public DateTime? DtAtendimento { get; set; }
        /// <summary>
        /// Status da solicitação. FK com TipoDiversos.
        /// 
        /// </summary>
        public int IdStatusSolicitacao { get; set; }
        /// <summary>
        /// Grau de prioridade da solicitação. EX: Normal, Urgente. FK com TipoDiversos.
        /// 
        /// </summary>
        public int? IdPrioridade { get; set; }
        /// <summary>
        /// Usuário que criou a solicitação. 
        /// 
        /// </summary>
        public int? IdUsuarioSolicitou { get; set; }
        /// <summary>
        /// Data prevista de atendimento à solicitação.
        /// </summary>
        public DateTime? DtPrevistaAtendimento { get; set; }
        /// <summary>
        /// No caso de uma prescrição médica, relaciona o atendimento do paciente. FK com Atendimento.
        /// 
        /// </summary>
        public int? IdAtendimento { get; set; }
        /// <summary>
        /// No caso de uma prescrição médica, relaciona médico que solicitou. 
        /// </summary>
        public int? IdMedico { get; set; }
        /// <summary>
        /// Validade da solicitação. No caso de Prescrição.
        /// 
        /// </summary>
        public DateTime? DtValidade { get; set; }
        /// <summary>
        /// Texto livre.
        /// 
        /// </summary>
        public string TxObservacao { get; set; }
        /// <summary>
        /// No caso de prioridade Urgente e Emergencial, deve ser informado uma justificativa de solicitação. FK com TipoDiversos.
        /// </summary>
        public int? IdJustificativa { get; set; }
        public int? IdProjetoTipo { get; set; }
        public DateTime? DtAutorizacao { get; set; }
        /// <summary>
        /// Justificativa texto livre para uma solicitação de compra, se parâmetro de sistema estiver informando que este atributo é visível.
        /// </summary>
        public string TxJustificativa { get; set; }
        /// <summary>
        /// Data que o usuário necessita do produto entregue para orientar o setor de compra.
        /// </summary>
        public DateTime? DtNecessidadeAtendimento { get; set; }
        /// <summary>
        /// Informa se  a compra está ou não, prevista no orçamento.
        /// </summary>
        public bool InPrevistoOrcamento { get; set; }
        public DateTime? DtGeracaoPrescricao { get; set; }
        public DateTime? DtRecebimentoSolicitacao { get; set; }
        public int? IdClassificacao { get; set; }
        public int? InTermoVaga { get; set; }
        public int? IdAcomodacao { get; set; }
        public string TxLeito { get; set; }
        public DateTime? DtLiberacaoLeito { get; set; }
        public DateTime? DtCancelamento { get; set; }

        public virtual TipoDiversos IdAcomodacaoNavigation { get; set; }
        public virtual Atendimento IdAtendimentoNavigation { get; set; }
        public virtual TipoDiversos IdClassificacaoNavigation { get; set; }
        public virtual TipoDiversos IdJustificativaNavigation { get; set; }
        public virtual Pessoa IdMedicoNavigation { get; set; }
        public virtual TipoDiversos IdPrioridadeNavigation { get; set; }
        public virtual TipoDiversos IdProjetoTipoNavigation { get; set; }
        public virtual TipoDiversos IdStatusSolicitacaoNavigation { get; set; }
        public virtual TipoDiversos IdTipoSolicitacaoNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeExecutoraNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeSolicitanteNavigation { get; set; }
        public virtual Usuario IdUsuarioSolicitouNavigation { get; set; }
        public virtual PrescricaoPadrao PrescricaoPadrao { get; set; }
        public virtual ICollection<DevolucaoChecagem> DevolucaoChecagem { get; set; }
        public virtual ICollection<MensagemSolicitacao> MensagemSolicitacao { get; set; }
        public virtual ICollection<PrescricaoImportacaoUsuario> PrescricaoImportacaoUsuarioIdPrescricaoImportacaoNavigation { get; set; }
        public virtual ICollection<PrescricaoImportacaoUsuario> PrescricaoImportacaoUsuarioIdPrescricaoVisualizacaoNavigation { get; set; }
        public virtual ICollection<Rastreamento> Rastreamento { get; set; }
        public virtual ICollection<ServicoCheckinEnfermagem> ServicoCheckinEnfermagem { get; set; }
        public virtual ICollection<SessaoOncologia> SessaoOncologia { get; set; }
        public virtual ICollection<SolicitacaoHistorico> SolicitacaoHistorico { get; set; }
        public virtual ICollection<SolicitacaoImpressao> SolicitacaoImpressao { get; set; }
        public virtual ICollection<SolicitacaoIntegracaoSistemaLegado> SolicitacaoIntegracaoSistemaLegado { get; set; }
        public virtual ICollection<SolicitacaoPdEnfermagem> SolicitacaoPdEnfermagem { get; set; }
        public virtual ICollection<SolicitacaoProdutoDetalhe> SolicitacaoProdutoDetalhe { get; set; }
    }
}