// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class SolicitacaoInternacaoHistorico
    {
        public int IdSolicitacaoInternacaoHistorico { get; set; }
        public int IdSolicitacao { get; set; }
        public DateTime DtHistorico { get; set; }
        public int IdUsuario { get; set; }
        public string TxObservacao { get; set; }
        public int IdStatus { get; set; }
    }
}