// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class SolicitacaoPdEnfermagem
    {
        public SolicitacaoPdEnfermagem()
        {
            AntimicrobianoPedidoItemSolicitacaoPdEnfermagem = new HashSet<AntimicrobianoPedidoItemSolicitacaoPdEnfermagem>();
            LotePrescricao = new HashSet<LotePrescricao>();
            MedicamentoNaoPadronizadoSolicitacaoPdenfermagem = new HashSet<MedicamentoNaoPadronizadoSolicitacaoPdenfermagem>();
            SessaoOncologiaItem = new HashSet<SessaoOncologiaItem>();
            SolicitacaoPdEnfermagemHorarioAdministracao = new HashSet<SolicitacaoPdEnfermagemHorarioAdministracao>();
        }

        public int IdSolicitacaoPdEnfermagem { get; set; }
        public int IdSolicitacao { get; set; }
        public int? IdProdutoDetalhe { get; set; }
        public int? IdServico { get; set; }
        public int? IdTipoItemSolicitacao { get; set; }
        public int? IdIntervaloAdministracao { get; set; }
        public int? IdViaAdministracao { get; set; }
        public int? IdUnidadeMedida { get; set; }
        public int? IdCondicao { get; set; }
        public int? IdInstrucaoEspecial { get; set; }
        public int IdSituacao { get; set; }
        public DateTime? HrInicioAdministracao { get; set; }
        public bool? InHorariopadrao { get; set; }
        public decimal? QnPrescrita { get; set; }
        public decimal? QnMinima { get; set; }
        public decimal? QnTotal { get; set; }
        public int? QnDoses { get; set; }
        public int? VlVelocidadeAdministracao { get; set; }
        public int NrAssociacao { get; set; }
        public string TxObservacao { get; set; }
        public string TxDescricao { get; set; }
        public int? IdPrioridadeTipo { get; set; }
        public bool? InRealizaExameLocal { get; set; }
        public int? IdSolicitacaoPdEnfermagemUltimoHorarioGerado { get; set; }
        public string TxObservacaoSistema { get; set; }
        public int? IdRegiaoAplicacao { get; set; }
        public int? IdUnidadeMedidaExibicao { get; set; }
        public decimal? QnPrescritaExibicao { get; set; }
        public int? IdViaAcesso { get; set; }
        public int? IdProdutoOncologico { get; set; }
        public double? VlConcentracao { get; set; }
        public int? VlDoseHorario { get; set; }
        public bool? InFracionado { get; set; }
        public bool? InHorarioAtrasado { get; set; }
        public bool? ChecarVisivel { get; set; }
        public string Proximo { get; set; }
        public string Ultimo { get; set; }
        public string Horarios { get; set; }
        public bool? InUltimoLote { get; set; }
        public string TxCriterioUtilizacao { get; set; }

        public virtual TipoDiversos IdCondicaoNavigation { get; set; }
        public virtual TipoDiversos IdInstrucaoEspecialNavigation { get; set; }
        public virtual TipoDiversos IdRegiaoAplicacaoNavigation { get; set; }
        public virtual TipoDiversos IdSituacaoNavigation { get; set; }
        public virtual Solicitacao IdSolicitacaoNavigation { get; set; }
        public virtual TipoDiversos IdTipoItemSolicitacaoNavigation { get; set; }
        public virtual TipoDiversos IdUnidadeMedidaExibicaoNavigation { get; set; }
        public virtual TipoDiversos IdUnidadeMedidaNavigation { get; set; }
        public virtual TipoDiversos IdViaAdministracaoNavigation { get; set; }
        public virtual PrescricaoAnaliseItem PrescricaoAnaliseItem { get; set; }
        public virtual ICollection<AntimicrobianoPedidoItemSolicitacaoPdEnfermagem> AntimicrobianoPedidoItemSolicitacaoPdEnfermagem { get; set; }
        public virtual ICollection<LotePrescricao> LotePrescricao { get; set; }
        public virtual ICollection<MedicamentoNaoPadronizadoSolicitacaoPdenfermagem> MedicamentoNaoPadronizadoSolicitacaoPdenfermagem { get; set; }
        public virtual ICollection<SessaoOncologiaItem> SessaoOncologiaItem { get; set; }
        public virtual ICollection<SolicitacaoPdEnfermagemHorarioAdministracao> SolicitacaoPdEnfermagemHorarioAdministracao { get; set; }
    }
}