// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class SptAlteraDataHoraAlta
    {
        public string NmPessoa { get; set; }
        public DateTime? DtAtendimento { get; set; }
        public DateTime? DtAltaMedica { get; set; }
        public DateTime? DtAlta { get; set; }
        public int? IdAtendimento { get; set; }
    }
}