// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class SptContaitemhistorico
    {
        public int IdConta { get; set; }
        public int IdAtendimento { get; set; }
        public DateTime DtLancamentoItem { get; set; }
        public DateTime DtExecucaoServico { get; set; }
        public string CdServico { get; set; }
        public string TxDescricaoServico { get; set; }
        public DateTime DtOcorrencia { get; set; }
        public string TxDescTipo { get; set; }
        public string TxJustificativa { get; set; }
        public string TxLogin { get; set; }
        public int IdPessoa { get; set; }
    }
}