// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class SptServico
    {
        public int IdServico { get; set; }
        public string CdServico { get; set; }
        public string TxDescricaoServico { get; set; }
        public int? IdServicoCategoria { get; set; }
        public bool InExcecao { get; set; }
        public bool InAtivo { get; set; }
        public int IdAgrupamento { get; set; }
        public string CdAgrupamento { get; set; }
        public int IdTraducao { get; set; }
        public string TxAgrupamento { get; set; }
        public string CdTraducao { get; set; }
        public string TxTraducao { get; set; }
        public int IdServicoProdutoTabela { get; set; }
        public string NmServicoProdutoTabela { get; set; }
        public string TxRotulo { get; set; }
        public string VlIncidencia { get; set; }
        public int IdServicoIncidencia { get; set; }
    }
}