// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class SuprimentosMovimentacao
    {
        public int? IdProduto { get; set; }
        public DateTime DtSolicitacao { get; set; }
        public int IdCentroCustosPrestador { get; set; }
        public int? IdCentroCustosReceptor { get; set; }
        public int? QnSolicitada { get; set; }
        public decimal VlMedioUnitario { get; set; }
        public int InDevolucao { get; set; }
    }
}