// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TabelaExcecao
    {
        /// <summary>
        /// SQL_Latin1_General_CP1_CI_AS
        /// </summary>
        public string CdServico { get; set; }
        /// <summary>
        /// SQL_Latin1_General_CP1_CI_AS
        /// </summary>
        public string Expr1 { get; set; }
        /// <summary>
        /// SQL_Latin1_General_CP1_CI_AS
        /// </summary>
        public string TxDescricaoServico { get; set; }
        /// <summary>
        /// SQL_Latin1_General_CP1_CI_AS
        /// </summary>
        public string Expr2 { get; set; }
    }
}