// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TabelaCargaProcedimentoMedico
    {
        public int IdServicoProdutoTabela { get; set; }
        public string CdServico { get; set; }
        public string TxDescricao { get; set; }
        public string QnFilme { get; set; }
        public string QnIncidencia { get; set; }
        public string VlCustoOperacional { get; set; }
        public string QnAuxiliares { get; set; }
        public string NrPorteAnestesico { get; set; }
        public string VlHonorarios { get; set; }
        public string TxPorteProcedimento { get; set; }
        public string PrIndicePorte { get; set; }
        public string TxUr { get; set; }
        public bool? InSexo { get; set; }
        public int? QnMaximaExecucao { get; set; }
        public int? QnMediaPermanencia { get; set; }
        public int? NrIdadeMinima { get; set; }
        public int? NrIdadeMaxima { get; set; }
        public double? VlServicoHospitalar { get; set; }
        public double? VlServicoProfissional { get; set; }
        public double? VlServicoAmbulatorial { get; set; }
        public string CdCompexidade { get; set; }
        public string CdTipoFinanciamento { get; set; }
        public string CdSubtipoFinanciamento { get; set; }
        public string TxInstrumentoRegistro { get; set; }
        public bool InValorMonetario { get; set; }
    }
}