// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TabelaSul
    {
        /// <summary>
        /// SQL_Latin1_General_CP1_CI_AS
        /// </summary>
        public string CdServico { get; set; }
        public int IdServico { get; set; }
        /// <summary>
        /// SQL_Latin1_General_CP1_CI_AS
        /// </summary>
        public string TxDescricaoServico { get; set; }
        public int? IdServicoCategoria { get; set; }
        /// <summary>
        /// SQL_Latin1_General_CP1_CI_AS
        /// </summary>
        public string QnFilme { get; set; }
        /// <summary>
        /// SQL_Latin1_General_CP1_CI_AS
        /// </summary>
        public string QnIncidencia { get; set; }
        /// <summary>
        /// SQL_Latin1_General_CP1_CI_AS
        /// </summary>
        public string VlCustoOperacional { get; set; }
        /// <summary>
        /// SQL_Latin1_General_CP1_CI_AS
        /// </summary>
        public string QnAuxiliares { get; set; }
        /// <summary>
        /// SQL_Latin1_General_CP1_CI_AS
        /// </summary>
        public string NrPorteAnestesico { get; set; }
        /// <summary>
        /// SQL_Latin1_General_CP1_CI_AS
        /// </summary>
        public string VlHonorarios { get; set; }
    }
}