// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TabelaClassificacao
    {
        public TabelaClassificacao()
        {
            ItemClassificacao = new HashSet<ItemClassificacao>();
            RegistroEletronicoItemModeloAtributo = new HashSet<RegistroEletronicoItemModeloAtributo>();
        }

        public int IdTabelaClassificacao { get; set; }
        public string NmTabelaClassificacao { get; set; }
        public bool? InAtivo { get; set; }
        public int IdTipoTabela { get; set; }

        public virtual TipoTabela IdTipoTabelaNavigation { get; set; }
        public virtual ICollection<ItemClassificacao> ItemClassificacao { get; set; }
        public virtual ICollection<RegistroEletronicoItemModeloAtributo> RegistroEletronicoItemModeloAtributo { get; set; }
    }
}