// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TaxaFolhaDeSala
    {
        public TaxaFolhaDeSala()
        {
            ContaItemServicoTaxaFolhadeSala = new HashSet<ContaItemServicoTaxaFolhadeSala>();
        }

        public int IdTaxaFolhaDeSala { get; set; }
        public int IdTaxa { get; set; }
        public int IdProcedimentoPrincipal { get; set; }
        public int IdCheckinEnfermagem { get; set; }
        public int? QnUtilizado { get; set; }
        public DateTime DtInicio { get; set; }
        public DateTime? DtFim { get; set; }
        public int? IdKit { get; set; }

        public virtual Folhadesala Id { get; set; }
        public virtual KitTaxasGases IdKitNavigation { get; set; }
        public virtual Servico IdTaxaNavigation { get; set; }
        public virtual ICollection<ContaItemServicoTaxaFolhadeSala> ContaItemServicoTaxaFolhadeSala { get; set; }
    }
}