// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TelefonePessoaRelatorio
    {
        public string CdPais { get; set; }
        public string CdArea { get; set; }
        public string NrTelefone { get; set; }
        public string NrRamal { get; set; }
        public int IdPessoa { get; set; }
    }
}