// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Telefone
    {
        public Telefone()
        {
            AgenciaTelefone = new HashSet<AgenciaTelefone>();
            PessoaTelefone = new HashSet<PessoaTelefone>();
            UnidadeOrganizacionalTelefone = new HashSet<UnidadeOrganizacionalTelefone>();
        }

        public int IdTelefone { get; set; }
        public int IdOrigemCadastroTipo { get; set; }
        public int? IdEndereco { get; set; }
        public int IdTelefoneTipo { get; set; }
        public string CdPais { get; set; }
        public string CdArea { get; set; }
        public string NrTelefone { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public string NmNomePessoa { get; set; }
        public int? IdFiscad { get; set; }

        public virtual Endereco IdEnderecoNavigation { get; set; }
        public virtual TipoDiversos IdOrigemCadastroTipoNavigation { get; set; }
        public virtual TipoDiversos IdTelefoneTipoNavigation { get; set; }
        public virtual ICollection<AgenciaTelefone> AgenciaTelefone { get; set; }
        public virtual ICollection<PessoaTelefone> PessoaTelefone { get; set; }
        public virtual ICollection<UnidadeOrganizacionalTelefone> UnidadeOrganizacionalTelefone { get; set; }
    }
}