// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TextoPadraoPrescricaoItemTipo
    {
        public int IdTextoPadraoPrescricaoItemTipo { get; set; }
        public int IdTextoPadrao { get; set; }
        public int IdPrescricaoItemTipo { get; set; }

        public virtual TipoDiversos IdPrescricaoItemTipoNavigation { get; set; }
        public virtual TextoPadrao IdTextoPadraoNavigation { get; set; }
    }
}