// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TipoParametro
    {
        public TipoParametro()
        {
            ParametrizacaoSistema = new HashSet<ParametrizacaoSistema>();
        }

        public int IdTipoParametro { get; set; }
        public string TxDescricao { get; set; }
        public bool InAtributoTabela { get; set; }
        public string NmTabelaAtributo { get; set; }
        public string NmAtributoApresentacao { get; set; }
        public string NmAtributoGravacao { get; set; }
        public string NmAtributoTipo { get; set; }
        public int NrAtributoTamanho { get; set; }

        public virtual ICollection<ParametrizacaoSistema> ParametrizacaoSistema { get; set; }
    }
}