// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TipoDocumentoPessoaEntidade
    {
        public int IdTipoDocumento { get; set; }
        public int IdPessoaEntidade { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual PessoaEntidade IdPessoaEntidadeNavigation { get; set; }
        public virtual TipoDocumento IdTipoDocumentoNavigation { get; set; }
    }
}