// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TipoAlta
    {
        public TipoAlta()
        {
            AltaMedica = new HashSet<AltaMedica>();
        }

        public int IdTipoAlta { get; set; }
        public string NmTipoAlta { get; set; }
        public int? CdTipoAltaSus { get; set; }
        public bool? InAltaTiss { get; set; }
        public bool? InAtivo { get; set; }
        public DateTime? DtInicioUso { get; set; }
        public DateTime? DtFinalUso { get; set; }

        public virtual ICollection<AltaMedica> AltaMedica { get; set; }
    }
}