// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TipoNovoControle
    {
        public TipoNovoControle()
        {
            NovoControle = new HashSet<NovoControle>();
        }

        /// <summary>
        /// Identificador da tabela Tipo_Novo_Controle
        /// </summary>
        public int IdTipoNovoControle { get; set; }
        /// <summary>
        /// Descrição do campo
        /// </summary>
        public string TxDescTipo { get; set; }
        /// <summary>
        /// Indica se o campo está ativo ou não.
        /// </summary>
        public bool InAtivo { get; set; }

        public virtual ICollection<NovoControle> NovoControle { get; set; }
    }
}