// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TipoInventario
    {
        public TipoInventario()
        {
            Inventario = new HashSet<Inventario>();
        }

        public int IdTipoInventario { get; set; }
        public string NmTipoInventario { get; set; }

        public virtual ICollection<Inventario> Inventario { get; set; }
    }
}