// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TissprocedimentosUnimed
    {
        public int? IdLote { get; set; }
        public int IdConta { get; set; }
        public int? IdContaItemServico { get; set; }
        public int IdAtendimento { get; set; }
        public int IdGuia { get; set; }
        public DateTime? DtLancamentoItem { get; set; }
        public double? VlDesconto { get; set; }
        public decimal? VlTotalServico { get; set; }
        public double? VlCobradoItem { get; set; }
        public double? VlTotalDesconto { get; set; }
        public decimal? PrReducaoAcrescimo { get; set; }
        public double? VlGp { get; set; }
        public double? VlTotalGp { get; set; }
        public double? QnServico { get; set; }
        public string CdServicoReferencia { get; set; }
        public string TxDescricaoServicoReferencia { get; set; }
        public DateTime? DtExecucaoServico { get; set; }
        public string CdServico { get; set; }
        public string TxDescricaoServico { get; set; }
        public int? Erfuncao { get; set; }
        public int? Fifuncao { get; set; }
        public int? Fierfuncao { get; set; }
        public int IdServicoProdutoTabela { get; set; }
        public DateTime? HrInicio { get; set; }
        public DateTime? HrFim { get; set; }
        public string ViaAcesso { get; set; }
        public bool InTecnicaUtilizada { get; set; }
        public string NmMedico { get; set; }
        public int? NrConselho { get; set; }
        public int? UfConselho { get; set; }
        public string SgConselho { get; set; }
        public string CdCpf { get; set; }
        public int? IdEntidadeConselho { get; set; }
        public int? IdFuncao { get; set; }
        public int? IdEspecialidade { get; set; }
        public string CdUnimed { get; set; }
        public DateTime? DtAtendimento { get; set; }
        public int? IdServico { get; set; }
        public int IdOperadora { get; set; }
        public int? RvVersaoLinha { get; set; }
        public int Q { get; set; }
        public int IdFechamentoItem { get; set; }
        public int? IdMedico { get; set; }
        public int IdUnidadeOrganizacional { get; set; }
        public string FiTxDescricao { get; set; }
        public string FiNmClassificacao { get; set; }
        public string NrGp { get; set; }
        public int? IdServicoCategoria { get; set; }
        public int? IdPessoaUnidade { get; set; }
    }
}