// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Tissmensagem
    {
        public int IdOperadora { get; set; }
        public int IdTipoMensagem { get; set; }
        public bool InAtivo { get; set; }
        public int IdVersao { get; set; }
        public string TxEndereco { get; set; }
        public string TxLogin { get; set; }
        public string TxSenha { get; set; }
        public string CdPrestadorWebService { get; set; }

        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual TipoDiversos IdTipoMensagemNavigation { get; set; }
        public virtual Tissversao IdVersaoNavigation { get; set; }
    }
}