// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TissguiasLoteConsulta3
    {
        public int? IdLote { get; set; }
        public int IdGuia { get; set; }
        public int IdAtendimento { get; set; }
        public int IdConta { get; set; }
        public int IdOperadora { get; set; }
        public string CdRegistroAns { get; set; }
        public DateTime? DtGuia { get; set; }
        public string AtendimentoRn { get; set; }
        public int IdIndicadorAcidente { get; set; }
        public string InRetornoAmbulatorio { get; set; }
        public string NrGuia { get; set; }
        public string NrAutorizacao { get; set; }
        public string NrMatricula { get; set; }
        public string NmTitular { get; set; }
        public string NmMedico { get; set; }
        public string NrCrm { get; set; }
        public int? IdPessoaEntidade { get; set; }
        public int? IdEspecialidade { get; set; }
        public int? IdUf { get; set; }
        public int? IdServicoProdutoTabela { get; set; }
        public string CdServico { get; set; }
        public string TxDescricaoServico { get; set; }
        public double? VlFechamentoItem { get; set; }
        public DateTime? DtAtendimento { get; set; }
        public string RvVersaoLinha { get; set; }
    }
}