// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TissdiferencasomatorioitensXmlConta
    {
        public int? IdLote { get; set; }
        public int IdGuia { get; set; }
        public string NrGuia { get; set; }
        public int IdConta { get; set; }
        public int IdAtendimento { get; set; }
        public string TxDescricao { get; set; }
        public double VlTotalServicos { get; set; }
        public double VlTotalTaxas { get; set; }
        public double VlTotalMateriais { get; set; }
        public double VlTotalMedicamentos { get; set; }
        public double VlTotalDiarias { get; set; }
        public double VlTotalGeral { get; set; }
        public double Somatorioitens { get; set; }
        public double? Somatorioconta { get; set; }
        public double? Comparativo { get; set; }
        public int? Comparativo2 { get; set; }
    }
}