// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TissoutrasDespesas1
    {
        public int? IdLote { get; set; }
        public int CdTipoLancamento { get; set; }
        public DateTime DtLancamento { get; set; }
        public string CdTabela { get; set; }
        public string CdServicoExecutado { get; set; }
        public string TxDescricaoServicoExecutado { get; set; }
        public string PrReducaoAcrescimo { get; set; }
        public double QnSolicitada { get; set; }
        public decimal? VlUnitario { get; set; }
        public decimal? VlFechamentoItem { get; set; }
        public int IdConta { get; set; }
        public int IdGuia { get; set; }
        public int? IdServicoProdutoTabela { get; set; }
        public int? IdFechamentoItem { get; set; }
        public int IdOperadora { get; set; }
        public int V { get; set; }
        public byte[] RvVersaoLinha { get; set; }
    }
}