// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TissTipoDiversos
    {
        public int IdTiss { get; set; }
        public int IdTipoDiversos { get; set; }
        public string CdTiss { get; set; }
        public string DescTiss { get; set; }
        public bool InAtivo { get; set; }

        public virtual TipoDiversos IdTipoDiversosNavigation { get; set; }
    }
}