// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Tisstipo
    {
        public Tisstipo()
        {
            TissdePara = new HashSet<TissdePara>();
            TisstipoItem = new HashSet<TisstipoItem>();
        }

        public int IdTipo { get; set; }
        public string NmTipo { get; set; }
        public int IdVersao { get; set; }
        public bool InTabelaProdutoServico { get; set; }
        public bool InConfigura { get; set; }
        public string TxDescricao { get; set; }
        public string NmTabela { get; set; }
        public string NmCampoChave { get; set; }
        public string TxDescricaoCampoChave { get; set; }
        public bool InTipoDiversos { get; set; }
        public int? IdTipoTabela { get; set; }

        public virtual TipoTabela IdTipoTabelaNavigation { get; set; }
        public virtual Tissversao IdVersaoNavigation { get; set; }
        public virtual ICollection<TissdePara> TissdePara { get; set; }
        public virtual ICollection<TisstipoItem> TisstipoItem { get; set; }
    }
}