// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TisscabecalhoLote3
    {
        public int IdLote { get; set; }
        public string NmOperadora { get; set; }
        public string CdCnpj { get; set; }
        public string CdPrestadorOperadora { get; set; }
        public string CdRegistroAns { get; set; }
        public string CdCnpjOperadora { get; set; }
        public DateTime DtRegistroTransacao { get; set; }
    }
}