// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TissprocedimentosMedicoCooperado
    {
        public int? IdLote { get; set; }
        public int IdGuia { get; set; }
        public int IdAtendimento { get; set; }
        public int IdConta { get; set; }
        public int? IdMedico { get; set; }
        public string NmMedico { get; set; }
        public int? IdFuncao { get; set; }
        public int? IdEspecialidade { get; set; }
        public DateTime DtLancamento { get; set; }
        public decimal? NrReducaoAcrescimo { get; set; }
        public string CdServico { get; set; }
        public string TxDescricaoServico { get; set; }
        public int? IdServicoProdutoTabela { get; set; }
        public string ViaAcesso { get; set; }
        public double QdItem { get; set; }
        public double VlUnitario { get; set; }
        public double VlFechamentoItem { get; set; }
        public byte[] RvVersaoLinha { get; set; }
    }
}