// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Tisscarta
    {
        public string CdRegistroAns { get; set; }
        public int IdCartarecurso { get; set; }
        public int Objeto { get; set; }
        public string CdHospitalOperadora { get; set; }
        public string CdCnpj { get; set; }
        public string NmOperadora { get; set; }
        public int IdOperadora { get; set; }
        public int? NrLote { get; set; }
        public string NmHospital { get; set; }
        public string NrProtocolo { get; set; }
        public int NrGuiaRecOperadora { get; set; }
        public double? VlTotalRecursado { get; set; }
        public DateTime DtImpressao { get; set; }
        public string RvVersaoLinha { get; set; }
    }
}