// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TissfonteDados
    {
        public TissfonteDados()
        {
            TissfinalidadeCampoValor = new HashSet<TissfinalidadeCampoValor>();
            TissfonteDadosRelacionamentoIdFonteDadosFilhoNavigation = new HashSet<TissfonteDadosRelacionamento>();
            TissfonteDadosRelacionamentoIdFonteDadosPaiNavigation = new HashSet<TissfonteDadosRelacionamento>();
        }

        public int IdFonteDados { get; set; }
        public string NmFonteDados { get; set; }
        public string TxDescricao { get; set; }
        public bool? InRaiz { get; set; }

        public virtual ICollection<TissfinalidadeCampoValor> TissfinalidadeCampoValor { get; set; }
        public virtual ICollection<TissfonteDadosRelacionamento> TissfonteDadosRelacionamentoIdFonteDadosFilhoNavigation { get; set; }
        public virtual ICollection<TissfonteDadosRelacionamento> TissfonteDadosRelacionamentoIdFonteDadosPaiNavigation { get; set; }
    }
}