// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Tisshospital
    {
        public string NmHospital { get; set; }
        public int IdLogradouroTipo { get; set; }
        public string TxEndereco { get; set; }
        public string NrNumero { get; set; }
        public string TxComplemento { get; set; }
        public string Municipio { get; set; }
        public string SgUf { get; set; }
        public int IdUf { get; set; }
        public string Cep { get; set; }
        public string CdHospitalUnimed { get; set; }
        public string CdHospitalUnimedDraViviane { get; set; }
        public string CdCnpj { get; set; }
        public string CdPrestadorOperadora { get; set; }
        public int? IdLote { get; set; }
        public int RvVersaoLinha { get; set; }
    }
}