// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TissarquivoGerado
    {
        public int IdArquivoGerado { get; set; }
        public string NmArquivoGerado { get; set; }
        public DateTime DtGeracao { get; set; }
        public int? IdLote { get; set; }
        public string NrSequencialEspecifico { get; set; }
        public string XmArquivo { get; set; }
        public int? IdFinalidade { get; set; }
        public int? IdUsuario { get; set; }
        public int? NrSequencialGeral { get; set; }

        public virtual Tissfinalidade IdFinalidadeNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}