// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class TissprofissionalSolicitante3
    {
        public int IdAtendimento { get; set; }
        public int IdGuia { get; set; }
        public int? IdPessoa { get; set; }
        public string NmMedico { get; set; }
        public string NrCrm { get; set; }
        public string UfCrm { get; set; }
        public int? IdPessoaEntidade { get; set; }
        public int? IdEspecialidade { get; set; }
        public string CdSolicitanteOperadora { get; set; }
        public int IdOperadora { get; set; }
        public int RvVersaoLinha { get; set; }
    }
}