// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Tributo
    {
        public Tributo()
        {
            TributoAliquota = new HashSet<TributoAliquota>();
        }

        public int IdTributo { get; set; }
        public int IdTipoTributo { get; set; }
        public int IdPessoa { get; set; }
        public int IdTipoDocumento { get; set; }
        public DateTime DtCadastro { get; set; }
        public int IdUsuario { get; set; }
        public bool? InAtivo { get; set; }
        public string CdRecolhimento { get; set; }
        public int IdTipoRegimeRecolhimento { get; set; }

        public virtual Pessoa IdPessoaNavigation { get; set; }
        public virtual TipoDocumento IdTipoDocumentoNavigation { get; set; }
        public virtual TipoDiversos IdTipoRegimeRecolhimentoNavigation { get; set; }
        public virtual TipoDiversos IdTipoTributoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
        public virtual ICollection<TributoAliquota> TributoAliquota { get; set; }
    }
}