// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Tussdtsunimed
    {
        public string CdUnimed { get; set; }
        public string CdTuss { get; set; }
    }
}