// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Uniconit
    {
        public int UarSeqImp { get; set; }
        public string UctConNum { get; set; }
        public int UciSeqNum { get; set; }
        public string UciPreExe { get; set; }
        public int? UciMedCod { get; set; }
        public short? UciCphNum { get; set; }
        public string UciPreCob { get; set; }
        public DateTime? UciDatRea { get; set; }
        public string UciIteTip { get; set; }
        public string UciIteNum { get; set; }
        public short? UciGraPar { get; set; }
        public int? UciCodIte { get; set; }
        public decimal? UciQtdCob { get; set; }
        public decimal? UciQtdPag { get; set; }
        public decimal? UciVlrCob { get; set; }
        public decimal? UciVlrPag { get; set; }
        public decimal? UciQtdFilP { get; set; }
        public decimal? UciVlrFilP { get; set; }
        public int? UciQtdUt { get; set; }
        public decimal? UciVlrUt { get; set; }
        public short? UciPerPag { get; set; }
        public int? UciCptPag { get; set; }
        public string UciCodAde { get; set; }
        public string UciDesAde { get; set; }
        public string UciComPag { get; set; }
        public int? UciLinArq { get; set; }
        public int? UciCodIteH { get; set; }
        public string UciAdeAgr { get; set; }
        public int? IdFechamentoItem { get; set; }
        public int? IdConta { get; set; }
    }
}