// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class UnidadeOrganizacionalRecurso
    {
        public int IdUnidadeOrganizacional { get; set; }
        public int IdRecurso { get; set; }
        public bool InAgenda { get; set; }
        public int? HrTempoAtendimento { get; set; }
        public DateTime HrInicialAtendimento { get; set; }
        public DateTime HrFinalAtendimento { get; set; }
        public bool? InAtivo { get; set; }
        public int? IdGrupoHorario { get; set; }
        public byte[] RvVersaoLinha { get; set; }

        public virtual TipoDiversos IdGrupoHorarioNavigation { get; set; }
        public virtual Recurso IdRecursoNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeOrganizacionalNavigation { get; set; }
    }
}