// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class UnidadeOrganizacionalColaborador
    {
        public UnidadeOrganizacionalColaborador()
        {
            ClinicaUnidadeOrganizacionalMedicoVigencia = new HashSet<ClinicaUnidadeOrganizacionalMedicoVigencia>();
            UnidadeOrganizacionalColaboradorHorario = new HashSet<UnidadeOrganizacionalColaboradorHorario>();
            UnidadeOrganizacionalColaboradorTurno = new HashSet<UnidadeOrganizacionalColaboradorTurno>();
        }

        public int IdPessoa { get; set; }
        public int IdUnidadeOrganizacional { get; set; }
        public bool InSupervisor { get; set; }
        public bool? InAtivo { get; set; }
        public byte[] RvVersaoLinha { get; set; }
        public int? IdGrupoHorario { get; set; }
        public bool InAgenda { get; set; }
        public int? HrTempoAtendimento { get; set; }
        public bool? InPrincipal { get; set; }

        public virtual TipoDiversos IdGrupoHorarioNavigation { get; set; }
        public virtual Pessoa IdPessoaNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeOrganizacionalNavigation { get; set; }
        public virtual ICollection<ClinicaUnidadeOrganizacionalMedicoVigencia> ClinicaUnidadeOrganizacionalMedicoVigencia { get; set; }
        public virtual ICollection<UnidadeOrganizacionalColaboradorHorario> UnidadeOrganizacionalColaboradorHorario { get; set; }
        public virtual ICollection<UnidadeOrganizacionalColaboradorTurno> UnidadeOrganizacionalColaboradorTurno { get; set; }
    }
}