// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class UnidadeOrganizacionalCentroCusto
    {
        public int IdUnidadeorganizacionalCentrocusto { get; set; }
        public int IdUnidadeOrganizacional { get; set; }
        public int IdCentroCusto { get; set; }
        public string NrCentroCusto { get; set; }
        public DateTime DtCadastro { get; set; }
        public int? IdUsuario { get; set; }
        public bool? InAtivo { get; set; }

        public virtual CentroCusto IdCentroCustoNavigation { get; set; }
        public virtual UnidadeOrganizacional IdUnidadeOrganizacionalNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}