// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Uniiteer
    {
        public int UarSeqImp { get; set; }
        public string UctConNum { get; set; }
        public int UciSeqNum { get; set; }
        public short UieSeqNum { get; set; }
        public string UieCodGlo { get; set; }
        public string UieDesGlo { get; set; }
        public int? UieLinArq { get; set; }
        public decimal? UieVlrGlo { get; set; }
        public string UieIdcReap { get; set; }
    }
}