// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class Uniitead
    {
        public int UarSeqImp { get; set; }
        public string UctConNum { get; set; }
        public int UciSeqNum { get; set; }
        public short UiaSeqNum { get; set; }
        public short? UiaGraPar { get; set; }
        public short? UiaTipIte { get; set; }
        public int? UiaCodIte { get; set; }
        public decimal? UiaQtdPag { get; set; }
        public decimal? UiaVlrPag { get; set; }
        public int? UiaQtdUt { get; set; }
        public decimal? UiaVlrUt { get; set; }
        public int? UiaComAde { get; set; }
        public decimal? UiaVlrAnt { get; set; }
        public int? UiaComPag { get; set; }
        public short? UiaPerPag { get; set; }
        public decimal? UiaVlrCalc { get; set; }
        public int? UiaLinArq { get; set; }
    }
}