// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class UnimedPc
    {
        public int Codigo { get; set; }
        public double Fevereiro { get; set; }
        public double Maio { get; set; }
    }
}