// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class UnimedsConserto
    {
        public int? NumConta { get; set; }
        public int? NumeroContaHospitale { get; set; }
        public int? NumeroContaPHospitalte { get; set; }
        public int? IdArquivoUnimed { get; set; }
        public int? IdContaUnimed { get; set; }
        public string NumeroDaGuia { get; set; }
        public string SenhaGuia { get; set; }
        public string NumMatricula { get; set; }
        public int? OperadoraSistemaLegado { get; set; }
        public string NumItem { get; set; }
    }
}