// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DADOS.Models
{
    public partial class UsuarioOperadora
    {
        public int IdUsuario { get; set; }
        public int IdOperadora { get; set; }
        public bool? InAtivo { get; set; }
        public DateTime? DtValidade { get; set; }

        public virtual Pessoa IdOperadoraNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}